{
  "hash": "2737a16155484e7261e05efccff9a727",
  "result": {
    "engine": "knitr",
    "markdown": "# Blockchain.\n\nThe previous chapters stayed close to market data, trading, asset pricing,\nportfolio allocation, and portfolio risk. This final technical chapter changes\nthe object of analysis. Blockchain is presented as a special application of\nfinancial modeling ideas to distributed records, transaction validation,\ncryptographic signatures, and incentives. It extends the toolkit as a special\napplication at the end of the book.\n\nHere, we develop an example originally taken from Massimo Franceschet.\n\n-   [Blockchain Explanation](https://youtu.be/J-ab9was1p0)\n-   [How does a blockchain work - Simply Explained](https://youtu.be/SSo_EIwHSd4)\n-   [Asymmetric Encryption - Simply explained](https://youtu.be/AQDCe585Lnc)\n-   [What is a Bitcoin hard fork? Simply Explained!](https://youtu.be/XCo6yyutYAM)\n-   [Proof-of-Stake (vs proof-of-work)](https://youtu.be/M3EFi_POhps)\n-   [Will GDPR kill blockchains?](https://youtu.be/5I3wYAwbKMM)\n-   [Zero Knowledge Proof - ZKP](https://youtu.be/OcmvMs4AMbM)\n\nA blockchain is a distributed system using cryptography to secure an evolving consensus about an economically valuable token. Cryptography is a method of protecting information and communications through the use of codes, so that only those for whom the information is intended can read and process it. The prefix *crypt-* means hidden or vault, and the suffix *-graphy* stands for writing.\n\n## Block.\n\nA blockchain is a chain of blocks. Hence, we first describe a block. A block is a container for data. In its simplest form it contains:\n\n* An identification number, <tt>`number`</tt>.\n* A timestamp of block creation <tt>`timestamp`</tt>.\n* A bunch of data, <tt>`data`</tt>.\n* A reference to the previous block (parent block) in the chain, <tt>`parent`</tt>.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblock <- list(number = 3,\n             timestamp = \"2018-10-01 17:24:18 CEST\",\n             data = \"London\",\n             parent = 2)\n\nblock\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$number\n[1] 3\n\n$timestamp\n[1] \"2018-10-01 17:24:18 CEST\"\n\n$data\n[1] \"London\"\n\n$parent\n[1] 2\n```\n\n\n:::\n:::\n\n\n\nThis was a single unchained block. Now, let's introduce the concept of chain.\n\n## Chain.\n\nBlocks are concatenated into a chain. The first block of the chain is called the *genesis block* and has no parent block. The last block of a chain is the *current block* and is not parent of any other block (yet).\n\nHere is the genesis block of the Ethereum blockchain: https://etherscan.io/block/0\n\nLet’s chain some blocks.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Some blocks.\nblock1 <- list(number = 1,\n             timestamp = \"2018-10-01 17:24:00 CEST\",\n             data = \"London\",\n             parent = NA)\n\nblock2 <- list(number = 2,\n             timestamp = \"2018-10-01 17:24:15 CEST\",\n             data = \"Paris\",\n             parent = 1) # We chain the block with respect to the last one.\n\nblock3 <- list(number = 3,\n             timestamp = \"2018-10-01 17:24:30 CEST\",\n             data = \"Rome\",\n             parent = 2) # We chain the block with respect to the last one.\n\n# The blockchain:\nblockchain <- list(block1, block2, block3)\nblockchain\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[[1]]$number\n[1] 1\n\n[[1]]$timestamp\n[1] \"2018-10-01 17:24:00 CEST\"\n\n[[1]]$data\n[1] \"London\"\n\n[[1]]$parent\n[1] NA\n\n\n[[2]]\n[[2]]$number\n[1] 2\n\n[[2]]$timestamp\n[1] \"2018-10-01 17:24:15 CEST\"\n\n[[2]]$data\n[1] \"Paris\"\n\n[[2]]$parent\n[1] 1\n\n\n[[3]]\n[[3]]$number\n[1] 3\n\n[[3]]$timestamp\n[1] \"2018-10-01 17:24:30 CEST\"\n\n[[3]]$data\n[1] \"Rome\"\n\n[[3]]$parent\n[1] 2\n```\n\n\n:::\n:::\n\n\n\nThis is how we can get one block from the blockchain.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the 2nd block.\nblockchain[[2]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$number\n[1] 2\n\n$timestamp\n[1] \"2018-10-01 17:24:15 CEST\"\n\n$data\n[1] \"Paris\"\n\n$parent\n[1] 1\n```\n\n\n:::\n:::\n\n\n\nLet’s also write a validation function for the blockchain. For now, we only check that the parent field of a non-genesis block references to the previous block in the chain. Therefore, we validate a blockchain as long as its sequence is correct. This validation rule is simple and enough for the toy example. For example, first the genesis, then the first one, then the second, and finally the third.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Returns false if the blockchain sequence is not correct.\nvalidate <- function(blockchain) {\n  if (length(blockchain) >= 2) {\n    for (i in 2:length(blockchain)) { # We skip the genesis block.\n      if (blockchain[[i]]$parent != blockchain[[i-1]]$number) {\n        return(FALSE)\n      }\n    }\n  }\n  return(TRUE)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvalidate(blockchain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\nOur blockchain is valid. At the moment the validation criterion is quite simple. The next subsection introduces a more strict validation criterion.\n\n## Hash.\n\nThe linking structure of the chain is more complex than one described above: each block in a blockchain is identified by a hash value of its content and references to the hash of the parent block, or 0 if the block is the genesis one.\n\nHashes of blocks are created using cryptographic hash functions, that are mathematical algorithms that maps data of arbitrary size to a bit string of a fixed size (called hash or digest). The hash is used to certify the information content of the block: by modifying even a single bit of the content, the hash completely changes. Furthermore, notice that the digest of the current block is computed in terms of the previous block digest. This means if you alter one block you need to modify its hash and the hash of every following block for the chain to be valid.\n\nAs a result, a hash function for three blocks looks like this:\n$hash_3 = f_3(f_2(f_1(block_1), block_2), block_3)$.\n\nThe hash algorithm used here (SHA-256) is part of SHA-2 (Secure Hash Algorithm 2), a set of cryptographic hash functions designed by the United States National Security Agency (NSA). In particular, it uses digests of 256 bits (or 32 hexadecimal figures). See for example:\n\nhttps://emn178.github.io/online-tools/sha256.html\n\nIt is implemented in R package <tt>`digest`</tt>.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creates hash digests of arbitrary R objects.\nlibrary(digest)\n\n# Hash a string.\ndigest(\"A blockchain is a chain of blocks\", \"sha256\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"5c2005976411a1628fabcdde3ac04be563d18943e710b7446afa2a8a5fab9abc\"\n```\n\n\n:::\n:::\n\n\n\nThe hash 256 has a length of 64 characters.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnchar(\"A blockchain is a chain of blocks\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 33\n```\n\n\n:::\n\n```{.r .cell-code}\nnchar(\"5c2005976411a1628fabcdde3ac04be563d18943e710b7446afa2a8a5fab9abc\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64\n```\n\n\n:::\n:::\n\n\n\n\nLet's implement the hash in the blockchain construction.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Hash blocks.\nblock1 <- list(number = 1,\n             timestamp = \"2018-10-01 17:24:00 CEST\",\n             data = \"London\",\n             parent_hash = \"0\")\n# Note that the whole block1 content is used to generate the hash.\nblock1$hash = digest(block1, \"sha256\")\n# The new block2 has block1 hash as the parent hash.\nblock2 <- list(number = 2,\n             timestamp = \"2018-10-01 17:24:15 CEST\",\n             data = \"Paris\",\n             parent_hash = block1$hash)\n# Note that the block 2 hash has block1 hash.\nblock2$hash = digest(block2, \"sha256\")\n# The new block3 has block2 hash as the parent hash.\nblock3 <- list(number = 3,\n             timestamp = \"2018-10-01 17:24:30 CEST\",\n             data = \"Rome\",\n             parent_hash = block2$hash)\n# Block 3 hash has block2 hash, which at the same time has block1 hash.\nblock3$hash = digest(block3, \"sha256\")\n# The blockchain.\nblockchain <- list(block1, block2, block3)\nblockchain\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[[1]]$number\n[1] 1\n\n[[1]]$timestamp\n[1] \"2018-10-01 17:24:00 CEST\"\n\n[[1]]$data\n[1] \"London\"\n\n[[1]]$parent_hash\n[1] \"0\"\n\n[[1]]$hash\n[1] \"e4064e41f246cba04e0e7d58418294c4e099aefff48f7e871f65a77aebbe8243\"\n\n\n[[2]]\n[[2]]$number\n[1] 2\n\n[[2]]$timestamp\n[1] \"2018-10-01 17:24:15 CEST\"\n\n[[2]]$data\n[1] \"Paris\"\n\n[[2]]$parent_hash\n[1] \"e4064e41f246cba04e0e7d58418294c4e099aefff48f7e871f65a77aebbe8243\"\n\n[[2]]$hash\n[1] \"12dfcc49b856a2d2c6a941b9166ee14d276811e453f11a24f7bef8aa3247966d\"\n\n\n[[3]]\n[[3]]$number\n[1] 3\n\n[[3]]$timestamp\n[1] \"2018-10-01 17:24:30 CEST\"\n\n[[3]]$data\n[1] \"Rome\"\n\n[[3]]$parent_hash\n[1] \"12dfcc49b856a2d2c6a941b9166ee14d276811e453f11a24f7bef8aa3247966d\"\n\n[[3]]$hash\n[1] \"22628b887626257faa3109dd7f786e88ea0d5ebe021a534afaef3ced3ad193d1\"\n```\n\n\n:::\n:::\n\n\n\n\nThe hash of block 3 depends on the block 3 information and the block 2 hash, which at the same time depends on the block 2 information and the block 1 hash. The blocks are chained.\n\nLet’s update the validation function. Now, we check that the parent field of a non-genesis block references to the correct hash of the following block.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalidate <- function(blockchain) {\n  for (i in 1:length(blockchain)) { # Check for the correct hash.\n    block = blockchain[[i]] # Evaluation starts.\n    hash = block$hash # Take the declared hash.\n    block$hash = NULL # Otherwise we cannot create the expected hash.\n    hash_expected = digest(block, \"sha256\") # Expected hash.\n    if (hash != hash_expected) { # If true, then the blockchain is invalid.\n      return(FALSE)\n    }\n  }\n  if (length(blockchain) >= 2) { # Check for the consecutive hash.\n    for (i in 2:length(blockchain)) {\n      if (blockchain[[i]]$parent_hash != blockchain[[i-1]]$hash) {\n        return(FALSE)\n      }\n    }\n  }\n  return(TRUE)\n}\n```\n:::\n\n\n\n\nTest our blockchain again.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalidate(blockchain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n\nLet's test the validation algorithm. Here, we change London by Budapest and nothing else.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblockchain[[1]]$data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"London\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# alter data of first block\nblockchain[[1]]$data = \"Budapest\"\nvalidate(blockchain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\nIt works. We cannot change one block bit of information because the blockchain become invalid. Let's restore the original information.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# restore data\nblockchain[[1]]$data = \"London\"\nvalidate(blockchain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\nAnother test of the validation algorithm. Now, we change London by Budapest and we update the corresponding hash in block 1.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Alter data and hash of first block.\nblockchain[[1]]$data = \"Budapest\"\nblockchain[[1]]$hash = NULL\nblockchain[[1]]$hash = digest(blockchain[[1]], \"sha256\")\n\nvalidate(blockchain)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] FALSE\n```\n\n\n:::\n:::\n\n\n\nWorks well. The hash of the second and third block would have to be altered as well, otherwise the blockchain is invalid. Remember the hash dependency looks like this:\n$hash_3 = f_3(f_2(f_1(block_1), block_2), block_3)$.\n\n## Proof-of-Work.\n\nHash alone is not enough to prevent tampering, since hash values can be computed fast by computers. A Proof-of-Work (PoW) algorithm controls the difficulty of creating a new block. For blockchains like BitCoin or Ethereum blocks are created (mined) by so-called *miners*. When a new block has to be created, a hard computational problem is sent out to the network. The miner which solves the problem first creates the new block and is rewarded in crypto currency.\n\nIn the case of BitCoin the PoW problem involves the problem of finding a number (called *nonce*) that once added to the block is such that the corresponding block hash contains a certain amount of leading zeros called difficulty (more specifically, Hashcash). The average work that a miner needs to perform in order to find a valid nonce is exponential in the difficulty, while one can verify the validity of the block by executing a single hash function.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nproof_of_work <- function(block, difficulty, print = FALSE) {\n  block$nonce <- 0 # Add a nonce=0 to the block as a starting point.\n  hash = digest(block, \"sha256\") # Generate the hash of the block.\n  zero <- paste(rep(\"0\", difficulty), collapse = \"\") # Number of leading 0's.\n  while(substr(hash, 1, difficulty) != zero) { # Hash has not the leading 0's.\n      block$nonce = block$nonce + 1 # Add 1 to the nonce value.\n      hash = digest(block, \"sha256\")  # Generate the hash of the block.\n      if(print == TRUE) {print(hash)} # Print only if TRUE.\n  }\n  return(list(hash = hash, nonce = block$nonce))\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# This block will allow us to evaluate the function above.\nblock <- list(number = 1,\n             timestamp = \"2018-10-01 17:24:00 CEST\",\n             data = \"London\",\nhash =\n  \"88e96d4537bea4d9c05d12549907b32561d3bf31f45aae734cdc119f13406cb6Parent\",\n             parent_hash = \"d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3\")\n```\n:::\n\n\n\n\nHow difficult is difficulty 1?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Evaluate a difficulty of 1 (one leading zero)\nproof_of_work(block, 1, print = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2ac786a13832b45ccf25466aec83ef714dae4562c9573511dedc10543568562c\"\n[1] \"80d238e881cb74c5dd100adb12a7ba5d6c84ff1759320b1eda3fdc74eb205d52\"\n[1] \"d51eeaf4dc82d6c52b452c9685c7fdf8d347c3612f7cb46c9e3fe1a6baff73a2\"\n[1] \"495fbc7ec32f0edffc9af8344832f0a83ccf1f8ec4c650661620e38ddb5947ab\"\n[1] \"a7d86c47ba718439066df81bffff60a41d3cd614ba31a93faed4c609a04b9c7e\"\n[1] \"0a72347fbbe9ac46481b6499e3bcacd394f267d4c3d8a0544e00978fc124fe2f\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$hash\n[1] \"0a72347fbbe9ac46481b6499e3bcacd394f267d4c3d8a0544e00978fc124fe2f\"\n\n$nonce\n[1] 6\n```\n\n\n:::\n:::\n\n\n\nIt takes 6 iterations to solve the problem of difficulty 1. Quite easy for a computer. How difficult is difficulty 2?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Evaluate a difficulty of 2 (two leading zeros)\nproof_of_work(block, 2, print = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"2ac786a13832b45ccf25466aec83ef714dae4562c9573511dedc10543568562c\"\n[1] \"80d238e881cb74c5dd100adb12a7ba5d6c84ff1759320b1eda3fdc74eb205d52\"\n[1] \"d51eeaf4dc82d6c52b452c9685c7fdf8d347c3612f7cb46c9e3fe1a6baff73a2\"\n[1] \"495fbc7ec32f0edffc9af8344832f0a83ccf1f8ec4c650661620e38ddb5947ab\"\n[1] \"a7d86c47ba718439066df81bffff60a41d3cd614ba31a93faed4c609a04b9c7e\"\n[1] \"0a72347fbbe9ac46481b6499e3bcacd394f267d4c3d8a0544e00978fc124fe2f\"\n[1] \"7d8d9144dd86cf70b24010534497970ae1e89ff7df03645d781ffbc4c5350988\"\n[1] \"abb9814a9680c1ba7c970eb5f8965e01f074af7547243db9d94b0a44908d5b1a\"\n[1] \"c61eebd36518426ac3510280eb698484856a2c9b93e1a534298cf11a3d7a62f9\"\n[1] \"7fe608cd3784913fed93e01263e9d013a337adbd562ee76280e4775d24adeabd\"\n[1] \"0e1344bc16dbbb1ee2ee2687a47925bcc82582e7fd90b281400ec9b467e81f68\"\n[1] \"35979c8a93866a4ec7d8e1ca1a5c9a1746c60c18d80d885d2d66fe67c773fcc0\"\n[1] \"3cd3f8a34fa46d01b4faedb6309a19b917fa133cede66d186ac4d5eb20685493\"\n[1] \"3fcab70d4a7710a16fa23b6f63024159987b3b95fb62841e60dfb824aff22d7e\"\n[1] \"89168037cbc585eed85f318b8063d48f350410052b47aa51a67e2a1a6a20870e\"\n[1] \"c233234c2ff42b73c4c633d6bd54b197a33774da062e48d02b384efe64cff332\"\n[1] \"75f98266dfa61fd5578f942f5140bbe58c6bbd285dab7375595b0ddaa29ce6ab\"\n[1] \"955d82a9f0ca7d4eaeb51ff65551b0eb5c3416c89252f6530e286d28abb22d01\"\n[1] \"5c5e31b26f1761d74e7409312d658be0053e5519ddfef914453a552e65832e4c\"\n[1] \"6cb0f90002461d203f826aa63c2abe950da14d986395b6625c03d652f3bcc15c\"\n[1] \"5b05120be9c2acaa937c6e8ed703d9c46c314e1bb8ec44cb8575716c7fbfc575\"\n[1] \"1dc89bb3f3d3168e141a78d478ef0416b9db35db49ea29d83b39d4fd39fcf137\"\n[1] \"11eb55ea6aa08526ea29fcbb7b2627571ce4a7ee64214f9a97bb7c11e41f65e6\"\n[1] \"4ed393b7603b7dcaf2c39936d8261189ac5d3fddcdd26a9c8be93da87e4f3b8a\"\n[1] \"1f0bb59cfc4dc2e50aa0721bc9cddc28eb1a31d64ec90c86a4579df6147342df\"\n[1] \"3bbf029721533141094663e2b9b2bb9ec7d69b299c1e5945bacd77dd5c736138\"\n[1] \"b4edd13b1f670ce9c0d66c17bb7bee6ddcb64a194f3d040d5df20b3a28c2b46e\"\n[1] \"b5a553d535ad26d10b4e7e8cfcc27a35696a7ce75bb1a5f1dd4322c5039877f2\"\n[1] \"186a2116c7fa43bb97c0573e6878b3260b57b1f854caa0412b0a45dc456f2ba2\"\n[1] \"ec5eb69718fb8a01bf0da8fe5320571f3671e740a8c7bc799224b8da069d7748\"\n[1] \"436460d156efc75f8c038c45544bbb14fc0261c3b83bdb576d36e145c759b285\"\n[1] \"2081ced993d0faa150a8780cff8793a871b171b775903a3e5d844c6935c8fbc7\"\n[1] \"332c6d6acf42dfef8b67a956367c4c318e56dca912b002ab51e62b495452eeb6\"\n[1] \"5193a0f62d3c57e03817228efe8c624d19e22424d529c0ceee0dcef5615c1ee7\"\n[1] \"6f0fc844d5c1ca51f9f64d2c34edd41fc12b3b5670cb9ae9b0f5dcb4214e90ee\"\n[1] \"1e399483289deafbcd0e08b5475ce984838ef09362fea3c89df8e9cd708235ae\"\n[1] \"49e12d2adde1c3e406a425552b676cd6b6c5006a91fb9ef02ece4f88f6dc150c\"\n[1] \"8d6e35c790d3e5a8d4b1b262433d81de2628a227133a036aa758b45f16b712ff\"\n[1] \"4a6aa4b71b76f38c063180c1506b2c0b96362f439fcb597fedf39d9bdb465ff1\"\n[1] \"23d12c93c530f0d7642ab4e60d0d3ec4ed71429f75c8d9b43810058a3c795a80\"\n[1] \"6e1912048fb80b8a6e7f4f8edde9ff79ade8b0f28c8e4f901294d4a8f7345586\"\n[1] \"4533c74f4933d43730495774af13db8d0d7c917522e16fcd0f55062afce09be0\"\n[1] \"82d16a1b0e2927216c8a241cb45fa0151cd40192b1c084e8e5b9a086f2a7c8cf\"\n[1] \"0cd03a81725e5133e68a693d99a8763335eb13d65f2fa1e3a2b6a1e9badca154\"\n[1] \"acf65bdea8bc4729749363cfe4e8ee268e8640c056c025955c0458de3b4b44ca\"\n[1] \"5981a2f324b01a80674f016eaa4fe44fe577842a9d825ef8e5ed06801978b865\"\n[1] \"8365e175af54bf134f21ef5b80c1aea66604893db27ba829118466b255d93c04\"\n[1] \"c98b16c8ea2928361a4ede39d38638e8927d0e6bbf5ce1f688b2fddde02e82af\"\n[1] \"2dafb2f5487cae69c48eedcb3bef62b6bf697a3e00cd359cc30e46e1b21bc46c\"\n[1] \"7aafae605f73a701ece38a1fe7e292ade217ecf99f8fcc45f759c34fcd83002d\"\n[1] \"eefac2bb3d27c16467125cab3be6470ea5a7d4edc749e1b3a6991fdc7f953ab7\"\n[1] \"706238f0d708202d409979ab444f044ed334b22e251331605bf81e8a5e5ffdd7\"\n[1] \"cc4aefc81929ac048f9ee988e32f5ede146afaa0016a05f8f94c9cce9324c69b\"\n[1] \"20c7a47dcc8bddba10358e39ea7cacf7d2a3bf783cc076117514a9b561a67700\"\n[1] \"1b3c6f6ec9abbad479df717fb62ceeccfe0c00371c8e4c541d68889cdd5fee98\"\n[1] \"07dc06fe1d907c5d018c53d6433c38f92f1d27ff7327492d2d3e0e43fbb1c837\"\n[1] \"70a1705abde4f30ac8e5c9ebdad79041d959de16607284e9b5add1c968686b05\"\n[1] \"f12a87c31615488e93f157b3b7925462a337c89778780f5a8086e5a5c0c56002\"\n[1] \"907ab7af7655531cb841b08db754cc790d8a6bcd3147310c66f5eae2db35401a\"\n[1] \"70d73d143c9e756754172d6eb9546d1f461bda31f2aa0de7e47c336368ea9286\"\n[1] \"a4de79e953f370022e4d6f511b928551587c42a0c849020f64c4605b33626b15\"\n[1] \"77b56e696d6ef39a954804412df280bfac81db42148f5e8f80127c0139c83ea6\"\n[1] \"f1491dc9536143365f8898d3d2adf6fc7871fa8be6bd27e89d9bb8f195dbd58c\"\n[1] \"ac0041cad81f86bd7625ee07e9769f6286bfeeae51e8b5c1ecd8351983d7cc9d\"\n[1] \"813f37737ea36c1ba97b5585f3bb16a13145b5f89e564d71248df36723165201\"\n[1] \"1a11c0669487cddeb9c7d2c37f89b3cd9bd0e3cf7beb9b7e2ab2eff8d826eff8\"\n[1] \"16e4f4a9308bb10784d212214270f1aea7d77f3320bd80427f72e40a19d5ff5c\"\n[1] \"1da929217ccdfd4f80e2c2c5e9fde25dea6c3980c54e5637fffe001f80bc9747\"\n[1] \"cbd56cca5f9ba3b0a7c7533c1c6015e719cf9e5402ea70ba7b1bd6b1c6489263\"\n[1] \"072fcf30ef73d861af1cdc73d29097fb0bf6482a09607e58fc79eb69a98329ad\"\n[1] \"53d8a89a4bee7db969c85abc5c7201b3a94751ba0a5566a3da5917a62e2a881d\"\n[1] \"a01522b8b24fcd160bf6b650b214ca7ce5ad66d3ee5aacdb6b7331d35d38abb8\"\n[1] \"4f1acdd38c7f87d99319012003483c7b3f2cd5c4b3046eba8b5d8181aee261ee\"\n[1] \"6e7a41a5c635cb692b6be1f180a6df8b2f35cd636df4861a80ab86448b2095c8\"\n[1] \"a310750d90857ed7b24527ddbc0cdf81049990becbf27004869adabc2c4b1013\"\n[1] \"305c739452d9a5d2f0f0b7785cc6fcbfa0d97d08ef52bc2d38c4756abd532b54\"\n[1] \"b59b0bb62486aea41ed1e79a9fa2a96be5cb569e25b6e4a855156ee7dad4cf31\"\n[1] \"4ff6199ec0734b9f7073b1ad2fb309dc42abab36dd4986d4e7aeae639affc4b4\"\n[1] \"d6ddaadaf7ea44af2ecc9ce19f97600391a30126ef10994c62667f710ca69090\"\n[1] \"2173de29b60f2275e8fac1e165676f2c276cfce19ddfe55a509dfc507f3566f9\"\n[1] \"41277987e6d0943ac5cdde53f398dd5a7c5ea49695437ec0a8e79aab5b5641ee\"\n[1] \"5c855c099e96e5327b93ba5ae16af6a98b3755cdd9c044db1632030ac0fb4764\"\n[1] \"fcff924a7cd4030544bc26412fc06baafae168bf9c733eedf35ca8c9e29866fe\"\n[1] \"84104b2db9f7de1a18c337d63f8ec1a0e7622d693b0b34b69d1f26c6fdd95b62\"\n[1] \"ef263baf2f39716ed981556a8ceed3f9b7d494aca0030bb08c8f7a76f568af66\"\n[1] \"1bc17844a4c77e70dd9c95545e6490011db36b78b9f8bae3f2d2876c1a25e72a\"\n[1] \"683211739c5519be35016bd7db8812e272d839c26aeace423c2786e296cbe7eb\"\n[1] \"049c9ae3a95d7d806cf0bdfbc3aaa8b66a370adf66d918671cc501b7eb16893c\"\n[1] \"98068d9988acf648dbe3768a6f4f9aaadfc4e4cacd8acacc73288bb7c3049c18\"\n[1] \"456fc562f458f3b0d0dfdfc148965520ec5ee12aa7c3b715bc38b1122e2b1d68\"\n[1] \"ac3af32e229d572a8a945a22b23a9522c2d3a121cb77a813686ef742714800a7\"\n[1] \"3657d923f73dca7f12fca7001cdb757c817b8697af1e2c42d45147bc84463fe8\"\n[1] \"3442caf8b04a69ba355b8948d4e065a03bde0120516ca3f6ea8914dce3f987bd\"\n[1] \"cacd037f2f9b610acfcd8ec44a3721c0c2144de59bb5450d18367d9044f91360\"\n[1] \"7ace1e58c1222cf7c1e0df4bca9356e238cb6a713e247a07b0735d4b07584ed9\"\n[1] \"9104d8a71ec23a48ee2f1dde07acbe7a8072bcfa7d20f189fbad2904dfeb78d2\"\n[1] \"860abeb5ed9e479c879b8d3caa0ecfb97e2c30c609d80a6f5a88d2fbe916a1fc\"\n[1] \"5162ec75fc2dd6b382e2f4f3c00a0f615954a11de4ecf44006b88ec44f99539a\"\n[1] \"1f931b0d9af7b9d580e3a163e5e86d9e012deedd22aaacd43d3103a25374f7a2\"\n[1] \"c8b722b23c5e40ba2f2525515b876be5ebad271060cb53f7838f2c8ed263e148\"\n[1] \"b5c405a0db9f29811a72a2c41ad95fbed4d6e9c415d4116f7b0b278e5f54d260\"\n[1] \"87b5a6962debb873e956ce00b2ccd795cbc79e28626eae87fe451a759056d269\"\n[1] \"46833431670435f7f6f90285075ddd5a34576ca758953c01f937d170674cacec\"\n[1] \"fb3d6f18a15b0a2cb56620e98edb5e9859d8b00aa3b4f4471665ba544590b065\"\n[1] \"39e5cef0b6fab302c47756379956c251595eab426437a69deb2235bd3e57012d\"\n[1] \"9252f22d653092513e7884a9683f8da284e6f0ce569319eb84a2ad76b5706cbc\"\n[1] \"66a709069db59ff4784db4227969a2e0e16b087363ee724dae3e078088821a14\"\n[1] \"3b2e9ddc6f7f4902de3a01ad59b9dc04530aa31202b91526ee2d51a2fb0c00da\"\n[1] \"21514f1f808593feecf52cc2b9b2f9b56619af9c4d0faaad82d48731c367b557\"\n[1] \"219c7d2727e44929f38d1f5e36f1bc616a31d04bd097245788c2e1d9f919b077\"\n[1] \"1093ed88bb41127ada9191ce767d301f53589821d69e88ea8858e55d39e793ae\"\n[1] \"9c07c5aaec78eacec5078e30cdeed30353d3f265a7bdafc39b596b08bb69ee57\"\n[1] \"c6c998cf58a382829f19e178b852db5648caa1432b022ee80a178d707654eaac\"\n[1] \"1823ef4d4d8d90a63e9400fc80f23f83b71f12310415706db18c9095c9795e51\"\n[1] \"1314d466891aab41490ffd96dcb8b75f7574f05dbe7c3f19caa76a486fb21b71\"\n[1] \"5d1583ef53ad165c7391e04e91375c1759808db3ca69d756c3c6c139cf6f3720\"\n[1] \"ae8ab2358f553a5a215690042c1e70de8b4b5c4ee508dd59245677f3989a1563\"\n[1] \"ad4eeb607d10505eea0509fa15bc777d24f11b1ec087a2e3d6021a05d9b60659\"\n[1] \"8ac87302354e7a84e69f4c21b1080e94c4bdb6e81dbe6f9416260063ced369cc\"\n[1] \"a8b2e8a1b078555263811dabfa5cb093ef4dcf101441af63ff95f4a1a28945c8\"\n[1] \"4d0e1bf41f146c6adf07123e4ab762402a77f0c3c8a006d625f30277b47affcb\"\n[1] \"50f556421663748be602a3b38bfe4adfbf882228320134c029b91e68214e8a68\"\n[1] \"5391020a77657d85a8e4c3d663d931efdb236c998e4d0f378ac0a63d3696c5f4\"\n[1] \"1e9840d0fffde05227c7979e464143d29302c197585fe731dd6528f72adcfa51\"\n[1] \"6167a09373071a5ba01fcde8272f370efff1d88abd54ca704a7126db1a523023\"\n[1] \"be6cda1e9261fed00192044908a4cf679e536fd9684111a61ce35c70d8be9be7\"\n[1] \"fa1456d8392dba2d27c5bda83e20bdb0295614a91569bb85f00c69eabb88540e\"\n[1] \"b9e211bbed593135b2f58e1cc412e6166702c67dfdab358fdc74183f6a945e93\"\n[1] \"8771dd4f9bc9da3c0744a2b733adc3dd479762085464d5f08719795d41ab5d07\"\n[1] \"74821c8f2a305c3eac7b9bc9c809f39811f652e88869fc03b227368f3f1b17b0\"\n[1] \"551301f75871d4feb21289ad44113ff8b394347ddd6d30c9c4eccd784167a41c\"\n[1] \"55a261ba8cfd352ca563eb9d62c1dcd6a3c3303543b2171c6b4b21dcb0b5d1bf\"\n[1] \"d249e152c0cabbd2d8e1914e95782c7c8e1c52b804d1a0b280d886b104a63d07\"\n[1] \"5940cc54f0a5433a6162bd37e47c159b19ebe04c3d2e7e89bd76e2f2e783647e\"\n[1] \"419b96e236b29536aae8908681df2d554317e54342f4563603cce2ce821c6e82\"\n[1] \"10010e32757342c7d51275cb96e1a7d78094724121d63ce1cd497c659da0a9f9\"\n[1] \"cac1870358b94529781cd46abff8c41b3d3a09638820e015648d4ce2e67f44d0\"\n[1] \"e44814b8a26051bd63c4b162c19c6b387d0174b36bf13f4bdf0f36cbaffdfec2\"\n[1] \"850617605c3d60ecd0145bfe4a8053fa529e9061f46824d3b902f8706161ee8c\"\n[1] \"4a5f0d925bc3e6641ecedf78487fc6fa23efb0ad5a00708d80e6210271f8e881\"\n[1] \"690bf0da1035be54725598ea0b30589bf09b2fe2298c4e021ca90b52fac634bf\"\n[1] \"e4aea7dcaa870a731fc2a3a04b318540a3a21fee406dfa098fb467e22f49380f\"\n[1] \"79215c4cc40681dfd88dedd5df0d1fd4f7b62a7fb64abde4ee2848b25c19df1a\"\n[1] \"13a08458d3af517b14e055f08d9852b22077844c7b372b73edaf479125ff51f7\"\n[1] \"5e57c85f8c9f603ddea5bbb312ff0261869be4581e582cfea5c2cab4b8f8236e\"\n[1] \"683c94a5d35aae72308415911e50414bf8d3f0813cca154e28e0b148524df9b7\"\n[1] \"cc0b40e48c3bb9ae06df848fa49873f5cf5d1f72991ba8280553ed68e4eb533e\"\n[1] \"80e7ddf3fee383209542a8ec40de5f923a3f81cd74d10b7a0552898b40aef5ee\"\n[1] \"50bbe55e82304fbcbc6a385dcf2625f8dbc6138dd2919791431c744fe5ed81e1\"\n[1] \"d1339007864e3dc8f59e2eae95bea59512818abadcae1ca98785cbed87b5879e\"\n[1] \"2eec1a0c571a37322daa637766a087db6d0c0075f5465af4e552f233bfdfa081\"\n[1] \"34dff9655eb63b7732184707cfef092d63082f5e661561d05a753fb21d06e5a0\"\n[1] \"a78f257422b7a915e3613f9fc61c099a874b71c4a515b1a5e14d5f9c8426f7ce\"\n[1] \"33d1915f3c2fd3ef06cf4fcb4c0341037a41ecb55d23abc0d8519da588fe13e4\"\n[1] \"098ae6adfee83c74b419015e4c24b6a3d0d67604852af563d7dca79b6f78f63f\"\n[1] \"e728212b1f5ab89604be312d5c482d4ba40db1f72a9ddb5f1f4c09b5e56b36c0\"\n[1] \"9a0e2179e639cc0cd57944ce35e3a2e4cec1bbbfc547059bd9da758b4f828c4f\"\n[1] \"8b6178e6ce14b58635357d434f7fb21d3183b6e5d396f76a923e6269d481b870\"\n[1] \"bb842bac82a00602cedd230e460056aa5a53ab094bbff5a681d217985b5f0309\"\n[1] \"929731c7b52798f066238f85423e7dc8a105ad3037f5f92da26bd065553b443f\"\n[1] \"98cb093b7305be1ee75f80bebf03d1661e4ffcd303b6b4438d0a37dd07200644\"\n[1] \"2403175b1811790a93347df0313902446e455273aac7dd6b92ba0d229483adf6\"\n[1] \"aa84ac653b8fb19914bb687f08b190f458ad7620253687d2bf5222bb1eb0b899\"\n[1] \"239a832c6b7bdd66c51a4b85a734da94c7d1adf34320834f45a2e5116244fbe4\"\n[1] \"005269bb674beb32c104bb415f9cd7501aace44bb3de16758b840ed08e12900a\"\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$hash\n[1] \"005269bb674beb32c104bb415f9cd7501aace44bb3de16758b840ed08e12900a\"\n\n$nonce\n[1] 165\n```\n\n\n:::\n:::\n\n\n\nIt takes 165 iterations to solve the problem of difficulty 2. How difficult is difficulty 3? This time <tt>`print = FALSE`</tt> to save space.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Evaluate a difficulty of 3 (three leading zeros)\nproof_of_work(block, 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$hash\n[1] \"0003b3433712535240d61d5c5c29c2975ec8a170e941323d489bcc5fedad55f6\"\n\n$nonce\n[1] 2937\n```\n\n\n:::\n:::\n\n\n\nIt takes 2937 iterations to solve the problem of difficulty 3. Note that the block remains the same except for the nonce value which increase by one every iteration.\n\nSee a 19 leading zeros example:\nhttps://blockstream.info/block/0000000000000000000ae7a6057c9c3d00ff21c1f8f87ca4413d89059cd9f2c6\n\nCollect the nonce for the first four levels of difficulty.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = 4 # Do not try difficulty 5!\niterations = vector(\"integer\", n)\nfor (i in 1:n) {\n  iterations[i] = proof_of_work(block, i)$nonce\n}\n\niterations\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]     6   165  2937 14644\n```\n\n\n:::\n:::\n\n\n\nSee how difficult the problem gets as we look for more leading zeros in the hash.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(1:n, iterations, type = \"b\", xlab = \"difficulty\",  ylab = \"iterations\")\n```\n\n::: {.cell-output-display}\n![](08-blockchain_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(1:n, log(iterations), type = \"b\", xlab = \"difficulty\",\n     ylab = \"log(iterations)\")\n```\n\n::: {.cell-output-display}\n![](08-blockchain_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n\nNow let’s build a blockchain using the PoW method:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mine algorithm.\nmine <- function(previous_block, difficulty, genesis = FALSE){\n  op <- options(digits.secs = 6) # To get millisecond timestamps.\n  if (genesis) {\n    # Define genesis block.\n    new_block <-  list(number = 1,\n                       timestamp = Sys.time(),\n                       data = \"I'm genesis block\",\n                       parent_hash = \"0\")\n  } else {\n    # Create new block.\n    new_block <- list(number = previous_block$number + 1,\n                      timestamp = Sys.time(),\n                      data = paste0(\"I'm block \", previous_block$number + 1),\n                      parent_hash = previous_block$hash)\n  }\n  # Add nonce with PoW.\n  new_block$nonce <- proof_of_work(new_block, difficulty)$nonce\n  # Add hash.\n  new_block$hash <- digest(new_block, \"sha256\")\n  return(new_block)\n}\n\n# Create a blockchain using the PoW method:\nblockchained = function(difficulty, nblocks) {\n  # Mine genesis block.\n  block_genesis = mine(NULL, difficulty, TRUE)\n  # First block is the genesis block.\n  blockchain <- list(block_genesis)\n\n  if (nblocks >= 2) {\n    # Add new blocks to the chain.\n    for (i in 2:nblocks){\n      blockchain[[i]] <- mine(blockchain[[i-1]], difficulty)\n    }\n    }\n  return(blockchain)\n  }\n```\n:::\n\n\n\n\nCreate 4 blocks with difficulty 3.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 4 blocks, difficulty 3\nblockchained(difficulty = 3, nblocks = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[[1]]\n[[1]]$number\n[1] 1\n\n[[1]]$timestamp\n[1] \"2026-06-01 03:38:03.268497 CST\"\n\n[[1]]$data\n[1] \"I'm genesis block\"\n\n[[1]]$parent_hash\n[1] \"0\"\n\n[[1]]$nonce\n[1] 5288\n\n[[1]]$hash\n[1] \"0000ea744b5b3b9fdcaa062f2644ebc38fd57f4bf5d7c2e9cfe34b1820c0d112\"\n\n\n[[2]]\n[[2]]$number\n[1] 2\n\n[[2]]$timestamp\n[1] \"2026-06-01 03:38:03.463972 CST\"\n\n[[2]]$data\n[1] \"I'm block 2\"\n\n[[2]]$parent_hash\n[1] \"0000ea744b5b3b9fdcaa062f2644ebc38fd57f4bf5d7c2e9cfe34b1820c0d112\"\n\n[[2]]$nonce\n[1] 2737\n\n[[2]]$hash\n[1] \"000deff777bb04879cfd20e47ee513b9a10a5ca41c818d19277ce1d055b8f7f1\"\n\n\n[[3]]\n[[3]]$number\n[1] 3\n\n[[3]]$timestamp\n[1] \"2026-06-01 03:38:03.558372 CST\"\n\n[[3]]$data\n[1] \"I'm block 3\"\n\n[[3]]$parent_hash\n[1] \"000deff777bb04879cfd20e47ee513b9a10a5ca41c818d19277ce1d055b8f7f1\"\n\n[[3]]$nonce\n[1] 1789\n\n[[3]]$hash\n[1] \"000a8eca367577acf124b60a1ac22bc715fb7af6a9fb4a60e4fbfddb74487c2b\"\n\n\n[[4]]\n[[4]]$number\n[1] 4\n\n[[4]]$timestamp\n[1] \"2026-06-01 03:38:03.61485 CST\"\n\n[[4]]$data\n[1] \"I'm block 4\"\n\n[[4]]$parent_hash\n[1] \"000a8eca367577acf124b60a1ac22bc715fb7af6a9fb4a60e4fbfddb74487c2b\"\n\n[[4]]$nonce\n[1] 1004\n\n[[4]]$hash\n[1] \"000555f2e918f721c211eeb52d000c874e7106cd46bbd08e7d704ba937147b0f\"\n```\n\n\n:::\n:::\n\n\n\nNice.\n\n## Transactions.\n\nTypically, the data field of a block contains a certain number of transactions. Each transaction has a sender, a receiver and a value of crypto currency that is transferred from sender to receiver. Moreover, it contains a fee of the transaction. Transactions are stored in a pool of pending transactions and each mined block will include a (proper) subset of pending transactions. The miner of the block gets the fees of all blocked transactions plus a fixed mining reward (and this transaction is included in the following block). This is how new coins are introduced in the blockchain economy.\n\nLet’s create a pool of fictitious pending transactions. We store them in a data frame structure using the <tt>`tibble`</tt> package.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tibble)\nntrx <- 10 # Number of transactions.\nsender <- sample(LETTERS, ntrx) # Sender names.\nreceiver <- sample(LETTERS, ntrx) # Receiver names.\nvalue <- round(runif(n = ntrx, min = 0, max = 100), 0) # Transaction value.\nfee <- round(runif(n = ntrx, min = 0, max = 1), 2) # Transaction fee.\n(transactions = tibble(sender, receiver, value, fee)) # Pending transactions.\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 4\n   sender receiver value   fee\n   <chr>  <chr>    <dbl> <dbl>\n 1 I      V           98  0.61\n 2 Z      N           99  0.07\n 3 C      A            5  0.68\n 4 M      Q           89  0.15\n 5 V      K           48  0.48\n 6 Y      G           20  0.46\n 7 X      W           95  0.34\n 8 G      H           13  0.19\n 9 O      P           94  0.42\n10 K      E            6  0.19\n```\n\n\n:::\n:::\n\n\n\nLet’s update the mining function. Each block will include the most profitable transactions (the ones with the highest fees) among the pending ones. The miner of the block gets as reward the sum of the fees of transactions in the block. The reward transaction is inserted in the next block. We take advantage of <tt>`dplyr`</tt> package.\n\nUpdate of the mining function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\n\nmine <- function(previous_block, transactions, difficulty = 3,\n                 block_size = 3, miner = \"Z\", genesis = FALSE){\n  # Filter transactions to add.\n  trans_pending = arrange(transactions, -fee) # from higher to lower fee.\n  if (nrow(trans_pending) < block_size) {\n    trans_to_add = trans_pending\n    trans_pending = tibble()\n  } else {\n    trans_to_add =  filter(trans_pending, row_number() <= block_size)\n    trans_pending = filter(trans_pending, row_number() > block_size)\n  }\n\n  if (genesis) {\n    # Define genesis block.\n    new_block <-  list(number = 1,\n                       timestamp = Sys.time(),\n                       data = trans_to_add,\n                       parent_hash = \"0\")\n  } else {\n    # Create new block.\n    new_block <- list(number = previous_block$number + 1,\n                      timestamp = Sys.time(),\n                      data = trans_to_add,\n                      parent_hash = previous_block$hash)\n  }\n\n  # Add nonce with PoW.\n  new_block$nonce <- proof_of_work(new_block, difficulty)$nonce\n  # Add hash.\n  new_block$hash <- digest(new_block, \"sha256\")\n  # Add reward transaction.\n  trans_pending = rbind(trans_pending,\n                        data.frame(sender = NA, receiver = miner,\n                                   value = sum(new_block$data$fee),\n                                   fee = 0.01))\n  return(list(block = new_block, transactions = trans_pending))\n}\n```\n:::\n\n\n\n\nBlockchain with transactions.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nblockchained = function(transactions, difficulty, block_size, nblocks) {\n  # Define genesis block.\n  mined = mine(NULL, transactions, difficulty, block_size, miner = \"Z\",\n               genesis = TRUE)\n  block_genesis <- mined$block\n  pending = mined$transactions\n  # First block is the genesis block.\n  blockchain <- list(block_genesis)\n\n  if (nblocks >= 2) {\n    # Add blocks to the chain.\n    for (i in 2:nblocks){\n      mined <- mine(blockchain[[i-1]], pending, difficulty, block_size,\n                    miner = \"Z\")\n      blockchain[[i]] <- mined$block\n      pending = mined$transactions\n    }\n  }\n\n  return(blockchain)\n}\n```\n:::\n\n\n\n\nBuild a new blockchain with transactions.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrans <- blockchained(transactions, difficulty = 3, block_size = 5,\n                      nblocks = 3)\ntrans[[1]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$number\n[1] 1\n\n$timestamp\n[1] \"2026-06-01 03:38:04.332269 CST\"\n\n$data\n# A tibble: 5 × 4\n  sender receiver value   fee\n  <chr>  <chr>    <dbl> <dbl>\n1 C      A            5  0.68\n2 I      V           98  0.61\n3 V      K           48  0.48\n4 Y      G           20  0.46\n5 O      P           94  0.42\n\n$parent_hash\n[1] \"0\"\n\n$nonce\n[1] 24\n\n$hash\n[1] \"000d47182445a1679f10e486f9150355433907158d024a9c7bb7d587710a203c\"\n```\n\n\n:::\n:::\n\n\n\n\nIn the first block above, we have the first half of the transactions sorted by fee.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrans[[2]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$number\n[1] 2\n\n$timestamp\n[1] \"2026-06-01 03:38:04.341432 CST\"\n\n$data\n# A tibble: 5 × 4\n  sender receiver value   fee\n  <chr>  <chr>    <dbl> <dbl>\n1 X      W           95  0.34\n2 G      H           13  0.19\n3 K      E            6  0.19\n4 M      Q           89  0.15\n5 Z      N           99  0.07\n\n$parent_hash\n[1] \"000d47182445a1679f10e486f9150355433907158d024a9c7bb7d587710a203c\"\n\n$nonce\n[1] 2137\n\n$hash\n[1] \"0008cc12c789f5c2cefecd6a81fe76271a4baff887dd564d11fb344e7889471b\"\n```\n\n\n:::\n:::\n\n\n\n\nIn the second block above, we have the second half of the transactions sorted by fee.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrans[[3]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$number\n[1] 3\n\n$timestamp\n[1] \"2026-06-01 03:38:04.428427 CST\"\n\n$data\n# A tibble: 2 × 4\n  sender receiver value   fee\n  <chr>  <chr>    <dbl> <dbl>\n1 <NA>   Z         2.65  0.01\n2 <NA>   Z         0.94  0.01\n\n$parent_hash\n[1] \"0008cc12c789f5c2cefecd6a81fe76271a4baff887dd564d11fb344e7889471b\"\n\n$nonce\n[1] 3202\n\n$hash\n[1] \"0004bde6c0332eafd078ccd770be8138d5ffe20a1420cbae4f64d154ce384b33\"\n```\n\n\n:::\n:::\n\n\n\n\nIn the third block above, the miner of the block Z solves the leading zeros problem and gets the fees of all blocked transactions plus a fixed mining reward (and this transaction is included in the following block).\n\n\n## Digital signature.\n\nHow can we be sure that transactions are authentic? Blockchain uses asymmetric cryptography to implement digital signatures of transactions. Each transaction is signed by the sender with her private key and anyone can verify the authenticity of the signature (and of the transaction) using the sender’s public key.\n\nPublic-key cryptography, or asymmetric cryptography, is any cryptographic system that uses pairs of keys: public keys which may be disseminated widely, and private keys which are known only to the owner. This accomplishes two functions: authentication, where the public key verifies that a holder of the paired private key sent the message, and encryption, where only the paired private key holder can decrypt the message encrypted with the public key. The strength of a public key cryptography system relies on the computational effort required to find the private key from its paired public key.\n\nIn a public key encryption system, any person can encrypt a message using the receiver’s public key. That encrypted message can only be decrypted with the receiver’s private key. In a public key signature system, a person can combine a message with a private key to create a short digital signature on the message. Anyone with the corresponding public key can combine the signed message and the known public key to verify whether the signature on the message was valid, i.e. made by the owner of the corresponding private key. Changing the message, even replacing a single letter, will cause verification to fail.\n\nDigital signatures are usually applied to a hash of the message. The hash keeps the signed object short while preserving integrity: any change to the original message changes the hash and invalidates the signature. Confidentiality is a separate layer. A sender can encrypt the message, often through hybrid or envelope encryption, using the receiver's public key or a symmetric key protected by that public key. The receiver verifies the signature with the sender's public key and decrypts with the appropriate private key.\n\nRSA (Rivest–Shamir–Adleman) is one of the first public-key cryptosystems and is widely used for secure data transmission. In RSA, the asymmetry is based on the practical difficulty of the factorization of the product of two large prime numbers.\n\nNext is an example of encryption and digital signature using package <tt>`openssl`</tt>. First, the encryption example.\n\nGenerate a RSA (Rivest–Shamir–Adleman) private and a public key (pubkey).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(openssl)\n# Encryption.\nkey <- rsa_keygen(512)\npubkey <- key$pubkey\nkey\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[512-bit rsa private key]\nmd5: 1499c6f1ca899f0e34b917348f295bda\nsha256: 82a2ac3240d311c79227df8093f3d1c32353c18024b91f912100ca1cabc40efd\n```\n\n\n:::\n\n```{.r .cell-code}\npubkey\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[512-bit rsa public key]\nmd5: 1499c6f1ca899f0e34b917348f295bda\nsha256: 82a2ac3240d311c79227df8093f3d1c32353c18024b91f912100ca1cabc40efd\n```\n\n\n:::\n:::\n\n\n\nLooks the same, but the the private key has some more information inside the key object.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(pubkey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 5\n $ type       : chr \"rsa\"\n $ size       : int 512\n $ ssh        : chr \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAQQC7esI7UFANG4 ...\"\n $ fingerprint: 'hash' raw [1:32] 82 a2 ac 32 ...\n $ data       :List of 2\n  ..$ e: 'bignum' raw [1:3] 01 00 01\n  ..$ n: 'bignum' raw [1:65] 00 bb 7a c2 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nstr(key)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nList of 4\n $ type  : chr \"rsa\"\n $ size  : int 512\n $ pubkey:List of 5\n  ..$ type       : chr \"rsa\"\n  ..$ size       : int 512\n  ..$ ssh        : chr \"ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAQQC7esI7UFANG4 ...\"\n  ..$ fingerprint: 'hash' raw [1:32] 82 a2 ac 32 ...\n  ..$ data       :List of 2\n  .. ..$ e: 'bignum' raw [1:3] 01 00 01\n  .. ..$ n: 'bignum' raw [1:65] 00 bb 7a c2 ...\n $ data  :List of 8\n  ..$ e : 'bignum' raw [1:3] 01 00 01\n  ..$ n : 'bignum' raw [1:65] 00 bb 7a c2 ...\n  ..$ p : 'bignum' raw [1:33] 00 eb 72 b1 ...\n  ..$ q : 'bignum' raw [1:33] 00 cb d8 2a ...\n  ..$ d : 'bignum' raw [1:64] 1d 99 6d 0f ...\n  ..$ dp: 'bignum' raw [1:32] 3c d5 5c 7a ...\n  ..$ dq: 'bignum' raw [1:33] 00 cb 3a 81 ...\n  ..$ qi: 'bignum' raw [1:33] 00 a2 e4 b4 ...\n```\n\n\n:::\n:::\n\n\n\n\nThe <tt>`charToRaw()`</tt> function converts a length-one character string to raw bytes.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Message.\nmsg <- charToRaw(\"Blockchain is terrific!\")\nmsg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 42 6c 6f 63 6b 63 68 61 69 6e 20 69 73 20 74 65 72 72 69 66 69 63 21\n```\n\n\n:::\n:::\n\n\n\n\nThe message *Blockchain is terrific!* is now transformed into data to encrypt. Each pair of characters (62, 6c and so on) represents one word, blank space or exclamation mark.\n\nCipher (transform a message to conceal its meaning) the message with public key.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nciphermsg <- rsa_encrypt(msg, pubkey)\nciphermsg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 00 a6 c9 fd 87 6c 15 75 60 02 50 58 02 00 28 ac 97 ed 71 b9 a9 a8 79 ef b9\n[26] d1 bd 70 e5 bf 10 b4 df f4 dc 42 78 5c 72 42 b9 87 b1 2d e5 fc 99 88 78 e9\n[51] 2f 91 c0 d1 44 b1 c2 b2 39 2e 0f 57 77 3c\n```\n\n\n:::\n:::\n\n\n\nThis is how it looks the encrypted message *Blockchain is terrific!*\n\nDecrypt the message with private key.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrawToChar(rsa_decrypt(ciphermsg, key))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Blockchain is terrific!\"\n```\n\n\n:::\n:::\n\n\n\nAnd this is how we can decrypt the message with the private key. Now, the signature example where the message is a transaction.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Signature.\n# Generate a private key (key) and a public key (pubkey)\nkey <- rsa_keygen()\npubkey <- key$pubkey\n# build a transaction\ntrans = list(sender = \"A\", receiver = \"B\", amount = \"100\")\ntrans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$sender\n[1] \"A\"\n\n$receiver\n[1] \"B\"\n\n$amount\n[1] \"100\"\n```\n\n\n:::\n:::\n\n\n\nThis is the original transaction.\n\nSerialize the transaction data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- serialize(trans, NULL)\ndata\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1] 58 0a 00 00 00 03 00 04 05 02 00 03 05 00 00 00 00 05 55 54 46 2d 38 00 00\n [26] 02 13 00 00 00 03 00 00 00 10 00 00 00 01 00 04 00 09 00 00 00 01 41 00 00\n [51] 00 10 00 00 00 01 00 04 00 09 00 00 00 01 42 00 00 00 10 00 00 00 01 00 04\n [76] 00 09 00 00 00 03 31 30 30 00 00 04 02 00 00 00 01 00 04 00 09 00 00 00 05\n[101] 6e 61 6d 65 73 00 00 00 10 00 00 00 03 00 04 00 09 00 00 00 06 73 65 6e 64\n[126] 65 72 00 04 00 09 00 00 00 08 72 65 63 65 69 76 65 72 00 04 00 09 00 00 00\n[151] 06 61 6d 6f 75 6e 74 00 00 00 fe\n```\n\n\n:::\n:::\n\n\n\nIn computing, serialization is the process of translating a data structure or object state into a format that can be stored or transmitted and reconstructed later. Here, the transaction is translated into a format that can be reconstructed later. At the moment, this object called <tt>`data`</tt> has not been signed yet by the sender. The next code chunk sign the <tt>`data`</tt> object by the sender.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sign (a hash of) the transaction with private key.\nsig <- signature_create(data, sha256, key = key)\nsig\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1] 75 20 a2 b3 95 28 69 73 26 b8 f9 1c ec 15 cd 63 68 e9 cd 5f 8c 32 52 1f d3\n [26] 83 c5 7a fd 70 0e 20 f9 8d fe ce 5f 1d 73 50 eb 95 2c ea fe 53 88 b4 59 0a\n [51] 2f ff 15 d5 ed 4d 47 67 34 29 a0 b4 9c 0a b5 25 6a 62 4a ce 59 e5 a7 32 38\n [76] 31 46 3a 2c 0c 77 2d c0 a0 c3 a2 4f 11 73 92 d6 a5 ba ee 42 d9 30 ec 8f 15\n[101] 0f f5 81 26 93 ce 47 09 25 16 a3 a4 66 af c1 1e d5 db 91 02 67 29 25 f4 31\n[126] 63 76 1f 30 5e 62 1b 45 13 b4 5f bc a5 2b 73 c8 6f 93 a7 37 bd b6 57 69 07\n[151] b0 06 e3 a5 e5 f9 b0 b4 92 e7 b5 df 52 8e 92 5f 25 46 5f 30 39 54 d0 c1 7c\n[176] 9c 9f 52 cc 55 19 ee c9 54 09 c0 9c 10 b5 bb 9f ae 05 48 7f b8 98 45 f8 a8\n[201] a9 c0 11 50 3f a1 28 c7 1c ef 9d 44 05 bf 8d c5 4f 64 45 3c 5c b5 bf fa af\n[226] 56 83 d3 1e 5f 6f 53 12 72 9d cf bb ca 51 cf 48 aa 46 97 76 a3 8f f8 91 11\n[251] e8 34 b4 56 2d de\n```\n\n\n:::\n:::\n\n\n\nThe new object <tt>`sig`</tt> is the digital signature of the serialized transaction. With the function <tt>`signature_verify()`</tt>, anyone can verify that the serialized transaction was signed with the private key associated with <tt>`pubkey`</tt>.\n\nVerify the message with public key.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsignature_verify(data, sig, sha256, pubkey = pubkey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\n\n\nVerification confirms that the holder of the private key associated with <tt>`pubkey`</tt> signed this serialized transaction. Now, we encrypt the translated transaction.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cipher the transaction with public key\nciphermsg <- rsa_encrypt(data, pubkey)\nciphermsg\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1] ad bf 17 db 75 c2 f9 2a 44 7c 12 3c 62 fa 16 bf 0f 6a e2 28 e8 52 3f fb 83\n [26] d5 b9 fd 28 80 46 f2 a4 18 8c 80 05 69 fe be c1 bb c0 28 82 05 5f bf 2b 23\n [51] 1e d8 00 13 af ea 60 95 e3 2e 4c f9 c7 26 e3 fd 82 5d 17 b0 55 65 40 f7 44\n [76] cb 11 2a 56 06 b1 d1 90 56 73 27 04 e4 c4 9b 36 56 db 56 0f 09 3c b0 55 a4\n[101] ec eb 81 33 47 e8 4e 69 b3 30 e3 98 45 10 ae 08 a5 4d 8a e8 ee 05 31 a7 7b\n[126] 88 52 b6 1f e7 c7 03 45 ed f1 9a 7d dc 9f 11 dc ea 29 1a b3 ee 49 55 fb 6d\n[151] 2e ba fb 6a 96 fb e6 80 ca 9a 8e c8 f4 35 90 18 6b b0 b2 a8 8d 4a 6a b3 5c\n[176] 62 36 11 66 13 e5 4b cd ae c3 c7 e4 b9 bf 6f 4d 6e 19 b7 d7 47 92 fb ac 48\n[201] 32 00 f5 a1 c3 ea 57 79 65 b4 15 16 e6 7d 8d 67 e3 86 da fd a8 07 fd 83 76\n[226] b6 f5 64 c1 4a 2b 37 a6 e0 e7 c4 7c 59 43 77 91 b2 da ef c0 41 e2 6f fe 4d\n[251] 66 0f 78 0e 50 9c\n```\n\n\n:::\n:::\n\n\n\nThe transaction data is serialized and encrypted in this toy example with <tt>`pubkey`</tt>. In a real confidential transfer, encryption would use the receiver's public key or a symmetric key protected for the receiver. The signature remains a separate object used for authenticity and integrity. To recover the original transaction we would need to decrypt the serialized message with the private key <tt>`key`</tt>, and then unserialize the result.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Decrypt and unserialize the transation with private key.\nunserialize(rsa_decrypt(ciphermsg, key))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$sender\n[1] \"A\"\n\n$receiver\n[1] \"B\"\n\n$amount\n[1] \"100\"\n```\n\n\n:::\n:::\n\n\n\nThe transaction details are back.\n\n## Network.\n\nFinally, the blockchain ledger is distributed over a peer-to-peer network. The steps to run the network are as follows:\n\n* new transactions are broadcast to all nodes;\n* each node collects new transactions into a block;\n* each node works on finding a difficult proof-of-work for its block;\n* when a node finds a proof-of-work, it broadcasts the block to all nodes;\n* nodes accept the block only if all transactions in it are valid and not already spent;\n* nodes express their acceptance of the block by working on creating the next block in the chain, using the hash of the accepted block as the previous hash.\n\nNodes always consider the longest chain to be the correct one and will keep working on extending it. The incentive of rewards may help encourage nodes to stay honest. If a greedy attacker is able to assemble more CPU power than all the honest nodes, he would have to choose between using it to defraud people by stealing back his payments, or using it to generate new coins. He ought to find it more profitable to play by the rules (generate new coins), such rules that favour him with more new coins than everyone else combined, than to undermine the system and the validity of his own wealth.\n\n## Privacy.\n\nThe traditional banking model achieves a level of privacy by limiting access to information to the parties involved and the trusted third party. The necessity to announce all transactions publicly precludes this method, but privacy can still be maintained by breaking the flow of information in another place: by keeping public keys anonymous. The public can see that someone is sending an amount to someone else, but without information linking the transaction to anyone. This is similar to the level of information released by stock exchanges, where the time and size of individual trades, the tape, is made public, but without telling who the parties were.\n",
    "supporting": [
      "08-blockchain_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}