# Conclusion.

Finance is not about how to make money; it is about much more than that.
Finance is about how to find and use resources, and how to assign them into
projects. This is not an easy task as resources are limited and projects are
risky. Moreover, sometimes the financial markets do not work well: bad projects
are financed and good projects are not. However, if we rely on finance theory,
quantitative models, and data analysis, we increase the chances to make good and
informed decisions. Making money is a necessary step that allows us to pursue
superior objectives like making firms growth, create better jobs, stimulate
innovation, economic growth, and hopefully improve the standard of living of the
population.

We have made some progress at implementing financial and economic models to
achieve these superior objectives but we cannot say we have succeeded. Poverty
levels in some countries are high, and income inequality leads not only to
economic but also social problems. Fortunately, there is an increasing and
genuine interest in learning finance principles by good people around the world.
