---
title: Financial modeling with R.
subtitle: Dr. Martín Lozano.
author:
- name: Back to main [`r fontawesome::fa("home")`](https://mlozanoqf.github.io/)
#  affiliation: Academic website. [Web.](https://sites.google.com/site/mlozanoqf/)
date: "\\faClock \\hspace{1 mm} Current commit: `r format(Sys.time(), '%d/%m/%Y, %H:%M:%S.')`"
#  bookdown::gitbook: default
output: 
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    toc_depth: 2
    number_sections: yes
    fig_caption: yes
    code_folding: hide
    theme: readable #darkly 
    includes:
      after_body: analytics_pmf.html
abstract: This material relies on @hull2020machine, @hyndman2021forecasting, and on Matt Dancho's Business Science IO freely available codes in R that explains how to implement machine learning workflow using H2O. Some mathematical background is skipped to emphasize the data analysis, model logic, discussion, graphical approach and R coding [@Rref]. As in the philosophy of Donald Knuth [@knuth1984literate], the objective of this document is to explain to human beings what we want a computer to do as literate programming. This is a work in progress and it is under revision.
bibliography: mybibfile.bib
---
-----------------------

```{=tex}
\newpage 
\hypersetup{linkcolor=black}
\renewcommand*\contentsname{Index.}
\tableofcontents
```

```{r include=FALSE}
# This removes all items in environment. 
# It is a good practice to start your code this way.
rm(list=ls())
library(tictoc)
tic("full")
```

```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(fig.pos = "H", out.extra = "")
```

```{r, xaringanExtra-clipboard, echo=FALSE}
htmltools::tagList(
  xaringanExtra::use_clipboard(
    button_text = "<i class=\"fa fa-clone fa-2x\" style=\"color: #301e64\"></i>",
    success_text = "<i class=\"fa fa-check fa-2x\" style=\"color: #90BE6D\"></i>",
    error_text = "<i class=\"fa fa-times fa-2x\" style=\"color: #F94144\"></i>"
  ),
  rmarkdown::html_dependency_font_awesome()
)
```

\newpage

```{r Introduction, child = 'intro.Rmd'}
```


```{r include=FALSE}
t_full <- toc()
```

This document took `r round(as.numeric((t_full$toc-t_full$tic)/60), 2)` minutes to compile in Rmarkdown, R version 4.2.1.

# References.
