---
title: ''
output: pdf_document
---

# Preface.

We all have different interests and incentives to learn finance. For me, it is a way to better understand the world we are living in. We are surrounded by finance products and services in our daily life. In fact, we are constantly and probably unconsciously assigning resources to achieve objectives, just as we consciously do in finance: *make financing decisions to invest in productive projects*. As individuals, we face decisions such as rent or buy, take vacations or a summer course, manage our personal budget, asking for a car loan, evaluating a mortgage, saving for our retirement, calculating and paying taxes, etc. Firm managers are interested to gather funds with the lowest possible costs, invest those funds in the most productive assets and employers, sell their products at a competitive price so at the end of the day their revenues exceed their cost to make money. Governments receive funds mainly from taxpayers and they are expected to invest taxpayers money to provide high quality and reliable public services to improve the living standard of people.

According to [@oecd2020oecd], developed and emerging countries and economies have become increasingly concerned about the level of financial literacy (ability to understand and properly apply financial management skills) of their citizens, including young people. This initially stemmed from concern about the potential impact of shrinking public and private welfare systems, shifting demographics, including the ageing of the population in many countries, and the increased sophistication and expansion of financial services. We all face financial decisions and we demand and offer financial services in this evolving context. As a result, financial literacy is now globally recognized as an essential life skill.

Let me introduce myself by listing my postgraduate studies and describing my professional background.

My postgraduate studies: I have a Post Doc in Finance from The University of Manchester; a PhD in Quantitative Finance from the University of the Basque Country; a Doctor *Europaeus* mention from several European universities: Manchester Business School; University of Edinburgh; Humboldt University; Aarhus University; University of Vienna; Dublin City University; Queen Mary, University of London; and University of St. Gallen. I have seven postgraduate studies in Statistical Learning, Data Mining, Scientific Analysis of Data, Statistical Methods, Applied Statistics, Finance, and Quantitative Finance. I have a BS in Economics, and other professional certificates mostly in the area of data science.

My professional background: I am a researcher in the area of quantitative finance for the last 10 years. My research has been published in 3 stars journals (high-ranked) according to The Chartered Association of Business Schools[^1], presented in numerous research seminars, and in prestigious international conferences. I have been a lecturer in economics, finance and data science for under and postgraduate levels at different universities in Mexico and the UK for the last 20 years. Also, I have supervised more than 70 dissertations at under and postgraduate academic programs of schools including the London School of Business & Finance; University of London, School of Oriental and African Studies (SOAS); The University of Manchester; Universidad Complutense de Madrid, UDEM, among others.

[^1]: The Chartered Association of Business Schools is considered the voice of the UK's business and management education sector. According to CABS, all 3 stars rated journals publish original and well executed research papers and are highly regarded. These journals typically have good submission rates and are very selective in what they publish. Papers are heavily refereed in 3 stars rated journals.

In case you are interested, my full academic CV is available at sites.google.com/site/mlozanoqf/
