{
  "hash": "6f119a7c323b4fdf513ed4efb518f22a",
  "result": {
    "engine": "knitr",
    "markdown": "# Prices and returns\n\n\n\n\n\n\n\n\n\nAn asset is any resource owned by a business or an economic entity that can produce value in the future. In this book, stocks are the main working example, but the same return logic can be applied to commodities, currencies, bonds, derivatives, and portfolio values.\n\nThis chapter is the bridge between raw financial data and the modeling chapters that follow. The previous chapter showed how to obtain and visualize prices. This chapter converts those prices into returns, cumulative values, distributional summaries, and risk-return indicators. These objects become the inputs for trading rules, beta regressions, portfolio allocation, and Value at Risk.\n\nA return is the percentage change of an asset price. Returns allow assets with different price levels to be compared on the same scale. For example, buying at \\$100 and selling at \\$110 produces a \\$10 gain and a 10% return. Buying at \\$10 and selling at \\$12 produces a \\$2 gain and a 20% return. The dollar gain is larger in the first case; the relative performance is larger in the second case.\n\nThe previous returns were calculated as simple percentage changes, $\\frac{\\$110-\\$100}{\\$100}$ and $\\frac{\\$12-\\$10}{\\$10}$ respectively. Log-returns are another common transformation.\n\n$$\nr_t=\\log\\left(\\frac{P_t}{P_{t-1}}\\right).\n$$\n\nLog-returns are close to simple returns for small price changes, and they are especially useful because multi-period log-returns add over time. For larger price changes, simple and log returns differ.\n\nIn this case the log-returns are $\\log\\left(\\frac{\\$110}{\\$100}\\right)$ and $\\log\\left(\\frac{\\$12}{\\$10}\\right)$ which are 9.53% and 18.23% respectively.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlog(110/100)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.09531018\n```\n\n\n:::\n\n```{.r .cell-code}\nlog(12/10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1823216\n```\n\n\n:::\n:::\n\n\n\n\n\nBoth absolute and relative valuations (\\$10 versus \\$2, and 10% versus 20%) are valid depending on the reporting question. The relative approach is especially useful because percentages place different assets on a common scale. Returns also have statistical properties that make them more convenient than prices in many quantitative finance and econometrics models.\n\nReturns can also be expressed relative to risk. If two assets have the same expected return of 5%, but the first has risk of 5% and the second has risk of 10%, the first asset has 1 unit of return per unit of risk and the second has 0.5. This is the logic behind many risk-return comparisons in the rest of the book.\n\nThere are several ways to measure and report asset returns: daily, monthly, yearly, simple, log, cumulative, and compounded. The chapter introduces the versions needed for the later modeling workflow.\n\n## From prices to returns\n\nTime series of asset prices are the input needed to calculate time series of asset returns. The first plot shows daily adjusted prices in the <tt>`FANG`</tt> database.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFANG_daily_all <- FANG |>\n  group_by(symbol) |>\n  ggplot(aes(x = date, y = adjusted, color = symbol)) +\n  geom_line(size = 1) +\n  labs(x = \"\", y = \"Adjusted prices\", color = \"\") +\n  scale_y_continuous(labels = scales::dollar) +\n  theme_tq() +\n  scale_color_tq()\n\nFANG_daily_all\n```\n\n::: {.cell-output-display}\n![Daily stock prices on their original scales.](03-prices-and-returns_files/figure-html/fig-dspnsetr-1.png){#fig-dspnsetr width=672}\n:::\n:::\n\n\n\n\nThe stocks fluctuate in different price ranges. A higher price level does not imply a better investment opportunity: Amazon or Google can trade at larger dollar prices than Meta or Netflix while still offering a weaker return-risk profile. The shared vertical axis also compresses some series, making the individual price paths difficult to inspect. For performance evaluation, the next step is to transform prices into returns and compare risk together with return.\n\nA faceted view makes the individual price paths easier to inspect.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFANG_daily <- FANG_daily_all +\n  facet_wrap(~ symbol, ncol = 2, scales = \"free_y\") +\n  theme(legend.position = \"none\", legend.title = element_blank())\n\nFANG_daily\n```\n\n::: {.cell-output-display}\n![Daily stock prices by stock.](03-prices-and-returns_files/figure-html/fig-dspetr-1.png){#fig-dspetr width=672}\n:::\n:::\n\n\n\n\nThe faceted plot shows positive price trends over the full period, while also revealing important differences by year. Prices declined around 2014 for Amazon, Google, and Netflix, and then Amazon and Google recovered strongly in 2015. This visualization helps compare each stock's price path, but the analysis is still based on prices. The next step is to transform prices into returns.\n\nAdjusted prices are selected first and then transformed into yearly returns. For an asset with adjusted price $P_t$, the simple return over one period is defined below.\n\n$$\nR_t = \\frac{P_t}{P_{t-1}} - 1.\n$$\n\nThe code below applies the same expression after grouping the data by stock and changing the periodicity to yearly.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create yearly returns.\nFANG_annual_returns <- FANG |>\n    group_by(symbol) |>\n    tq_transmute(select     = adjusted,\n                 mutate_fun = periodReturn,\n                 period     = \"yearly\",\n                 type       = \"arithmetic\")\nFANG_annual_returns\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 3\n# Groups:   symbol [4]\n   symbol date       yearly.returns\n   <chr>  <date>              <dbl>\n 1 META   2013-12-31         0.952 \n 2 META   2014-12-31         0.428 \n 3 META   2015-12-31         0.341 \n 4 META   2016-12-30         0.0993\n 5 AMZN   2013-12-31         0.550 \n 6 AMZN   2014-12-31        -0.222 \n 7 AMZN   2015-12-31         1.18  \n 8 AMZN   2016-12-30         0.109 \n 9 NFLX   2013-12-31         3.00  \n10 NFLX   2014-12-31        -0.0721\n11 NFLX   2015-12-31         1.34  \n12 NFLX   2016-12-30         0.0824\n13 GOOG   2013-12-31         0.550 \n14 GOOG   2014-12-31        -0.0597\n15 GOOG   2015-12-31         0.442 \n16 GOOG   2016-12-30         0.0171\n```\n\n\n:::\n:::\n\n\n\n\nThe output follows the tidy-data convention: each variable forms a column, each observation forms a row, and each type of observational unit forms a table. These yearly returns are expressed in decimal notation. A value such as 0.95 corresponds to 95%.\n\nThe annual-return plot visualizes period-by-period performance by stock.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFANG_annual_returns |>\n  ggplot(aes(x = date-365, y = yearly.returns, fill = symbol)) +\n  geom_col() +\n  geom_hline(yintercept = 0, color = \"black\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(y = \"Annual returns\", x = \"\") +\n  facet_wrap(~ symbol, ncol = 2, scales = \"free_y\") +\n  theme_tq() +\n  scale_fill_tq() +\n  theme(legend.position = \"none\", legend.title = element_blank())\n```\n\n::: {.cell-output-display}\n![FANG: annual returns.](03-prices-and-returns_files/figure-html/fig-far-1.png){#fig-far width=672}\n:::\n:::\n\n\n\n\nThese stocks are risky because their returns change substantially over time. The annual-return plot confirms the message from the price chart: 2014 produced negative returns for Amazon, Google, and Netflix, while 2015 was strong for Amazon and Google.\n\nThe next comparison evaluates a \\$100 investment in each stock from the first day of 2013 to the last day of 2016. Yearly returns show period-by-period performance, while cumulative returns show the full investment path over the sample.\n\n## Cumulative returns\n\nWorking with cumulative percentage changes requires multiplying growth factors. If an initial value is \\$100 and it increases by 5%, the new value is $\\$100 \\times (1+0.05) = \\$105$. If the value later falls by 20%, the current value is $\\$100 \\times (1+0.05) \\times (1-0.2) = \\$84$.\n\nNow consider a \\$100 investment in Amazon over this period. The value of the investment is calculated by compounding the four yearly returns listed above. Amazon's yearly returns from 2013 to 2016 are: 54.98%, -22.18%, 117.78%, 10.95% in that order.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Investment in USD.\ninvestment = 100\n# Amazon's cumulative return in percentage.\nAMZN_cum_percentage = (1 + 0.54984265) * (1 - 0.22177086) *\n  (1 + 1.17783149) * (1 + 0.10945565) - 1\n# Amazon's cumulative return in USD.\nAMZN_cum_usd = investment * (1 + AMZN_cum_percentage)\n# Show results.\nAMZN_cum_percentage\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.914267\n```\n\n\n:::\n\n```{.r .cell-code}\nAMZN_cum_usd\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 291.4267\n```\n\n\n:::\n:::\n\n\n\n\nThe dollar value of \\$100 invested in Amazon at the end of the 4 years is \\$291.4267. The cumulative return is 191.4267%. A direct check applies this return over the \\$100 investment: $\\$100 \\times (1+1.914267) = \\$291.4267$.\n\nThe 191.4267% cumulative return accumulates four years of performance. A separate summary is the mean yearly return. For yearly returns $R_1,\\ldots,R_n$, the arithmetic mean is defined as follows.\n\n$$\n\\bar{R}_{arith}=\\frac{1}{n}\\sum_{t=1}^{n}R_t.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Arithmetic mean return.\nAMZN_arith_mean_retun = (0.54984265 - 0.22177086 +\n                         1.17783149 + 0.10945565) / 4\nAMZN_arith_mean_retun\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4038397\n```\n\n\n:::\n:::\n\n\n\n\nThe arithmetic mean can be misleading when it is used as if it were a compounded growth rate. In this example, the arithmetic mean return is 40.38397% per year. Applying that value as a constant annual growth rate gives the following result.\n\nThe repeated-multiplication calculation gives the same type of compounded value.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninvestment * (1 + AMZN_arith_mean_retun) *\n  (1 + AMZN_arith_mean_retun) *\n  (1 + AMZN_arith_mean_retun) * (1 + AMZN_arith_mean_retun)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 388.3919\n```\n\n\n:::\n:::\n\n\n\n\nThe equivalent power notation gives the same calculation more compactly.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninvestment * (1 + AMZN_arith_mean_retun) ^ 4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 388.3919\n```\n\n\n:::\n:::\n\n\n\n\nThe result is inconsistent with the actual compounded value. The dollar value of \\$100 invested in Amazon at the end of the 4 years is \\$291.4267, while applying the arithmetic mean as a growth rate gives \\$388.3919. The arithmetic mean is useful as a sample summary, but it should be distinguished from the rate that reproduces the multi-period investment value.\n\nThe difference is reconciled with the geometric mean return. For gross returns $(1+R_t)$, the geometric mean return is defined as follows.\n\n$$\n\\bar{R}_{geom}=\\left(\\prod_{t=1}^{n}(1+R_t)\\right)^{1/n}-1.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Geometric mean return.\nAMZN_geom_mean_retun = ((1 + 0.54984265) * (1-0.22177086) *\n                        (1 + 1.17783149) * (1 + 0.10945565)) ^ (1/4) - 1\nAMZN_geom_mean_retun\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3065689\n```\n\n\n:::\n:::\n\n\n\n\nThe geometric mean return of 30.65689% per year reproduces the compounded investment value: \\$100 grows to \\$291.4267 by the end of the fourth year. The calculation can be checked in two equivalent ways.\n\nThe repeated-multiplication calculation gives the compounded value.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninvestment * (1 + AMZN_geom_mean_retun) *\n  (1 + AMZN_geom_mean_retun) *\n  (1 + AMZN_geom_mean_retun) * (1 + AMZN_geom_mean_retun)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 291.4267\n```\n\n\n:::\n:::\n\n\n\n\nThe equivalent power notation gives the same compounded value more compactly.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninvestment * (1 + AMZN_geom_mean_retun) ^ 4\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 291.4267\n```\n\n\n:::\n:::\n\n\n\n\nThis phenomenon is an example of a result that is well known in mathematics. For positive gross returns, the geometric mean is less than or equal to the arithmetic mean (30.6 \\< 40.3). The arithmetic mean return of 40.38397% overstates the constant annual growth rate that reproduces the investment value. Fund-performance reporting therefore needs to distinguish between average period returns and compounded growth rates.\n\nFor now, the examples use arithmetic returns. The next plot shows how a \\$100 investment grows each year for each stock. The plotted values are in USD, and each series starts from the same initial investment.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Yearly returns.\nFANG_annual_returns <- FANG |>\n    group_by(symbol) |>\n    tq_transmute(select     = adjusted,\n                 mutate_fun = periodReturn,\n                 period     = \"yearly\",\n                 type       = \"arithmetic\")\n# Cumulative returns.\nFANG_annual_cum_returns <- FANG_annual_returns |>\n  mutate(cr = 100*cumprod(1 + yearly.returns)) |>\n  bind_rows(\n    FANG_annual_returns |>\n      distinct(symbol) |>\n      mutate(date = as.Date(\"2012-12-31\"),\n             yearly.returns = 0,\n             cr = 100)\n  ) |>\n  arrange(symbol, date) |>\n# Plot the results.\n  ggplot(aes(x = date, y = cr, fill = symbol)) + geom_col() +\n  labs(subtitle = \"100 USD investment growth from 2013-01-01 to 2016-12-31.\",\n  x = \"\", y = \"USD value at the end of the year\", color = \"\") +\n  scale_y_continuous(labels = scales::dollar) +\n  facet_wrap(~ symbol, ncol = 2, scales = \"free_y\") +\n  theme_tq() +\n  scale_color_tq() +\n  theme(legend.position = \"none\", legend.title = element_blank())\n\nFANG_annual_cum_returns\n```\n\n::: {.cell-output-display}\n![Yearly cumulative USD returns, a facet view.](03-prices-and-returns_files/figure-html/fig-ycurafv-1.png){#fig-ycurafv width=672}\n:::\n:::\n\n\n\n\nThe Amazon path in the plot matches the calculation above: \\$100 invested at the start of the period ends at \\$291.4267. The common base value makes terminal differences easier to interpret.\n\nThe same transformation can be applied at monthly frequency.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Monthly returns.\nFANG_monthly_returns <- FANG |>\n    group_by(symbol) |>\n    tq_transmute(select     = adjusted,\n                 mutate_fun = periodReturn,\n                 period     = \"monthly\",\n                 type       = \"arithmetic\")\n# Plot the results.\nggplot(FANG_monthly_returns, aes(x = date-12,\n       y = monthly.returns, fill = symbol)) +\n  geom_col() +\n  geom_hline(yintercept = 0, color = \"black\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(y = \"Monthly returns\", x = \"\") +\n  facet_wrap(~ symbol, ncol = 2, scales = \"free_y\") +\n  theme_tq() +\n  scale_fill_tq() +\n  theme(legend.position = \"none\", legend.title = element_blank())\n```\n\n::: {.cell-output-display}\n![FANG: monthly returns, a facet view.](03-prices-and-returns_files/figure-html/fig-fmrafv-1.png){#fig-fmrafv width=672}\n:::\n:::\n\n\n\n\nMoving from yearly to monthly returns gives 12 observations per year. The monthly plot reveals more short-run volatility: GOOG has a negative month immediately after a positive return above 20%. The frequent movement between positive and negative returns shows why short-horizon prediction is difficult.\n\nMonthly returns allow a finer view of the same \\$100 investment example. If the initial investment is $V_0=100$, the investment value after $t$ monthly returns follows the compounding expression below.\n\n$$\nV_t = 100 \\prod_{j=1}^{t}(1+R_j).\n$$\n\nThe code inserts the initial value $V_0=100$ for every stock and then appends the cumulative monthly values. This makes the comparison start from the same dollar base for all four assets.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate monthly cumulative returns.\nFANG_monthly_cum_returns <- FANG_monthly_returns |>\n  group_by(symbol) |>\n  mutate(cr = 100 * cumprod(1 + monthly.returns))\nFANG_monthly_cum_returns <- bind_rows(\n  FANG_monthly_returns |>\n    distinct(symbol) |>\n    mutate(date = as.Date(\"2012-12-31\"),\n           monthly.returns = 0,\n           cr = 100),\n  FANG_monthly_cum_returns\n) |>\n  arrange(symbol, date)\n# Plot results.\nFANG_monthly_all <- FANG_monthly_cum_returns |>\nggplot(aes(x = date, y = cr, color = symbol)) +\n  geom_line(size = 1) +\n  geom_point(data = FANG_monthly_cum_returns |>\n               filter(date == as.Date(\"2012-12-31\")),\n             size = 4, col = \"black\", alpha = 0.5) +\n  labs(subtitle = \"100 USD investment growth from 2013-01-01 to 2016-12-31.\",\n         x = \"\", y = \"USD value at the end of the month\", color = \"\") +\n  scale_y_continuous(labels = scales::dollar) +\n  theme_tq() +\n  scale_color_tq()\n\nFANG_monthly_all\n```\n\n::: {.cell-output-display}\n![Monthly cumulative USD returns.](03-prices-and-returns_files/figure-html/fig-mcur-1.png){#fig-mcur width=672}\n:::\n:::\n\n\n\n\nEach stock now begins at the same $100 base value. The plot shows that a common starting investment can lead to very different terminal values, even when the original price series have different price levels.\n\nA faceted version separates the four stocks and makes the comparison easier to read.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFANG_monthly <- FANG_monthly_all +\n  facet_wrap(~ symbol, ncol = 2, scales = \"free_y\") +\n  theme(legend.position = \"none\", legend.title = element_blank())\n\nFANG_monthly\n```\n\n::: {.cell-output-display}\n![Monthly cumulative USD returns, a facet view.](03-prices-and-returns_files/figure-html/fig-mcurafv-1.png){#fig-mcurafv width=672}\n:::\n:::\n\n\n\n\nThe dollar value of \\$100 invested in Amazon at the end of the 4 years is again \\$291.4267. The monthly view shows the path of the investment value through time. The faceted view confirms the same message with cleaner scales: every panel starts at $100, and Netflix reaches the largest terminal value in this historical window.\n\nReturn to the original price plot.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFANG_daily_all\n```\n\n::: {.cell-output-display}\n![Daily stock prices on their original scales, revisited.](03-prices-and-returns_files/figure-html/fig-dspnsetra-1.png){#fig-dspnsetra width=672}\n:::\n:::\n\n\n\n\nNetflix looks low in the original price chart because its dollar price is plotted on the same scale as higher-priced stocks. A \\$100 investment in Netflix during these four years would nevertheless produce the highest terminal value, close to \\$1,000. This contrast motivates the return-based analysis used in the rest of the book.\n\nPlotting prices and returns over time helps connect financial performance with specific dates. A deeper analysis could investigate the events around 2014 for Amazon and Google and connect firm-level news, market conditions, and investor expectations with the observed returns.\n\n## Distribution of returns\n\nTime series plots are useful for financial analysis because they preserve chronology. Density plots provide a complementary view: they remove time and show the distribution of return values. The vertical axis is density. Areas under the curve represent probability mass, so taller regions indicate where returns are more concentrated. This approach helps compare typical returns, unusual outcomes, and dispersion across assets.\n\nThe next figure uses density plots to compare the distribution of monthly returns in the <tt>`FANG`</tt> data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(FANG_monthly_returns, aes(x = monthly.returns, fill = symbol)) +\n  geom_density(alpha = 0.5) +\n  geom_hline(yintercept = 0, color = palette_light()[[1]]) +\n  labs(x = \"Monthly returns\", y = \"Density\") +\n  xlim(-0.3, 0.9) +\n  theme_tq() +\n  scale_fill_tq()\n```\n\n::: {.cell-output-display}\n![FANG: monthly returns, a density view.](03-prices-and-returns_files/figure-html/fig-fmradv-1.png){#fig-fmradv width=672}\n:::\n:::\n\n\n\n\nMonthly returns around zero are frequent, whereas monthly returns above 50% are rare in this sample. The density plot also shows that Netflix has the widest dispersion among the four stocks. A faceted version separates the distributions and makes the comparison easier to read.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Density plots.\nggplot(FANG_monthly_returns, aes(x = monthly.returns, fill = symbol)) +\n  geom_density(alpha = 0.5) +\n  geom_hline(yintercept = 0, color = \"black\") +\n  labs(x = \"Monthly returns\", y = \"Density\") +\n  xlim(-0.3, 0.9) +\n  theme_tq() +\n  scale_fill_tq() +\n  facet_wrap(~ symbol, ncol = 2) +\n  theme(legend.position = \"none\", legend.title = element_blank())\n```\n\n::: {.cell-output-display}\n![FANG: monthly returns, a density and facet view.](03-prices-and-returns_files/figure-html/fig-fmradafv-1.png){#fig-fmradafv width=672}\n:::\n:::\n\n\n\nThe faceted density plot separates the four stocks and makes dispersion easier to compare.\n\n-   AMZN. The mode is close to zero, suggesting that monthly returns near zero are frequent in this sample. Most observations fall roughly between -25% and 25%, with a few large positive months.\n-   GOOG. The distribution is more concentrated around zero than AMZN in this sample. This suggests lower monthly-return dispersion over the 2013-2016 window.\n-   META. The mode is slightly above zero. The sample mean should be verified from summary statistics because the mode and the mean can differ. A few large positive monthly returns make the distribution more dispersed.\n-   NFLX. The distribution has the widest dispersion among the four stocks in this sample, which is consistent with the large cumulative investment value and the larger risk estimate calculated below.\n\nDensity distributions summarize the shape of the returns, but this example has only 48 monthly observations for each stock. That is enough for illustration and too small for strong conclusions about long-run distributional behavior.\n\nMonthly returns can also be grouped by calendar year to compare within-year dispersion.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFANG_monthly_returns |>\n  mutate(year = as.factor(year(date))) |>\n  ggplot(aes(x = monthly.returns, fill = symbol)) +\n  geom_density(alpha = 0.5) +\n  geom_hline(yintercept = 0) +\n  labs(x = \"Monthly returns\", y = \"Density\") + xlim(-0.3, 0.6) +\n  theme_tq() +\n  scale_fill_tq() +\n  facet_wrap(~ year, ncol = 2)\n```\n\n::: {.cell-output-display}\n![FANG: Monthly return distribution per year.](03-prices-and-returns_files/figure-html/fig-fmrdpy-1.png){#fig-fmrdpy width=672}\n:::\n:::\n\n\n\n\nThis view shows that return dispersion changes across years. Netflix contributes several extreme monthly observations, whereas Google remains comparatively concentrated around zero in this sample.\n\nStatistical indicators complement the previous graphical analysis.\n\nFor a sample of returns $R_1,\\ldots,R_n$, the statistics used below are defined as follows.\n\n$$\n\\bar{R}=\\frac{1}{n}\\sum_{t=1}^{n}R_t,\n\\qquad\ns_R=\\sqrt{\\frac{1}{n-1}\\sum_{t=1}^{n}(R_t-\\bar{R})^2},\n\\qquad\nsr=\\frac{\\bar{R}}{s_R}.\n$$\n\nThe interquartile range is $IQR=Q_{0.75}-Q_{0.25}$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate relevant statistics.\nFANG_stats <- FANG_monthly_returns |>\nsummarise(mean = mean(monthly.returns), sd = sd(monthly.returns),\n          sr = mean/sd, iqr = IQR(monthly.returns))\nFANG_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  symbol   mean     sd    sr    iqr\n  <chr>   <dbl>  <dbl> <dbl>  <dbl>\n1 AMZN   0.0257 0.0817 0.314 0.126 \n2 GOOG   0.0176 0.0594 0.296 0.0646\n3 META   0.0341 0.0989 0.345 0.108 \n4 NFLX   0.0592 0.167  0.355 0.193 \n```\n\n\n:::\n:::\n\n\n\n\nThe sample mean estimates expected return in this historical window. GOOG has the lowest mean and NFLX has the highest. The standard deviation <tt>`sd`</tt> measures dispersion around the mean and is used here as a simple risk proxy. GOOG has the lowest standard deviation and NFLX has the highest. The interquartile range <tt>`IQR`</tt> measures the distance between the 75th and 25th percentiles, adding a robust view of dispersion.\n\nComparing return and risk, or mean and standard deviation of stock returns can be troublesome. This is because the relationship between risk and return is not perfectly proportional.\n\nThe risk-return comparison can also be shown graphically.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Mean variance plot.\nFANG_stats |>\n  ggplot(aes(x = sd, y = mean, color = symbol)) +\n  geom_point(size = 5) +\n  geom_text(aes(label = paste0(round(sr, 3))),\n            vjust = 2, color = \"black\", size = 3.5) +\n  xlim(0.04, 0.18) +\n  ylim(0.01, 0.06) +\n  labs(subtitle = \"Numerical values represent return per unit of risk.\",\n       x = \"Risk\", y = \"Expected return\") +\n  theme_tq()\n```\n\n::: {.cell-output-display}\n![FANG: risk-return comparison.](03-prices-and-returns_files/figure-html/fig-fthtrthtr-1.png){#fig-fthtrthtr width=672}\n:::\n:::\n\n\n\n\nAccording to these estimates, Netflix is the stock with the highest return and risk. Return per unit of risk is calculated by dividing the mean by the standard deviation. This indicator is called <tt>`sr`</tt> in the table above. Under this metric, Netflix also has the highest return per unit of risk among the four stocks, which is consistent with the cumulative-return comparison.\n\nThe plot above measures returns on the vertical axis and risk on the horizontal axis. In finance, this is a mean-variance view: the mean summarizes return, and the variance or standard deviation summarizes risk. The mean-variance approach was a breakthrough because it organized investment comparisons around the joint behavior of risk and return.\n\nSuppose stock 1 has a return of 5% and a risk of 4%, whereas stock 2 has a return of 6% and a risk of 8%. Stock 1 has 1.25 units of return per unit of risk (5/4), while stock 2 has 0.75. The relative comparison favors stock 1 even though stock 2 has the higher raw return.\n\nReturn distributions help separate lower-risk and higher-risk assets. The next example simulates two artificial return series with the same expected return of 0% and different volatility levels.\n\n$$\nR^{low}_t \\sim N(0,0.01^2),\n\\qquad\nR^{high}_t \\sim N(0,0.02^2).\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create random assets.\nset.seed(13)\nless_risky <- data.frame(return = rnorm(10000, 0, 0.01))\nmore_risky <- data.frame(return = rnorm(10000, 0, 0.02))\n# Name random assets.\nless_risky$asset <- 'Less risky asset'\nmore_risky$asset <- 'Riskier asset'\nassets <- rbind(less_risky, more_risky)\n# Plot the assets.\nggplot(assets, aes(return, fill = asset)) +\n  geom_density(alpha = 0.5, adjust = 3) +\n  geom_hline(yintercept = 0) +\n  scale_x_continuous(labels = scales::percent) +\n  labs(x = \"Simulated return\", y = \"Density\")\n```\n\n::: {.cell-output-display}\n![Risk illustration.](03-prices-and-returns_files/figure-html/fig-ri-1.png){#fig-ri width=672}\n:::\n:::\n\n\n\n\nThe riskier asset can take a wider range of returns. Most simulated observations for the less risky asset are closer to zero; the riskier asset has wider tails. The code generates 10,000 random values following a normal distribution with mean zero, and standard deviations of 1% and 2% for the less risky and riskier asset respectively.\n\nThe next chapter uses this same return language in a trading workflow. The book moves from describing return distributions to building lagged indicators that become inputs for a simple robo trader. The goal is to see how prices and returns can be transformed into trading signals while keeping the timing of the information explicit.\n",
    "supporting": [
      "03-prices-and-returns_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}