{
  "hash": "8066229dcad3f355f21cf5d2031c994e",
  "result": {
    "engine": "knitr",
    "markdown": "# Portfolio allocation\n\n\n\n\n\n\n\n\n\nThe previous chapter estimated return exposures one asset at a time. Portfolio allocation turns those individual assets into a portfolio decision. The practical question is how much capital should be assigned to each asset when expected returns, risk, correlations, and investment constraints are considered together.\n\nOptimization selects a feasible solution under an explicit objective and a set of constraints. In this chapter, the feasible solution is a vector of portfolio weights. The objective can be low risk, high expected return, a strong return-risk ratio, or a benchmark comparison. The constraints can require full investment, long-only positions, maximum weights, minimum weights, or rebalancing rules. R is useful because the calculation combines data transformation, matrix operations, optimization, and performance evaluation.\n\nDiversification is the central idea. If all assets move together, portfolio risk remains close to single-asset risk. If assets respond differently to common shocks, portfolio volatility can fall even when expected return remains attractive. The correlation examples from earlier chapters prepare this point: co-movement determines how much risk can be reduced by combining assets.\n\nThe combined investment is a portfolio, and each percentage invested in an individual asset is a portfolio weight. Portfolio allocation models estimate or test these weights. The chapter separates four tasks: estimate returns and covariances, optimize weights under constraints, compare benchmarks, and evaluate realized performance. It starts with a single-period FANG portfolio, then compares optimization methods, examines an equally weighted benchmark, introduces synthetic assets to isolate diversification, and finishes with rebalancing and performance evaluation.\n\n\n## The single-period problem\n\nThe single-period problem is the simplest framework for portfolio allocation. At $t=0$, the investor observes historical information, chooses portfolio weights, and then realizes a portfolio return at $t=1$.\n\nThe example uses the <tt>`PortfolioAnalytics`</tt> package to distribute 100% of available capital across four stocks. For convenience, the example uses monthly returns from the <tt>`FANG`</tt> database.\n\nIf $w_i$ is the portfolio weight of asset $i$ and $R_i$ is its return, the portfolio return is defined as\n\n$$\nR_p=\\sum_{i=1}^{N}w_iR_i.\n$$\n\nThe portfolio expected return and variance are\n\n$$\nE(R_p)=w'\\mu,\n\\qquad\n\\sigma_p^2=w'\\Sigma w.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFANG_monthly_returns <- FANG |>\n    group_by(symbol) |>\n    tq_transmute(select     = adjusted,\n                 mutate_fun = periodReturn,\n                 period     = \"monthly\",\n                 type       = \"arithmetic\")\n\nFANG_monthly_returns\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 192 × 3\n# Groups:   symbol [4]\n   symbol date       monthly.returns\n   <chr>  <date>               <dbl>\n 1 META   2013-01-31        0.106   \n 2 META   2013-02-28       -0.120   \n 3 META   2013-03-28       -0.0613  \n 4 META   2013-04-30        0.0856  \n 5 META   2013-05-31       -0.123   \n 6 META   2013-06-28        0.0218  \n 7 META   2013-07-31        0.479   \n 8 META   2013-08-30        0.122   \n 9 META   2013-09-30        0.217   \n10 META   2013-10-31       -0.000398\n# ℹ 182 more rows\n```\n\n\n:::\n:::\n\n\n\n\nThe <tt>`PortfolioAnalytics`</tt> package expects returns in a wide format, with one column per asset. The <tt>`FANG_monthly_returns`</tt> object is tidy, with a <tt>`symbol`</tt> column identifying the stock. The following transformation reshapes the data so each stock has its own return column.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfang <- FANG_monthly_returns |>\n  tbl_xts(spread_by = \"symbol\")\n\nhead(fang)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  META         AMZN        NFLX        GOOG\n2013-01-31  0.10642857  0.031829319  0.79589177  0.04485307\n2013-02-28 -0.12040026 -0.004632810  0.13822318  0.06022315\n2013-03-28 -0.06128440  0.008400504  0.00638028 -0.00874938\n2013-04-30  0.08561376 -0.047581495  0.14153635  0.03825280\n2013-05-31 -0.12315448  0.060635964  0.04711437  0.05657498\n2013-06-28  0.02176587  0.031537851 -0.06700557  0.01050246\n```\n\n\n:::\n:::\n\n\n\n\nThe <tt>`FANG`</tt> information is the same, but the format now matches the requirements of the portfolio functions. The correlation matrix summarizes how the four stock returns move together.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(fang)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          META      AMZN      NFLX      GOOG\nMETA 1.0000000 0.1846197 0.2182079 0.2468989\nAMZN 0.1846197 1.0000000 0.3118020 0.6171376\nNFLX 0.2182079 0.3118020 1.0000000 0.3586214\nGOOG 0.2468989 0.6171376 0.3586214 1.0000000\n```\n\n\n:::\n:::\n\n\n\n\nThe lowest correlation is between META and AMZN (0.1846197), which indicates a weak linear relationship. GOOG and AMZN have a correlation of 0.6171376, suggesting a stronger linear relationship between those stock returns. In principle, lower correlation creates greater diversification possibilities when forming a portfolio. The ice-cream and hot-chocolate example used a correlation of -0.9 to illustrate a strong volatility-reduction effect. In practice, strongly negative correlations are difficult to find, although diversification gains can arise whenever correlation is below +1.\n\nThe model output is a vector of weights, which indicates how much capital is assigned to each of the four assets.\n\nThe portfolio specification is defined with <tt>`portfolio.spec()`</tt>.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the portfolio specification\nport_spec <- portfolio.spec(colnames(fang))\nport_spec\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**************************************************\nPortfolioAnalytics Portfolio Specification \n**************************************************\n\nCall:\nportfolio.spec(assets = colnames(fang))\n\nNumber of assets: 4 \nAsset Names\n[1] \"META\" \"AMZN\" \"NFLX\" \"GOOG\"\n```\n\n\n:::\n:::\n\n\n\n\nThe portfolio specification uses four assets. A full-investment constraint keeps the weights close to a total of 1. In practical terms, requiring an exact sum of 1 can be too restrictive for numerical optimization, so the allowed range is 0.99 to 1.01.\n\n$$\n0.99 \\leq \\sum_{i=1}^{N}w_i \\leq 1.01.\n$$\n\nThe <tt>`add.constraint()`</tt> function inserts this restriction into the portfolio specification.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nport_spec <- add.constraint(portfolio = port_spec, type = \"weight_sum\",\n                            min_sum = 0.99, max_sum = 1.01)\nport_spec\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**************************************************\nPortfolioAnalytics Portfolio Specification \n**************************************************\n\nCall:\nportfolio.spec(assets = colnames(fang))\n\nNumber of assets: 4 \nAsset Names\n[1] \"META\" \"AMZN\" \"NFLX\" \"GOOG\"\n\nConstraints\nEnabled constraint types\n\t\t- weight_sum \n```\n\n\n:::\n:::\n\n\n\n\nA box constraint keeps the optimal portfolio weights between 0 and 1. This is equivalent to a *long-only* constraint.\n\n$$\n0 \\leq w_i \\leq 1.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nport_spec <- add.constraint(portfolio = port_spec, type = \"box\",\n                            min = 0, max = 1)\nport_spec\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**************************************************\nPortfolioAnalytics Portfolio Specification \n**************************************************\n\nCall:\nportfolio.spec(assets = colnames(fang))\n\nNumber of assets: 4 \nAsset Names\n[1] \"META\" \"AMZN\" \"NFLX\" \"GOOG\"\n\nConstraints\nEnabled constraint types\n\t\t- weight_sum \n\t\t- box (long only) \n```\n\n\n:::\n:::\n\n\n\n\nThe chapter focuses on risk and return as a joint portfolio problem. The optimization setup adds objectives for expected return and standard deviation. The return per unit of risk used to compare portfolios is\n\n$$\nSR(w)=\\frac{E(R_p)}{\\sigma_p},\n\\quad \\text{with } w \\text{ subject to the constraints above.}\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add an objective to minimize portfolio standard deviation\nport_spec <- add.objective(portfolio = port_spec,\n                           type = \"risk\",\n                           name = \"StdDev\")\nport_spec <- add.objective(portfolio = port_spec,\n                           type = \"return\",\n                           name = \"mean\")\nport_spec\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**************************************************\nPortfolioAnalytics Portfolio Specification \n**************************************************\n\nCall:\nportfolio.spec(assets = colnames(fang))\n\nNumber of assets: 4 \nAsset Names\n[1] \"META\" \"AMZN\" \"NFLX\" \"GOOG\"\n\nConstraints\nEnabled constraint types\n\t\t- weight_sum \n\t\t- box (long only) \n\nObjectives:\nEnabled objective names\n\t\t- StdDev \n\t\t- mean \n```\n\n\n:::\n:::\n\n\n\n\nThe portfolio specification indicates that four assets are available: META, AMZN, NFLX, and GOOG. The constraints require the portfolio to invest 100% of the available funds, or very close to that value, and to keep individual weights nonnegative.\n\nRemoving the box constraint would allow the model to deliver negative portfolio weights. Negative portfolio weights represent short sales, which are positions that benefit when an asset price declines. Many investment mandates restrict short selling, so the box constraint makes the exercise closer to a long-only portfolio decision.\n\nThe <tt>`optimize.portfolio()`</tt> function can solve the portfolio problem with several methods, constraints, and objectives. The examples below compare the random and ROI methods.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Solve the optimization problem.\nset.seed(13)\nopt_rand <- optimize.portfolio(fang, portfolio = port_spec,\n                               optimize_method = \"random\", trace = TRUE)\nopt_roi <- optimize.portfolio(fang, portfolio = port_spec,\n                              optimize_method = \"ROI\", trace = TRUE)\n# Show optimization results.\nopt_rand\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n***********************************\nPortfolioAnalytics Optimization\n***********************************\n\nCall:\noptimize.portfolio(R = fang, portfolio = port_spec, optimize_method = \"random\", \n    trace = TRUE)\n\nOptimal Weights:\n META  AMZN  NFLX  GOOG \n0.282 0.162 0.074 0.472 \n\nObjective Measures:\n StdDev \n0.05808 \n\n\n   mean \n0.02646 \n```\n\n\n:::\n\n```{.r .cell-code}\nopt_roi\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n***********************************\nPortfolioAnalytics Optimization\n***********************************\n\nCall:\noptimize.portfolio(R = fang, portfolio = port_spec, optimize_method = \"ROI\", \n    trace = TRUE)\n\nOptimal Weights:\n  META   AMZN   NFLX   GOOG \n0.3907 0.0000 0.6193 0.0000 \n\nObjective Measure:\nmean \n0.05 \n\n\nStdDev \n0.1178 \n```\n\n\n:::\n:::\n\n\n\n\n\n\nThe output above shows the portfolio weights, return, and risk of the two optimized portfolios. Before plotting the optimized results, the initial situation is inspected: the individual assets before considering any portfolio.\n\nThe relevant <tt>`FANG`</tt> data provide the individual monthly returns used to estimate the allocation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFANG_monthly_returns <- FANG |>\n    group_by(symbol) |>\n    tq_transmute(select     = adjusted,\n                 mutate_fun = periodReturn,\n                 period     = \"monthly\",\n                 type       = \"arithmetic\")\n\nFANG_stats <- FANG_monthly_returns |>\nsummarise(mean = mean(monthly.returns),\n          sd = sd(monthly.returns),\n          sr = mean/sd)\n\nFANG_stats\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  symbol   mean     sd    sr\n  <chr>   <dbl>  <dbl> <dbl>\n1 AMZN   0.0257 0.0817 0.314\n2 GOOG   0.0176 0.0594 0.296\n3 META   0.0341 0.0989 0.345\n4 NFLX   0.0592 0.167  0.355\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(FANG_stats, aes(x = sd, y = mean, color = symbol)) +\n  geom_point(size = 5) +\n  geom_text(aes(label = paste0(symbol)),\n  vjust = 2, color = \"black\", size = 3.5) +\n  labs(x = \"Risk\", y = \"Return\") +\n  scale_y_continuous(limits = c(0.01, 0.06),\n                     labels = scales::percent) +\n  scale_x_continuous(labels = scales::percent) +\n  theme_tq() +\n  theme(legend.position = \"none\", legend.title = element_blank())\n```\n\n::: {.cell-output-display}\n![FANG, the four individual assets.](06-asset-allocation_files/figure-html/fig-ftfia-1.png){#fig-ftfia width=672}\n:::\n:::\n\n\n\n\nThe plot places the four individual assets in mean-variance space. Portfolio allocation adds a portfolio perspective by combining assets so the joint risk-return profile can improve over a single-asset choice. The optimization process searches for the allocation that satisfies the objective and constraints.\n\nFor example, a portfolio with 3.5% monthly expected return and 15% standard deviation is dominated by alternatives with similar return and lower risk. A portfolio with 4% expected return and 5% risk would have a stronger return per unit of risk. This is the kind of comparison the optimizer formalizes.\n\nRandom portfolio optimization evaluates many candidate portfolios. Under the selected objective, the method searches for a combination with a more attractive return per unit of risk than the individual assets.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot results.\nchart.RiskReward(opt_rand, risk.col = \"StdDev\",\n                 return.col = \"mean\", chart.assets = TRUE,\n                 xlim = c(0, 0.10))\nabline(v = 0.05941703, lty = 2)\nabline(h = 0.02566966, lty = 2)\nlegend(\"bottomright\", legend = c(\"opt_rand\", \"equally_weighted\"),\n       col = c(\"blue\", \"orange\"), pch = 19, cex = 0.9)\n```\n\n::: {.cell-output-display}\n![FANG, random method optimal portfolio.](06-asset-allocation_files/figure-html/fig-frmop-1.png){#fig-frmop width=672}\n:::\n:::\n\n\n\n\nAccording to the portfolio specification and asset universe, the gray circles represent feasible combinations of the individual assets. Some feasible portfolios have lower risk than GOOG. The algorithm selects the blue portfolio as the optimum under the chosen objective and constraints. This portfolio has approximately the same risk as GOOG with higher expected return, and a similar expected return to AMZN with lower risk. The gray portfolios form a mean-variance frontier. Portfolios to the left of that boundary are unavailable under the current data and constraints, and the selected optimum lies on the frontier.\n\nThe blue point marks the strongest available trade-off under the optimization setup. A point above it would offer higher return for the same risk, and a point to the left would offer lower risk for the same return. Those alternatives are outside the feasible set. Points below or to the right are feasible, although they offer a weaker trade-off. Efficient portfolios are therefore located on the upper-left boundary of the mean-variance cloud.\n\nThe corresponding weights translate the blue point into an implementable allocation.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Weights(opt_rand)\n```\n\n::: {.cell-output-display}\n![FANG, random method optimal weights.](06-asset-allocation_files/figure-html/fig-frmow-1.png){#fig-frmow width=672}\n:::\n:::\n\n\n\n\nThe <tt>`opt_rand`</tt> weights define the implementable allocation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextractWeights(opt_rand)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n META  AMZN  NFLX  GOOG \n0.282 0.162 0.074 0.472 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nopt_rand_mean <- as.numeric(extractObjectiveMeasures(opt_rand)$mean)\nopt_rand_sd <-\n  as.numeric(extractObjectiveMeasures(opt_rand)$StdDev[1,1])\nopt_rand_sr <- opt_rand_mean/opt_rand_sd\n\nopt_rand_summary <-data.frame(mean = opt_rand_mean,\n                              sd = opt_rand_sd, sr = opt_rand_sr)\nrow.names(opt_rand_summary) <- \"opt_rand\"\n\nFANG_stats |>\n  add_row(symbol = \"opt_rand\", opt_rand_summary) |>\n  arrange(-sr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 4\n  symbol     mean     sd    sr\n  <chr>     <dbl>  <dbl> <dbl>\n1 opt_rand 0.0265 0.0581 0.456\n2 NFLX     0.0592 0.167  0.355\n3 META     0.0341 0.0989 0.345\n4 AMZN     0.0257 0.0817 0.314\n5 GOOG     0.0176 0.0594 0.296\n```\n\n\n:::\n:::\n\n\n\n\nThe optimal portfolio <tt>`opt_rand`</tt> has a 0.4555797 return per unit of risk. Under this sample and criterion, it improves on the individual assets shown below.\n\nA second criterion is to optimize according to ROI (R Optimization Infrastructure for linear and quadratic programming solvers).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot results.\nchart.RiskReward(opt_roi, risk.col = \"StdDev\",\n                 xlim = c(0.05, 0.18),\n                 return.col = \"mean\", rp = TRUE, chart.assets = TRUE)\npoints(0.05807126, 0.02606294, pch = 19, cex = 1.5, col = \"black\")\nlegend(\"bottomright\", legend = c(\"ROI\", \"opt_rand\"),\n       col = c(\"blue\", \"black\"), pch = 19, cex = 0.9)\n```\n\n::: {.cell-output-display}\n![FANG, ROI method optimal portfolio.](06-asset-allocation_files/figure-html/fig-frmop2-1.png){#fig-frmop2 width=672}\n:::\n:::\n\n\n\n\nA different optimization method leads to a different portfolio. Both selected portfolios lie on the efficient frontier under the current data, constraints, and objective specification.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Weights(opt_roi)\n```\n\n::: {.cell-output-display}\n![FANG, ROI method optimal weights.](06-asset-allocation_files/figure-html/fig-frmow2-1.png){#fig-frmow2 width=672}\n:::\n:::\n\n\n\n\nThe <tt>`opt_roi`</tt> weights define the allocation under the ROI method.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextractWeights(opt_roi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        META         AMZN         NFLX         GOOG \n3.906783e-01 0.000000e+00 6.193217e-01 5.610126e-17 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nopt_roi_mean <- as.numeric(extractObjectiveMeasures(opt_roi)$mean)\nopt_roi_sd <-\n  as.numeric(extractObjectiveMeasures(opt_roi)$StdDev)\nopt_roi_sr <- opt_roi_mean/opt_roi_sd\n\nopt_roi_summary <-data.frame(mean = opt_roi_mean,\n                              sd = opt_roi_sd, sr = opt_roi_sr)\nrow.names(opt_roi_summary) <- \"opt_roi\"\n\nFANG_stats |>\n  add_row(symbol = \"opt_rand\", opt_rand_summary) |>\n  add_row(symbol = \"opt_roi\", opt_roi_summary) |>\n  arrange(-sr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  symbol     mean     sd    sr\n  <chr>     <dbl>  <dbl> <dbl>\n1 opt_rand 0.0265 0.0581 0.456\n2 opt_roi  0.0500 0.118  0.424\n3 NFLX     0.0592 0.167  0.355\n4 META     0.0341 0.0989 0.345\n5 AMZN     0.0257 0.0817 0.314\n6 GOOG     0.0176 0.0594 0.296\n```\n\n\n:::\n:::\n\n\n\nThe optimal portfolio <tt>`opt_roi`</tt> has a 0.4244362 return per unit of risk. The value exceeds the individual assets and remains below the <tt>`opt_rand`</tt> portfolio. According to this return-risk ratio, <tt>`opt_rand`</tt> ranks first in this comparison, with 0.4555797 return per unit of risk. The optimization process therefore produces a portfolio that improves on the individual assets in this historical sample. In practice, an allocation such as 28.2% in META, 16.2% in AMZN, 7.4% in NFLX, and 47.2% in GOOG would still require additional checks before implementation, including estimation stability, transaction costs, liquidity, constraints, and investor suitability.\n\nThe orange portfolio represents an equally weighted benchmark with 25% in each asset. With $N=4$, the weight is $1/N=1/4$. This benchmark requires no optimization and still offers a diversified comparison point. In this example, it is close to the optimized alternatives and provides a useful check on whether optimization adds value under the selected assumptions.\n\nA benchmark portfolio specification <tt>`port_naive`</tt> forces each weight to be exactly 0.25.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nport_naive <- portfolio.spec(colnames(fang))\nport_naive <- add.constraint(portfolio = port_naive,\n                             type = \"full_investment\")\nport_naive <- add.constraint(portfolio = port_naive,\n                             type = \"long_only\")\nport_naive <- add.objective(portfolio = port_naive,\n                           type = \"risk\",\n                           name = \"StdDev\")\nport_naive <- add.objective(portfolio = port_naive,\n                           type = \"return\",\n                           name = \"mean\")\n```\n:::\n\n\n\n\nThe comparison table adds the equal-weight benchmark to the optimized alternatives.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nopt_naive <- equal.weight(fang, portfolio = port_naive)\nopt_naive_mean <- as.numeric(extractObjectiveMeasures(opt_naive)$mean)\nopt_naive_sd <-\n  as.numeric(extractObjectiveMeasures(opt_naive)$StdDev)\nopt_naive_sr <- opt_naive_mean/opt_naive_sd\nopt_naive_summary <-data.frame(mean = opt_naive_mean,\n                              sd = opt_naive_sd, sr = opt_naive_sr)\nrow.names(opt_naive_summary) <- \"opt_naive\"\n\nFANG_stats |>\n  add_row(symbol = \"opt_rand\", opt_rand_summary) |>\n  add_row(symbol = \"opt_roi\", opt_roi_summary) |>\n  add_row(symbol = \"opt_naive\", opt_naive_summary) |>\n  arrange(-sr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 4\n  symbol      mean     sd    sr\n  <chr>      <dbl>  <dbl> <dbl>\n1 opt_naive 0.0341 0.0718 0.476\n2 opt_rand  0.0265 0.0581 0.456\n3 opt_roi   0.0500 0.118  0.424\n4 NFLX      0.0592 0.167  0.355\n5 META      0.0341 0.0989 0.345\n6 AMZN      0.0257 0.0817 0.314\n7 GOOG      0.0176 0.0594 0.296\n```\n\n\n:::\n:::\n\n\n\nThe benchmark portfolio <tt>`port_naive`</tt> has the highest Sharpe ratio in this comparison, including the optimized alternatives. This result is informative: optimization depends on the objective, constraints, method, and sample estimates. A target-return constraint can search for an optimized portfolio that matches the benchmark portfolio's expected return.\n\n$$\nw'\\mu = R_{\\text{target}}.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nport_spec2 <- add.constraint(portfolio = port_spec, type = \"return\",\n                             return_target = 0.03414333)\nset.seed(13)\nopt_roi2 <- optimize.portfolio(fang, portfolio = port_spec2,\n                               optimize_method = \"ROI\", maxSR = TRUE,\n                               rf = 0, trace = TRUE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Weights(opt_roi2)\n```\n\n::: {.cell-output-display}\n![FANG, ROI method optimal weights targeting the equal-weight benchmark expected return.](06-asset-allocation_files/figure-html/fig-frmowtttnper-1.png){#fig-frmowtttnper width=672}\n:::\n:::\n\n\n\n\nThe <tt>`opt_roi2`</tt> weights show the allocation that targets the benchmark expected return.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextractWeights(opt_roi2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     META      AMZN      NFLX      GOOG \n0.3755684 0.2987422 0.2049933 0.1203416 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot results.\nchart.RiskReward(opt_roi2, risk.col = \"StdDev\",\nxlim = c(0.07, 0.073),\nylim = c(0.032, 0.036),\nreturn.col = \"mean\", chart.assets = TRUE, cex = 2)\npoints(0.07176544, 0.03414333, pch = 19, col = \"orange\", cex = 2)\nlegend(\"bottomright\", legend = c(\"opt_roi\", \"equally_weighted\"),\ncol = c(\"blue\", \"orange\"), pch = 19, cex = 0.8)\n```\n\n::: {.cell-output-display}\n![FANG, ROI method targeting the equal-weight benchmark expected return.](06-asset-allocation_files/figure-html/fig-frmtttnper-1.png){#fig-frmtttnper width=672}\n:::\n:::\n\n\n\n\nThe <tt>`opt_roi2`</tt> portfolio is compared with the previous alternatives.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nopt_roi2_mean <- as.numeric(extractObjectiveMeasures(opt_roi2)$mean)\nopt_roi2_sd <-\n  as.numeric(extractObjectiveMeasures(opt_roi2)$StdDev)\nopt_roi2_sr <- opt_roi2_mean/opt_roi2_sd\nopt_roi2_summary <-data.frame(mean = opt_roi2_mean,\n                              sd = opt_roi2_sd, sr = opt_roi2_sr)\nrow.names(opt_roi2_summary) <- \"opt_roi2\"\n\nFANG_stats |>\n  add_row(symbol = \"opt_rand\", opt_rand_summary) |>\n  add_row(symbol = \"opt_roi\", opt_roi_summary) |>\n  add_row(symbol = \"opt_naive\", opt_naive_summary) |>\n  add_row(symbol = \"opt_roi2\", opt_roi2_summary) |>\n  arrange(-sr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 4\n  symbol      mean     sd    sr\n  <chr>      <dbl>  <dbl> <dbl>\n1 opt_roi2  0.0347 0.0716 0.485\n2 opt_naive 0.0341 0.0718 0.476\n3 opt_rand  0.0265 0.0581 0.456\n4 opt_roi   0.0500 0.118  0.424\n5 NFLX      0.0592 0.167  0.355\n6 META      0.0341 0.0989 0.345\n7 AMZN      0.0257 0.0817 0.314\n8 GOOG      0.0176 0.0594 0.296\n```\n\n\n:::\n:::\n\n\n\n\n\nThe expected return in $t=0$ of the <tt>`opt_rand`</tt> portfolio is read from the optimizer output. It is the sum of the <tt>`opt_rand`</tt> portfolio weights multiplied by the individual expected returns. The realized return at $t=1$ remains uncertain, so a simple simulation illustrates possible outcomes.\n\nIn this case, $t=0$ is 2016-12-30 and $t=1$ is 2017-01-31. The simulation uses the historical mean and standard deviation information available at $t=0$.\n\nThe simulation generates 1,000 observations for each individual asset and portfolio. This simulation is a simple teaching device. It treats each investment alternative as normally distributed using the historical mean and standard deviation shown above.\n\n$$\n\\tilde{R}_{i,b}=\\hat{\\mu}_i+\\hat{\\sigma}_i z_b,\n\\qquad z_b\\sim N(0,1).\n$$\n\nIt ignores time dependence, changing volatility, tail events, and the full correlation structure. The result is useful for intuition and works as a simplified risk model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of simulations.\nsim = 1000\nset.seed (7)\n# Simulation per stock and portfolio.\ns_AMZN <- rnorm(sim, 0.02566966, 0.08172605)\ns_FB <- rnorm(sim, 0.03412852, 0.09894324)\ns_GOOG <- rnorm(sim, 0.01757620, 0.05941703)\ns_NFLX <- rnorm(sim, 0.05919893, 0.16656346)\ns_ran <- rnorm(sim, opt_rand$opt_values$mean, opt_rand$opt_values$StdDev)\ns_roi <- rnorm(sim, opt_roi$opt_values$mean, opt_roi$opt_values$StdDev)\n```\n:::\n\n\n\n\nThe simulated outcomes are summarized with a boxplot showing the minimum, maximum, median, first quartile, and third quartile.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The boxplot.\nb = cbind(s_FB, s_AMZN, s_NFLX, s_GOOG, s_ran, s_roi)\nboxplot(b, las = 2)\nabline(h = 0, lty = 2)\n```\n\n::: {.cell-output-display}\n![FANG, simulated returns of investment alternatives.](06-asset-allocation_files/figure-html/fig-fsroia-1.png){#fig-fsroia width=672}\n:::\n:::\n\n\n\n\nThe <tt>`opt_rand`</tt> portfolio has a narrower simulated dispersion than several individual stocks, while <tt>`opt_roi`</tt> has a wider simulated dispersion. Real returns can have heavier tails, changing volatility, and co-movement across assets, so this simulation works as a first approximation. Because the historical period is known, the realized returns on 2017-01-31 can be compared with the simulated distribution.\n\nThe 2017-01-31 realized returns provide the out-of-sample check. The <tt>`FANG`</tt> database ends at 2016-12-30, and these historical returns are fixed observations. They are stored directly here to avoid depending on the Meta ticker change or on current data-provider availability for old symbols.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2017-01-31 realized individual asset returns.\nr_stocks <- c(META = 0.1208283,\n              AMZN = 0.101782,\n              NFLX = 0.1076947,\n              GOOG = 0.02058163)\n\nr_stocks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      META       AMZN       NFLX       GOOG \n0.12082830 0.10178200 0.10769470 0.02058163 \n```\n\n\n:::\n:::\n\n\n\n\nThese are the realized monthly returns at $t=1$. They were unavailable when the portfolios were formed at $t=0$, so they provide an out-of-sample check. The realized portfolio return is calculated as the weighted sum of realized individual returns.\n\n$$\nR_{p,t+1}^{\\text{realized}}=\\sum_{i=1}^{N}w_iR_{i,t+1}.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate realized portfolio returns.\nrealized_ret <- c(opt_rand = sum(opt_rand$weights * r_stocks),\n                  opt_roi = sum(opt_roi$weights * r_stocks))\n\nexpected_ret <- c(opt_rand = opt_rand$opt_values$mean,\n                  opt_roi = opt_roi$opt_values$mean)\n\ndata.frame(cbind(realized_ret, expected_ret))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         realized_ret expected_ret\nopt_rand    0.0682462   0.02645942\nopt_roi     0.1139027   0.04999645\n```\n\n\n:::\n:::\n\n\n\n\nThe expected monthly return at $t=0$ for the <tt>`opt_rand`</tt> portfolio is 0.02606294, and its realized monthly return at $t=1$ is 0.06958923. For the <tt>`opt_roi`</tt> portfolio, the expected monthly return at $t=0$ is 0.04999645, and the realized monthly return at $t=1$ is 0.11390269. In this historical check, both realized returns exceeded their estimated values.\n\nThe plot below combines the simulated distribution with the realized returns shown in red.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# The simulation.\nboxplot(b, las = 2)\nabline(h = 0, lty = 2)\n# The realized returns in red.\npoints(1, 0.1208283,  col = \"red\", pch = 19, cex = 2)\npoints(2, 0.101782,   col = \"red\", pch = 19, cex = 2)\npoints(3, 0.1076947,  col = \"red\", pch = 19, cex = 2)\npoints(4, 0.02058163, col = \"red\", pch = 19, cex = 2)\npoints(5, sum(opt_rand$weights * r_stocks), col = \"red\",\n       pch = 19, cex = 2)\npoints(6, sum(opt_roi$weights * r_stocks),  col = \"red\",\n       pch = 19, cex = 2)\n```\n\n::: {.cell-output-display}\n![FANG, simulated returns of investment alternatives with realized returns in red.](06-asset-allocation_files/figure-html/fig-fsroiawrhb2ir-1.png){#fig-fsroiawrhb2ir width=672}\n:::\n:::\n\n\n\n\nThe realized returns can be quite different from the simulated or expected returns. This difference depends on the method, the model, the sample length, the portfolio design, and the random component of returns. Portfolio models produce estimates under assumptions; realized returns can land far away from those estimates. In this <tt>`FANG`</tt> example, the optimized allocations performed well in the realized month.\n\nThe same allocation workflow is applied to the 10-stock data used in the previous asset-pricing example. The value of reproducible code is practical because once the data structure is consistent, the same modeling sequence can be reused with a different asset universe. The set keeps the same broad sector logic used before, where <tt>`VTR`</tt> represents healthcare real estate exposure and <tt>`VOD`</tt> represents telecommunications exposure.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Download individual asset returns.\nR_stocks <- c(\"NEM\", \"AMCR\", \"CLX\", \"VTR\", \"KR\", \"TXN\", \"F\", \"TXT\",\n              \"KLAC\", \"VOD\") |>\n  tq_get(get = \"stock.prices\", from = \"2010-01-01\",\n         to = \"2015-12-31\") |>\n  group_by(symbol) |>\n  tq_transmute(select     = adjusted,\n               mutate_fun = periodReturn,\n               period     = \"monthly\",\n               col_rename = \"R_stocks\")\nR_stocks\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 692 × 3\n# Groups:   symbol [10]\n   symbol date       R_stocks\n   <chr>  <date>        <dbl>\n 1 NEM    2010-01-29  -0.115 \n 2 NEM    2010-02-26   0.150 \n 3 NEM    2010-03-31   0.0355\n 4 NEM    2010-04-30   0.101 \n 5 NEM    2010-05-28  -0.0403\n 6 NEM    2010-06-30   0.149 \n 7 NEM    2010-07-30  -0.0946\n 8 NEM    2010-08-31   0.0970\n 9 NEM    2010-09-30   0.0268\n10 NEM    2010-10-29  -0.0310\n# ℹ 682 more rows\n```\n\n\n:::\n:::\n\n\n\n\nThe portfolio specification uses the 10-asset return matrix.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncapm_stocks <- R_stocks |>\n  tbl_xts(spread_by = \"symbol\") |>\n  na.fill(fill = 0.00)\n\nport_spec <- portfolio.spec(colnames(capm_stocks))\nport_spec <- add.constraint(portfolio = port_spec, type = \"weight_sum\",\n                            min_sum = 0.99, max_sum = 1.01)\nport_spec <- add.constraint(portfolio = port_spec, type = \"box\",\n                            min = 0, max = 1)\nport_spec <- add.objective(portfolio = port_spec,\n                           type = \"risk\",\n                           name = \"StdDev\")\nport_spec <- add.objective(portfolio = port_spec,\n                           type = \"return\",\n                           name = \"mean\")\nport_spec\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n**************************************************\nPortfolioAnalytics Portfolio Specification \n**************************************************\n\nCall:\nportfolio.spec(assets = colnames(capm_stocks))\n\nNumber of assets: 10 \nAsset Names\n [1] \"NEM\"  \"AMCR\" \"CLX\"  \"VTR\"  \"KR\"   \"TXN\"  \"F\"    \"TXT\"  \"KLAC\" \"VOD\" \n\nConstraints\nEnabled constraint types\n\t\t- weight_sum \n\t\t- box (long only) \n\nObjectives:\nEnabled objective names\n\t\t- StdDev \n\t\t- mean \n```\n\n\n:::\n:::\n\n\n\n\nThe random method searches feasible allocations in the 10-asset universe.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(13)\nopt_rand <- optimize.portfolio(capm_stocks, portfolio = port_spec,\n                          optimize_method = \"random\", trace = TRUE)\nchart.RiskReward(opt_rand, risk.col = \"StdDev\",\n                 return.col = \"mean\", chart.assets = TRUE)\nlegend(\"bottomleft\", legend = c(\"opt_rand\", \"equally_weighted\"),\n       col = c(\"blue\", \"orange\"), pch = 19, cex = 0.8)\nabline(0, opt_rand$objective_measures$mean /\n         opt_rand$objective_measures$StdDev, lwd = 2, col = \"red\")\n```\n\n::: {.cell-output-display}\n![10-assets, random method optimal portfolio.](06-asset-allocation_files/figure-html/fig-tarmop-1.png){#fig-tarmop width=672}\n:::\n:::\n\n\n\n\nHere, the slope of the red line corresponds to the optimal portfolio return per unit of risk. The optimal portfolio has a similar return per unit of risk to KR, while the rest of the assets have lower return per unit of risk in this sample.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextractWeights(opt_rand)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  NEM  AMCR   CLX   VTR    KR   TXN     F   TXT  KLAC   VOD \n0.040 0.224 0.486 0.006 0.088 0.000 0.026 0.014 0.000 0.118 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Weights(opt_rand)\n```\n\n::: {.cell-output-display}\n![10-assets, random method optimal weights.](06-asset-allocation_files/figure-html/fig-tarmopw-1.png){#fig-tarmopw width=672}\n:::\n:::\n\n\n\n\nThe ROI method provides a second optimization comparison for the same 10 assets.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nopt_roi <- optimize.portfolio(capm_stocks, portfolio = port_spec,\n                          optimize_method = \"ROI\", trace = TRUE)\nchart.RiskReward(opt_roi, risk.col = \"StdDev\",\n                 return.col = \"mean\", rp = TRUE, chart.assets = TRUE)\nlegend(\"bottomleft\", legend = c(\"opt_roi\"),\n       col = c(\"blue\"), pch = 19, cex = 0.8)\nabline(0, opt_roi$objective_measures$mean /\n         opt_roi$objective_measures$StdDev, lwd = 2, col = \"red\")\n```\n\n::: {.cell-output-display}\n![10-assets, ROI method optimal portfolio.](06-asset-allocation_files/figure-html/fig-tarmop2-1.png){#fig-tarmop2 width=672}\n:::\n:::\n\n\n\nThis solution is concentrated in KR, with a very small KLAC weight caused by the full-investment tolerance.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextractWeights(opt_roi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          NEM          AMCR           CLX           VTR            KR \n 6.050516e-17  2.445685e-16  1.464562e-18  1.728497e-16  1.000000e+00 \n          TXN             F           TXT          KLAC           VOD \n-9.142772e-17 -3.352468e-17  0.000000e+00  1.000000e-02  3.972525e-18 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nchart.Weights(opt_roi)\n```\n\n::: {.cell-output-display}\n![10-assets, ROI method optimal weights.](06-asset-allocation_files/figure-html/fig-tarmow2-1.png){#fig-tarmow2 width=672}\n:::\n:::\n\n\n\n\n## Diversification\n\nIn finance, diversification is the process of allocating capital in a way that reduces exposure to any single asset or risk factor. Holding several assets can reduce portfolio risk when their returns are imperfectly correlated. If the assets move almost together, as Visa and Mastercard did in the previous chapter, diversification gains are limited. This section uses a controlled experiment: two artificial assets, $X$ and $Y$, are added to the <tt>`FANG`</tt> database to create a six-asset universe. Their strong negative correlation isolates the mechanism through which diversification can reduce portfolio volatility.\n\nThe returns of the two new assets are simulated. The assets $X$ and $Y$ do not exist in the real world; they are created to isolate the diversification mechanism.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(13)\ndata = mvrnorm(n = 48, mu = c(0.2, 0.5),\n               Sigma = matrix(c(1, -1.4, -1.4, 2), nrow = 2),\n               empirical = TRUE)/10\nxy = as.data.frame(data)\nX = xy$V1\nY = xy$V2\n# Add X and Y to the fang database.\nfang_xy <- fang\nfang_xy$X <- X\nfang_xy$Y <- Y\nhead(fang_xy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  META         AMZN        NFLX        GOOG          X\n2013-01-31  0.10642857  0.031829319  0.79589177  0.04485307 0.08235099\n2013-02-28 -0.12040026 -0.004632810  0.13822318  0.06022315 0.11219977\n2013-03-28 -0.06128440  0.008400504  0.00638028 -0.00874938 0.15700719\n2013-04-30  0.08561376 -0.047581495  0.14153635  0.03825280 0.09411057\n2013-05-31 -0.12315448  0.060635964  0.04711437  0.05657498 0.07357672\n2013-06-28  0.02176587  0.031537851 -0.06700557  0.01050246 0.01481500\n                     Y\n2013-01-31 -0.04241279\n2013-02-28 -0.05184889\n2013-03-28 -0.16791336\n2013-04-30 -0.04495379\n2013-05-31 -0.05019958\n2013-06-28  0.04137669\n```\n\n\n:::\n:::\n\n\n\n\nThe correlation matrix verifies that the two new assets are negatively correlated.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(fang_xy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            META        AMZN        NFLX       GOOG           X           Y\nMETA  1.00000000  0.18461970  0.21820791  0.2468989  0.03779375 -0.04276241\nAMZN  0.18461970  1.00000000  0.31180203  0.6171376  0.04877402 -0.05611269\nNFLX  0.21820791  0.31180203  1.00000000  0.3586214  0.06772682 -0.05943567\nGOOG  0.24689886  0.61713764  0.35862138  1.0000000  0.20682201 -0.19110508\nX     0.03779375  0.04877402  0.06772682  0.2068220  1.00000000 -0.98994949\nY    -0.04276241 -0.05611269 -0.05943567 -0.1911051 -0.98994949  1.00000000\n```\n\n\n:::\n:::\n\n\n\n\nThe correlation of $X$ and $Y$ is -0.98994949, very close to -1, so they are strongly negatively correlated. Their correlations with the original assets are also negative. Under the same objective, this expanded universe creates room for a portfolio with a stronger return per unit of risk.\n\nNegative correlation reduces the covariance component of portfolio variance. Expected return is still the weighted average of the individual expected returns, so it does not mechanically become zero.\n\nA sequence of $X$ and $Y$ portfolio weights is created.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_x <- seq(0, 1, 0.01)\nw_y <- 1 - w_x\n```\n:::\n\n\n\n\nFor a two-asset portfolio, expected return remains a weighted average and risk depends on variances plus covariance.\n\n$$\nE(R_p)=w_X\\mu_X+w_Y\\mu_Y,\n$$\n\n$$\n\\sigma_p =\n\\sqrt{\nw_X^2\\sigma_X^2+\nw_Y^2\\sigma_Y^2+\n2w_Xw_Y\\rho_{XY}\\sigma_X\\sigma_Y\n}.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nret_xy <- w_x * mean(fang_xy$X) + w_y * mean(fang_xy$Y)\nsd_xy <- (w_x^2 * sd(fang_xy$X)^2 +\n          w_y^2 * sd(fang_xy$Y)^2 +\n          2 * w_x * w_y * sd(fang_xy$X) * sd(fang_xy$Y) *\n            cor(fang_xy$X, fang_xy$Y))^0.5\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(sd_xy, ret_xy, type = \"l\", xlim = c(0, 0.15), ylim = c(0, 0.05),\n     xlab = \"Risk\", ylab = \"Expected return\")\nabline(v = 0, lty = 2)\nabline(h = 0, lty = 2)\npoints(sd(fang_xy$X), mean(fang_xy$X), cex = 2, pch = 19, col = \"red\")\npoints(sd(fang_xy$Y), mean(fang_xy$Y), cex = 2, pch = 19, col = \"blue\")\nlegend(\"bottomright\", legend = c(\"X\", \"Y\"),\n       col = c(\"red\", \"blue\"), pch = 19, cex = 1)\n```\n\n::: {.cell-output-display}\n![2-assets, efficient frontier.](06-asset-allocation_files/figure-html/fig-taef-1.png){#fig-taef width=672}\n:::\n:::\n\n\n\nThe minimum portfolio risk from this grid is shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(sd_xy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.008354639\n```\n\n\n:::\n:::\n\n\n\nThe observation that matches the minimum portfolio risk identifies the point on the grid where the diversification benefit is strongest.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwhich.min(sd_xy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 60\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(sd_xy, ret_xy, type = \"l\", xlim = c(0, 0.15), ylim = c(0, 0.05),\n     xlab = \"Risk\", ylab = \"Expected return\")\nabline(v = 0, lty = 2)\nabline(h = 0, lty = 2)\npoints(sd(fang_xy$X), mean(fang_xy$X), cex = 2, pch = 19, col = \"red\")\npoints(sd(fang_xy$Y), mean(fang_xy$Y), cex = 2, pch = 19, col = \"blue\")\npoints(sd_xy[60], ret_xy[60], cex = 2, pch = 19)\nlegend(\"bottomright\", legend = c(\"X\", \"Y\"),\n       col = c(\"red\", \"blue\"), pch = 19, cex = 1)\n```\n\n::: {.cell-output-display}\n![2-assets, efficient frontier and minimum variance portfolio.](06-asset-allocation_files/figure-html/fig-taefamvp-1.png){#fig-taefamvp width=672}\n:::\n:::\n\n\n\nThe minimum-variance portfolio weights are shown below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nw_x[60]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.59\n```\n\n\n:::\n\n```{.r .cell-code}\nw_y[60]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.41\n```\n\n\n:::\n:::\n\n\n\n\nThe <tt>`FANG`</tt> database is then combined with the two artificial assets $X$ and $Y$. The portfolio specification and optimization are rebuilt with this expanded asset universe.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create the portfolio specification\nport_spec <- portfolio.spec(colnames(fang_xy))\nport_spec <- add.constraint(portfolio =\n                              port_spec, type = \"full_investment\")\nport_spec <- add.constraint(portfolio = port_spec, type = \"long_only\")\nport_spec <- add.objective(portfolio = port_spec,\n                           type = \"risk\",\n                           name = \"StdDev\")\nport_spec <- add.objective(portfolio = port_spec,\n                           type = \"return\",\n                           name = \"mean\")\n# Optimization.\nset.seed(13)\nopt_xy <- optimize.portfolio(fang_xy, portfolio = port_spec,\n                          optimize_method = \"random\", trace = TRUE)\n```\n:::\n\n\n\n\nThe expanded asset universe is visualized in mean-variance space.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot results.\nchart.RiskReward(opt_xy, risk.col = \"StdDev\",\n                 xlim = c(0, 10),\n                 return.col = \"mean\", chart.assets = TRUE)\npoints(0.05807126, 0.02606294, pch = 19, cex = 1.5, col = \"black\")\npoints(0.1170653,0.04960399, pch = 19, cex = 1.5, col = \"red\")\nlegend(\"topleft\", legend = c(\"opt_xy (FANG+X+Y)\",\n       \"opt_rand (FANG)\", \"opt_roi (FANG)\", \"opt_naive (FANG)\"),\n       col = c(\"blue\", \"black\", \"red\", \"orange\"), pch = 19, cex = 0.9)\n```\n\n::: {.cell-output-display}\n![FANG plus X and Y, random portfolio.](06-asset-allocation_files/figure-html/fig-fpxayrp-1.png){#fig-fpxayrp width=672}\n:::\n:::\n\n\n\n\nThe new assets materially change the optimization because their negative correlation creates a diversification opportunity. The optimal portfolio has almost the same expected return as Meta with substantially lower risk. Correlation therefore plays a central role in diversification: assets with low or negative correlation can reduce portfolio volatility when combined with the rest of the investment universe.\n\nThe details of the new portfolio show how the optimizer uses the artificial diversification opportunity.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extract weight, risk and return.\nextractWeights(opt_xy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n META  AMZN  NFLX  GOOG     X     Y \n0.002 0.028 0.000 0.014 0.522 0.434 \n```\n\n\n:::\n\n```{.r .cell-code}\nopt_xy_mean <- as.numeric(extractObjectiveMeasures(opt_xy)$mean)\nopt_xy_sd <-\n  as.numeric(extractObjectiveMeasures(opt_xy)$StdDev)\nopt_xy_sr <- opt_xy_mean/opt_xy_sd\n\nopt_xy_summary <-data.frame(mean = opt_xy_mean,\n                              sd = opt_xy_sd, sr = opt_xy_sr)\nrow.names(opt_xy_summary) <- \"opt_xy\"\n\nFANG_stats |>\n  add_row(symbol = \"opt_rand\", opt_rand_summary) |>\n  add_row(symbol = \"opt_roi\", opt_roi_summary) |>\n  add_row(symbol = \"opt_naive\", opt_naive_summary) |>\n  add_row(symbol = \"opt_roi2\", opt_roi2_summary) |>\n  add_row(symbol = \"opt_xy\", opt_xy_summary) |>\n  arrange(-sr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 4\n  symbol      mean     sd    sr\n  <chr>      <dbl>  <dbl> <dbl>\n1 opt_xy    0.0332 0.0123 2.70 \n2 opt_roi2  0.0347 0.0716 0.485\n3 opt_naive 0.0341 0.0718 0.476\n4 opt_rand  0.0265 0.0581 0.456\n5 opt_roi   0.0500 0.118  0.424\n6 NFLX      0.0592 0.167  0.355\n7 META      0.0341 0.0989 0.345\n8 AMZN      0.0257 0.0817 0.314\n9 GOOG      0.0176 0.0594 0.296\n```\n\n\n:::\n:::\n\n\n\n\nThe portfolio assigns high weights to $X$ and $Y$, with values of 52.2% and 43.4%. The rest is 0.2% in META, 2.8% in AMZN, 0% in NFLX, and 1.4% in GOOG.\n\n\nThe <tt>`opt_xy`</tt> portfolio shows a large improvement because the artificial assets combine high average returns with a very strong negative correlation. This controlled experiment isolates the diversification mechanism. In practice, investors evaluate return together with volatility, correlation, liquidity, estimation error, and implementation constraints. Low or negatively correlated assets can reduce portfolio volatility and improve the return per unit of risk, while realized returns remain uncertain.\n\nA practical extension is to search for assets with different exposures to risk factors, estimate their joint behavior, and rerun the optimization with realistic constraints. Sector, geography, currency, liquidity, and macroeconomic exposure are natural places to start that search.\n\n## Portfolio rebalancing and evaluation\n\nThe previous sections estimate portfolio weights once. The optimization criterion changed and new assets were added, while the allocation was still selected at a single point in time. Rebalancing extends the problem by recalculating portfolio weights as new returns become available. Evaluation then asks how the resulting strategy performs over a full investment period. This section incorporates both ideas with a different database.\n\nConsider the following investment process. At $t=0$, the investor has access to 60 months of historical information for a set of individual assets. The data from $t=-60$ to $t=0$ is used to estimate portfolio weights and form the portfolio at $t=0$. Returns are then realized for $t=1$, $t=2$, and $t=3$. At $t=3$, the portfolio is re-estimated using the rolling window from $t=-57$ to $t=3$. The same procedure continues through the investment period. The evaluation question is whether the rebalanced strategy produces stronger annualized return and return per unit of risk than a benchmark.\n\nThe process requires repeated data transformation, optimization, implementation, and evaluation. R makes the workflow reproducible because each rebalance date follows the same script. That automation is important in finance: the analyst can focus on assumptions, constraints, risk controls, and interpretation while the computer performs the repeated calculations.\n\nThe rebalancing exercise starts with the asset-return data.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get the data.\ndata(indexes)\nreturns <- indexes[, 1:4]\ntail(returns)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           US Bonds US Equities Int'l Equities Commodities\n2009-07-31   0.0132      0.0703         0.0838      0.0044\n2009-08-31   0.0108      0.0348         0.0517     -0.0242\n2009-09-30   0.0108      0.0360         0.0371      0.0017\n2009-10-31   0.0042     -0.0189        -0.0126      0.0555\n2009-11-30   0.0134      0.0566         0.0199      0.0150\n2009-12-31  -0.0175      0.0189         0.0143      0.0086\n```\n\n\n:::\n:::\n\n\n\n\nThe database goes from 1980-01-31 to 2009-12-31. The assets are US Bonds, US Equities, International Equities, and Commodities. The first allocation is calculated with the initial 60 monthly observations, and later allocations are updated according to the quarterly rebalancing schedule. The realized evaluation period starts after the training window and ends on 2009-12-31.\n\nBefore calculating optimal portfolios, a benchmark portfolio is created. This allows the optimized portfolio to be compared with a simple alternative. In this case, the benchmark is an equally weighted portfolio, investing 25% in each asset for all periods. With $N=4$ assets\n\n$$\nw_i=\\frac{1}{4}=0.25.\n$$\n\nThis equally weighted portfolio requires no optimization. It invests 25% in each asset, or index in this case, and keeps that benchmark rule through the investment period.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Equal weight benchmark.\nn <- ncol(returns)\nequal_weights <- rep(1 / n, n)\nbenchmark_returns <- Return.portfolio(R = returns,\n                                      weights = equal_weights,\n                                      rebalance_on = \"quarters\")\ncolnames(benchmark_returns) <- \"benchmark\"\n# Benchmark performance.\ntable.AnnualizedReturns(benchmark_returns)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          benchmark\nAnnualized Return            0.0769\nAnnualized Std Dev           0.1029\nAnnualized Sharpe (Rf=0%)    0.7476\n```\n\n\n:::\n:::\n\n\n\n\nThe benchmark gives the optimized strategy a simple comparison point.\n\nThe portfolio specification follows the same structure used in the previous section.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Base portfolio specification.\nbase_port_spec <- portfolio.spec(assets = colnames(returns))\n#base_port_spec <- add.constraint(portfolio = base_port_spec,\n#                                 type = \"full_investment\")\n#base_port_spec <- add.constraint(portfolio = base_port_spec,\n#                                 type = \"long_only\")\nbase_port_spec <- add.constraint(portfolio = base_port_spec,\n                                 type = \"weight_sum\",\n                                 min_sum = 0.99, max_sum = 1.01)\nbase_port_spec <- add.constraint(portfolio = base_port_spec,\n                                 type = \"box\", min = 0, max = 1)\nbase_port_spec <- add.objective(portfolio = base_port_spec,\n                                type = \"risk\", name = \"StdDev\")\n```\n:::\n\n\n\n\nThe investment process is implemented with quarterly rebalancing. At each rebalance date, the portfolio return for the next period is determined by the weights chosen from the prior information set.\n\n$$\nR_{p,t}=\\sum_{i=1}^{N}w_{i,t-1}R_{i,t}.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the optimization with periodic rebalancing.\nopt_base <- optimize.portfolio.rebalancing(R = returns,\n            optimize_method = \"ROI\", portfolio = base_port_spec,\n            rebalance_on = \"quarters\", training_period = 60,\n            rolling_window = 60)\n# Calculate portfolio returns.\nbase_returns <- Return.portfolio(returns, extractWeights(opt_base))\ncolnames(base_returns) <- \"base\"\n```\n:::\n\n\n\n\nThe rebalancing and evaluation calculations are complete, so the allocation path can be inspected.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Chart the optimal weights.\nchart.Weights(opt_base)\n```\n\n::: {.cell-output-display}\n![Indexes, optimal weights.](06-asset-allocation_files/figure-html/fig-iow-1.png){#fig-iow width=672}\n:::\n:::\n\n\n\n\nThe chart shows the weight assigned to each asset through the rebalancing process. US bonds dominate the allocation in this run, which reflects the optimization objective and historical inputs. The annualized performance table reports the realized backtest comparison.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Merge benchmark and portfolio returns.\nret <- cbind(benchmark_returns, base_returns)\n# Annualized performance.\ntable.AnnualizedReturns(ret)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          benchmark   base\nAnnualized Return            0.0769 0.0765\nAnnualized Std Dev           0.1029 0.0432\nAnnualized Sharpe (Rf=0%)    0.7476 1.7710\n```\n\n\n:::\n:::\n\n\n\n\nThe optimized strategy produced a higher annualized return than the benchmark in this historical backtest. As a sample result, it is read together with the assumptions, constraints, and historical window used to generate it.\n\nInvestment mandates often impose limits on individual assets. Suppose the portfolio is not allowed to invest more than 40% in US bonds. This constraint can be incorporated directly before rerunning the rebalancing exercise.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a copy of the portfolio specification.\nbox_port_spec <- base_port_spec\n# Update the constraint.\nbox_port_spec <- add.constraint(portfolio = box_port_spec,\n                                type = \"box\", min = 0.05, max = 0.4,\n                                indexnum = 2)\n# Backtest.\nopt_box <- optimize.portfolio.rebalancing(R = returns,\n                                          optimize_method = \"ROI\",\n                                          portfolio = box_port_spec,\n                                          rebalance_on = \"quarters\",\n                                          training_period = 60,\n                                          rolling_window = 60)\n# Calculate portfolio returns.\nbox_returns <- Return.portfolio(returns, extractWeights(opt_box))\ncolnames(box_returns) <- \"box\"\n```\n:::\n\n\n\n\nAdditional constraints reduce the feasible set available to the optimizer. They may be necessary for mandate, liquidity, or risk-control reasons, although they can reduce performance under the selected objective.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Chart the optimal weights.\nchart.Weights(opt_box)\n```\n\n::: {.cell-output-display}\n![Indexes, optimal weights with box constraint.](06-asset-allocation_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n\n\nThe constraint forces the allocation to spread more weight across the remaining assets.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Merge box portfolio returns.\nret <- cbind(ret, box_returns)\n# Annualized performance.\ntable.AnnualizedReturns(ret)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          benchmark   base    box\nAnnualized Return            0.0769 0.0765 0.0753\nAnnualized Std Dev           0.1029 0.0432 0.0806\nAnnualized Sharpe (Rf=0%)    0.7476 1.7710 0.9344\n```\n\n\n:::\n:::\n\n\n\n\nIn this backtest, the box constraint reduces the annualized return relative to the unconstrained optimized strategy.\n\nPrivate firms often provide recurring portfolio analysis, monitoring, and rebalancing services. Software has reduced the cost of producing this kind of analysis, and fintech firms can now offer tools that were previously available only to institutions with specialized teams and infrastructure. Even so, functions such as <tt>`optimize.portfolio()`</tt> are professional modeling tools. They support the decision process, while the final portfolio decision still requires data validation, risk controls, costs, constraints, and suitability analysis.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncharts.PerformanceSummary(R = ret)\n```\n\n::: {.cell-output-display}\n![Indexes, portfolio performance.](06-asset-allocation_files/figure-html/fig-ipp-1.png){#fig-ipp width=672}\n:::\n:::\n\n\n\n\nPortfolio allocation produces weights, realized returns, and benchmark comparisons. The following chapter expresses the same portfolio problem in terms of possible losses. Value at Risk provides a compact way to ask how large a one-day portfolio loss could be under a chosen confidence level and a specific modeling assumption.\n",
    "supporting": [
      "06-asset-allocation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}