{
  "hash": "e985b371b010dcbac6e460504189971c",
  "result": {
    "engine": "knitr",
    "markdown": "# Value at Risk\n\n\n\n\n\n\n\n\n\nThe previous chapter focused on how to allocate capital across assets. The complementary risk-management task is to estimate how large a short-run market loss could be once a portfolio exists. Value at Risk (VaR) provides a compact answer by combining a time horizon, a confidence level, portfolio weights, and a loss distribution.\n\nIf $L$ is the portfolio loss over the chosen horizon and $\\alpha$ is the confidence level, VaR is the loss threshold such that losses are below or equal to it with probability $\\alpha$.\n\n$$\nP(L \\leq VaR_\\alpha)=\\alpha.\n$$\n\nEquivalently, when losses are sorted from low to high, VaR is the corresponding loss quantile.\n\n$$\nVaR_\\alpha = Q_\\alpha(L),\n$$\n\nwhere $Q_\\alpha(L)$ is the $\\alpha$ quantile of the loss distribution.\n\nThis chapter develops and extends the example called *Investment in Four Stock Indices* in Chapters 22 and 23 of @Hull. In this book, the example is used as an integrative market-risk exercise within the broader Financial Modeling with R path. It combines several ideas already used in the book: data preparation, currency adjustment, returns, portfolio weights, optimization, scenario generation, quantiles, and realized-outcome evaluation. The database used in this example <tt>`dataR.txt`</tt> is available [here](https://github.com/mlozanoqf/tutorial_if/blob/main/dataR.txt).\n\nThe working question is specific: calculate VaR for a portfolio using a one-day time horizon, a 99% confidence level, and 501 days of data, from Monday August 7, 2006 to Thursday September 25, 2008. The chapter follows four steps: express all index positions in US dollars, build one-day loss scenarios, estimate VaR with historical and model-building methods, and evaluate how portfolio weights change the loss distribution.\n\n## Prepare the data\n\nThe data set contains the index levels and exchange rates needed to express all positions from the perspective of a US investor.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- read.table(\"dataR.txt\", sep = \"\", header = TRUE)\n```\n:::\n\n\n\n\nThe first rows show the raw structure of the file before currency adjustment.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      DJIA FTSE100 USDGBP   CAC40 EURUSD   Nikkei YENUSD\n1 11219.38  5828.8 1.9098 4956.34 0.7776 15154.06 115.00\n2 11173.59  5818.1 1.9072 4967.95 0.7789 15464.66 115.08\n3 11076.18  5860.5 1.9086 5025.15 0.7762 15656.59 115.17\n4 11124.37  5823.4 1.8918 4976.64 0.7828 15630.91 115.41\n5 11088.02  5820.1 1.8970 4985.52 0.7833 15565.02 116.07\n6 11097.87  5870.9 1.8923 5046.93 0.7847 15857.11 116.45\n```\n\n\n:::\n:::\n\n\n\nThese are four international stock indices: Dow Jones Industrial Average (DJIA) in the US, the FTSE 100 in the UK, the CAC 40 in France, and the Nikkei 225 in Japan together with the corresponding exchange rates.\n\nBecause the example uses the perspective of a US investor, the values of the FTSE 100, CAC 40, and Nikkei 225 must be measured in US dollars. The *adjusted* US dollar equivalents of the stock indices follow these conversions.\n\n$FTSE_{USD}=FTSE_{GBP}\\times\\frac{USD}{GBP}$.\n\n$CAC_{USD}=\\frac{CAC_{EUR}}{\\frac{EUR}{USD}}$.\n\n$Nikkei_{USD}=\\frac{Nikkei_{JPY}}{\\frac{JPY}{USD}}$.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj <- df %>%\n  mutate(Day = c(0:501)) %>%\n  mutate(AFTSE100 = FTSE100 * USDGBP) %>%\n  mutate(ACAC40 = CAC40 / EURUSD) %>%\n  mutate(ANikkei = Nikkei / YENUSD)\n```\n:::\n\n\n\n\nThe following table shows the US dollar equivalent of the stock indices used for historical simulation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj %>%\n  select(Day, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  slice(1, 2, 3, 4, 500, 501)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Day     DJIA  AFTSE100   ACAC40  ANikkei\n1   0 11219.38 11131.842 6373.894 131.7744\n2   1 11173.59 11096.280 6378.162 134.3818\n3   2 11076.18 11185.350 6474.040 135.9433\n4   3 11124.37 11016.708 6357.486 135.4381\n5 499 10825.17  9438.580 6033.935 114.2604\n6 500 11022.06  9599.898 6200.396 112.8221\n```\n\n\n:::\n:::\n\n\n\nThe VaR estimation uses 501 observations because the sample counts from day zero through day 500. The *A* before the index name stands for *adjusted*. The figure shows the common dollar-based scale that will be used for scenario construction.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj %>%\n  mutate(ANikkei = ANikkei*100) %>%\n  mutate(obs = c(1:502)) %>%\n  select(obs, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  filter(obs < 502) %>%\n  gather(IX, Adj, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  mutate(IX = as.factor(IX)) %>%\n  ggplot(aes(x = obs, y = Adj, col = IX)) +\n  geom_line(size = 1) +\n  labs(y = \"US dollar equivalent of stock indices\", x = \"\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Adjusted index values, Nikkei = Nikkei $\\times$ 100.](07-value-at-risk_files/figure-html/fig-aivnn-1.png){#fig-aivnn width=672}\n:::\n:::\n\n\n\nThe time series starts on Monday August 7, 2006 and ends on Thursday September 25, 2008. These are 501 past daily observations. The plot below also shows the value of Friday September 26, 2008 as a dot. This is observation 502, stored as <tt>`tomorrow`</tt>. Observation 502 is excluded from the VaR estimation because it represents the future value being evaluated.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntomorrow <- df.Adj %>%\n  mutate(ANikkei = ANikkei*100) %>%\n  mutate(obs = c(1:502)) %>%\n  select(obs, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  filter(obs == 502) %>%\n  gather(IX, Adj, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  mutate(IX = as.factor(IX))\n\ndf.Adj %>%\n  mutate(ANikkei = ANikkei*100) %>%\n  mutate(obs = c(1:502)) %>%\n  select(obs, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  filter(obs > 400) %>%\n  filter(obs < 502) %>%\n  gather(IX, Adj, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  mutate(IX = as.factor(IX)) %>%\n  ggplot(aes(x = obs, y = Adj, col = IX)) +\n  geom_line(size = 1) +\n  geom_point(aes(obs, Adj), size = 2, alpha = 0.4, data = tomorrow) +\n  labs(y = \"US dollar equivalent of stock indices\", x = \"\") +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Adjusted index values, Nikkei = Nikkei $\\times$ 100, zoom view.](07-value-at-risk_files/figure-html/fig-aivnnzv-1.png){#fig-aivnnzv width=672}\n:::\n:::\n\n\n\nThe stock index values for Friday September 26, 2008 provide the realized values used later for evaluation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntomorrow\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  obs       IX       Adj\n1 502     DJIA 11143.130\n2 502 AFTSE100  9379.123\n3 502   ACAC40  6081.478\n4 502  ANikkei 11216.788\n```\n\n\n:::\n:::\n\n\n\n\n## Historical simulation\n\nThe historical simulation method requires scenarios for the possible stock-index values on Friday September 26, 2008. The calculation constructs 500 scenarios from 501 past observations. The method assumes that the index value on Friday September 26, 2008 can be represented by the value observed on Thursday September 25, 2008 multiplied by one historical percentage change. The first percentage change goes from Monday August 7, 2006 to Tuesday August 8, 2006. The second goes from Tuesday August 8, 2006 to Wednesday August 9, 2006, and the sequence continues through the historical window.\n\nFor index $j$ and historical scenario $k$, the generated value is defined by applying a past daily relative change to the last observed value.\n\n$$\nS_{j,k}^{scenario}=S_{j,T}\\frac{S_{j,k}}{S_{j,k-1}},\n\\qquad k=1,\\dots,500.\n$$\n\nThe portfolio value and loss for scenario $k$ combine those scenario index levels with the dollar allocations.\n\n$$\np_k=\\sum_{j=1}^{4} a_j \\frac{S_{j,k}^{scenario}}{S_{j,T}},\n\\qquad\nl_k=10{,}000-p_k,\n$$\n\nwhere $a_j$ is the dollar allocation to index $j$ in thousands of US dollars.\n\nThe adjusted values provide the reference levels for the scenario ratios.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj %>%\n  select(Day, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  slice(1, 2, 3, 4, 500, 501)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Day     DJIA  AFTSE100   ACAC40  ANikkei\n1   0 11219.38 11131.842 6373.894 131.7744\n2   1 11173.59 11096.280 6378.162 134.3818\n3   2 11076.18 11185.350 6474.040 135.9433\n4   3 11124.37 11016.708 6357.486 135.4381\n5 499 10825.17  9438.580 6033.935 114.2604\n6 500 11022.06  9599.898 6200.396 112.8221\n```\n\n\n:::\n:::\n\n\n\nThe first three Dow Jones scenarios $SDJIA$ illustrate the calculation.\n\n$SDJIA_1 = 11022.06 \\times \\frac{11173.59}{11219.38} \\rightarrow SDJIA_1 = 10977.08$.\n\n$SDJIA_2 = 11022.06 \\times \\frac{11076.18}{11173.59} \\rightarrow SDJIA_2 = 10925.97$\n\n$SDJIA_3 = 11022.06 \\times \\frac{11124.37}{11076.18} \\rightarrow SDJIA_3 = 11070.01$\n\nThe first three possible Dow Jones values according to the historical approach for September 26, 2008 are 10977.08, 10925.97, and 11070.01. The actual value, 11143.130, is reserved for evaluation, so it does not enter the VaR estimate.\n\nThe generated scenario table gives the first simulated values and the last historical rows in the scenario window.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj.S <- df.Adj %>%\n  mutate(obs = c(0:501)) %>%\n  mutate(SDJIA = DJIA[501] * (DJIA/lag(DJIA))) %>%\n  mutate(SFTSE100 = AFTSE100[501] * (AFTSE100/lag(AFTSE100))) %>%\n  mutate(SCAC40 = ACAC40[501] * (ACAC40/lag(ACAC40))) %>%\n  mutate(SNikkei = ANikkei[501] * (ANikkei/lag(ANikkei)))\n\ndf.Adj.S %>%\n  select(obs, SDJIA, SFTSE100, SCAC40, SNikkei) %>%\n  slice(2, 3, 4, 500, 501)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  obs    SDJIA SFTSE100   SCAC40  SNikkei\n1   1 10977.08 9569.230 6204.547 115.0545\n2   2 10925.97 9676.957 6293.603 114.1331\n3   3 11070.01 9455.160 6088.768 112.4028\n4 499 10831.43 9383.488 6051.936 113.8498\n5 500 11222.53 9763.974 6371.450 111.4019\n```\n\n\n:::\n:::\n\n\n\n\nThe violin plot shows the generated scenarios together with the actual values for September 26, 2008. The dot is useful for evaluation because it shows where the realized next-day value landed relative to the historical scenario range.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlevels(tomorrow$IX) <- list(SCAC40 = \"ACAC40\", SDJIA = \"DJIA\",\n                         SFTSE100 = \"AFTSE100\", SNikkei = \"ANikkei\")\n\ndf.Adj.S %>%\n  mutate(SNikkei = SNikkei*100) %>%\n  mutate(obs = c(1:502)) %>%\n  select(obs, SDJIA, SFTSE100, SCAC40, SNikkei) %>%\n  filter(obs < 502) %>%\n  gather(IX, S, SDJIA, SFTSE100, SCAC40, SNikkei) %>%\n  mutate(IX = as.factor(IX)) %>%\n  ggplot(aes(x = IX, fill = IX)) +\n  geom_violin(aes(IX, S), draw_quantiles = 0.5) +\n  geom_point(aes(IX, Adj), size = 3,\n             data = tomorrow, show.legend = FALSE) +\n  labs(y = \"Scenarios generated for September 26, 2008\", x = \"\") +\n  theme(legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](07-value-at-risk_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\nAccording to the example, an investor in the United States owns, on September 25, 2008, a portfolio worth \\$10 million consisting of 40% in the DJIA, 30% in the FTSE, 10% in the CAC, and 20% in the Nikkei. The calculations below express portfolio values and losses in thousands of US dollars. The corresponding 500 scenarios for the possible portfolio value $p$ on September 26, 2008 use the same allocation formula.\n\n$p_1 = 4000 \\frac{SDJIA_1}{DJIA_{sept.25.2008}} + 3000 \\frac{SFTSE_1}{FTSE_{sept.25.2008}} + 1000 \\frac{SCAC_1}{CAC_{sept.25.2008}} + 2000  \\frac{SNikkei_1}{Nikkei_{sept.25.2008}}$,\n\n$p_1 = 4000 \\frac{10977.08}{11022.06} + 3000 \\frac{9569.230}{9599.898} + 1000 \\frac{6204.547}{6200.396} + 2000  \\frac{115.0545}{112.8221}$,\n\n$p_1 = 10{,}014.334$ thousand dollars.\n\n$p_2 = 4000 \\frac{SDJIA_2}{DJIA_{sept.25.2008}} + 3000 \\frac{SFTSE_2}{FTSE_{sept.25.2008}} + 1000 \\frac{SCAC_2}{CAC_{sept.25.2008}} + 2000  \\frac{SNikkei_2}{Nikkei_{sept.25.2008}}$,\n\n$p_2 = 4000 \\frac{10925.97}{11022.06} + 3000 \\frac{9676.957}{9599.898} + 1000 \\frac{6293.603}{6200.396} + 2000  \\frac{114.1331}{112.8221}$,\n\n$p_2 = 10{,}027.481$ thousand dollars.\n\nThe same scenario formula is applied to the remaining historical changes.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj.S <- df.Adj.S %>%\n  mutate(p = (4000 * SDJIA / DJIA[501]) + # Investment portfolio value\n             (3000 * SFTSE100 / AFTSE100[501]) +\n             (1000 * SCAC40 / ACAC40[501]) +\n             (2000 * SNikkei / ANikkei[501])) %>%\n  mutate(l = 10000 - p) # Losses l\n\ndf.Adj.S %>%\n  select(obs, SDJIA, SFTSE100, SCAC40, SNikkei, p, l) %>%\n  slice(2, 3, 4, 500, 501)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  obs    SDJIA SFTSE100   SCAC40  SNikkei         p          l\n1   1 10977.08 9569.230 6204.547 115.0545 10014.334  -14.33385\n2   2 10925.97 9676.957 6293.603 114.1331 10027.481  -27.48131\n3   3 11070.01 9455.160 6088.768 112.4028  9946.736   53.26406\n4 499 10831.43 9383.488 6051.936 113.8498  9857.465  142.53549\n5 500 11222.53 9763.974 6371.450 111.4019 10126.439 -126.43897\n```\n\n\n:::\n:::\n\n\n\n\nThe variable $l$ represents portfolio losses, with $l = 10{,}000 - p$ in thousands of US dollars. A negative loss represents a portfolio gain. The values reproduce the numerical structure of the historical-simulation example in @Hull.\n\nThe scenario-loss plot preserves the historical ordering of the 500 daily changes. Positive bars are losses and negative bars are gains, so the picture gives a quick sense of the downside tail before selecting a VaR threshold.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nl <- df.Adj.S %>%\n  mutate(obs = c(0:501)) %>%\n  select(obs, l) %>%\n  filter(obs > 0 & obs < 501) %>%\n  select(l) %>%\n  unlist()\n\nl.tomorrow <- df.Adj.S %>%\n  mutate(obs = c(0:501)) %>%\n  select(obs, l) %>%\n  filter(obs == 501) %>%\n  select(l) %>%\n  unlist()\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(l, type = \"h\", lwd = 2,\n     xlab = \"500 scenarios (sorted by historical date)\",\n     ylab = \"Portfolio gains (-) and losses (+)\",\n     col = ifelse(l < 0, \"blue\", \"red\"))\npoints(501, l.tomorrow, pch = 19, cex = 2)\nabline(0, 0)\nabline(v = 0)\nlines(seq(0, max(l, na.rm = TRUE), length.out = 500), lty = 2)\nlines(seq(0, min(l, na.rm = TRUE), length.out = 500), lty = 2)\nabline(h = 253.385, lwd = 2, col = \"green\")\nlegend(\"bottomleft\", legend = c(\"Gains\", \"Losses\", \"Historical VaR: 253.385\"),\n       col = c(\"blue\", \"red\", \"green\"), lty = 1, bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Scenario losses for the September 25, 2008 portfolio.](07-value-at-risk_files/figure-html/fig-tis22witwtchtmpt-1.png){#fig-tis22witwtchtmpt width=672}\n:::\n:::\n\n\n\n\nThe histogram compresses the same scenarios into a distribution of losses. Most scenarios are clustered around moderate gains or losses, while VaR is read from the right tail.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(l, 15, xlab = \"Portfolio losses (+) and gains (-)\", main = NULL)\npoints(l.tomorrow, 1, pch = 19, cex = 2)\nabline(v = 253.385, col = \"red\", lwd = 2)\nlegend(\"topleft\", legend = c(\"Historical VaR: 253.385\"), col = \"red\",\n       bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Histogram of scenario losses between September 25 and 26, 2008.](07-value-at-risk_files/figure-html/fig-holftscbs2a22ah-1.png){#fig-holftscbs2a22ah width=672}\n:::\n:::\n\n\n\n\nThe point marks the realized loss, and the red line marks the historical VaR estimate. The density plot smooths the same information and makes the shape of the empirical loss distribution easier to compare with the normal model used later.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndensi <- density(l, na.rm = TRUE)\nplot(densi, main = \"\", xlab = \"Portfolio losses (+) and gains (-)\")\npolygon(densi, col = \"grey\", border = \"black\")\npoints(l.tomorrow, 0, pch = 19, cex = 2)\nabline(v = 253.385, col = \"red\", lwd = 2)\nlegend(\"topleft\", legend = c(\"Historical VaR: 253.385\"), col = \"red\",\n       bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Density plot of scenario losses between September 25 and 26, 2008.](07-value-at-risk_files/figure-html/fig-holftscbs2a22adp-1.png){#fig-holftscbs2a22adp width=672}\n:::\n:::\n\n\n\n\nThe same loss distribution can be displayed with axes that match the original textbook presentation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(l, 15, axes = F, lty = \"blank\", col = \"grey\", main = \"\",\n     xlab = \"Portfolio losses (+) and gains (-)\")\naxis(1, pos = 0)\naxis(2, pos = 0, las = 1)\n```\n\n::: {.cell-output-display}\n![Historical loss distribution with Hull-style axes.](07-value-at-risk_files/figure-html/fig-f2holftscbs2a22-1.png){#fig-f2holftscbs2a22 width=672}\n:::\n:::\n\n\n\n\nRanking the 500 scenario losses from highest to lowest makes the tail selection explicit. At the 99% confidence level with 500 scenarios, 1% of the sample corresponds to five observations. The fifth-largest loss is therefore the discrete historical VaR used in the textbook example.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTable22.4 <- data.frame(scenario.number = order(l, decreasing = TRUE),\n                        `loss in positive values` =\n                          l[order(l, decreasing = TRUE)])\nhead(Table22.4, 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     scenario.number loss.in.positive.values\nl494             494                477.8410\nl339             339                345.4351\nl349             349                282.2038\nl329             329                277.0413\nl487             487                253.3850\nl227             227                217.9740\nl131             131                202.2555\nl238             238                201.3892\nl473             473                191.2691\nl306             306                191.0497\nl477             477                185.1269\nl495             495                184.4496\nl376             376                182.7072\nl237             237                180.1048\nl365             365                172.2237\n```\n\n\n:::\n:::\n\n\n\n\nThe last values show the largest gains in the ranked loss table.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail(Table22.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     scenario.number loss.in.positive.values\nl395             395               -224.5146\nl489             489               -284.9247\nl341             341               -307.9301\nl377             377               -316.4893\nl379             379               -333.0218\nl497             497               -555.7954\n```\n\n\n:::\n:::\n\n\n\n\nOne of the highest gains happens in scenario 497, almost at the end of the historical window. The largest gains remain outside the VaR tail calculation and still help show that the historical window contains both downside and upside shocks.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVaR.hist <- 253.3850\nResults <- data.frame(VaR.method = \"Historical simulation, original weights\",\n                      VaR = VaR.hist)\nResults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                               VaR.method     VaR\n1 Historical simulation, original weights 253.385\n```\n\n\n:::\n:::\n\n\n\n\nThe original weights are 40% in the DJIA, 30% in the FTSE, 10% in the CAC, and 20% in the Nikkei. They are treated as a benchmark allocation because they are assigned exogenously in the example. The ranked-loss barplot makes the 1% tail visible and separates the VaR estimate from the realized next-day outcome.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(l[order(l, decreasing = TRUE)],\n        names.arg = order(l, decreasing = TRUE), ylim = c(0, 500),\n        xlim = c(0, 20), las = 2, cex.names = 1, ylab = \"Portfolio loss ($000s)\",\n        col = \"red\", xlab = \"Scenario number (ranked)\")\nabline(h = 253.385, lwd = 3)\nabline(h = 0, lwd = 3)\nabline(h = l.tomorrow, lwd = 3, col = \"green\")\nlegend(\"topright\", legend = c(\"Historical VaR: 253.385\",\n       \"Realized loss\"), col = c(\"black\", \"green\"),\n       bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![Ranked scenario losses with 1 percent historical VaR and realized loss.](07-value-at-risk_files/figure-html/fig-eot2iagvha1p2wrhig-1.png){#fig-eot2iagvha1p2wrhig width=672}\n:::\n:::\n\n\n\n\nThe top 1% can also be explored with the <tt>`quantile()`</tt> function. R's default quantile estimator interpolates between order statistics, so its 99% value differs from Hull's fifth-worst-scenario historical VaR. The difference comes from a numerical convention for estimating sample quantiles.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVaR.hist.quantile <- quantile(l, 0.99)\nVaR.hist.quantile\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     99% \n218.3281 \n```\n\n\n:::\n:::\n\n\n\n\nHull's discrete historical VaR is reproduced by taking the fifth largest loss directly.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVaR.hist.discrete <- sort(l, decreasing = TRUE)[5]\nVaR.hist.discrete\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   l487 \n253.385 \n```\n\n\n:::\n:::\n\n\n\n\nThe default <tt>`quantile()`</tt> function at the 99% level gives the interpolated estimate.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(l, 0.99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     99% \n218.3281 \n```\n\n\n:::\n:::\n\n\n\nThe quantile curve shows how the VaR estimate changes with the confidence level.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(seq(from = 0.902, to = 1, by = 0.002),\n     quantile(l, seq(from = 0.902, to = 1, by = 0.002)), cex = 1.5,\n     xlab = \"Confidence level (vertical line at 99%)\",\n     ylab = \"Portfolio VaR\")\nabline(v = 0.99, lty = 2, lwd = 2)\nabline(h = quantile(l, 0.99), col = \"blue\", lty = 2, lwd = 2)\nabline(h = Table22.4[5, 2], col = \"red\", lty = 2, lwd = 2)\nlegend(\"topleft\", legend = c(\"99% level\", \"Historical VaR: 253.385\",\n                             \"99% quantile VaR: 218.3281\"),\n       col = c(\"black\", \"red\", \"blue\"), lty = 2, bg = \"white\", lwd = 2)\n```\n\n::: {.cell-output-display}\n![VaR estimates across confidence levels.](07-value-at-risk_files/figure-html/fig-aqa-1.png){#fig-aqa width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nci <- seq(0, 1, length.out = 500)\nind <- c(1:500)\ntail(data.frame(\"quantile function\" = quantile(l, ci),\n                \"scenario number\" = order(l),\n                \"sort losses\" = sort(l)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             quantile.function scenario.number sort.losses\n98.9979960%           217.9740             227    217.9740\n99.1983968%           253.3850             487    253.3850\n99.3987976%           277.0413             329    277.0413\n99.5991984%           282.2038             349    282.2038\n99.7995992%           345.4351             339    345.4351\n100.0000000%          477.8410             494    477.8410\n```\n\n\n:::\n:::\n\n\n\n\nThe results table stores the historical VaR estimates.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results %>%\n  add_row(VaR.method =\n            \"Historical approximate quantile(), original weights\",\n          VaR = VaR.hist.quantile) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                           VaR.method      VaR\n1 Historical approximate quantile(), original weights 218.3281\n2             Historical simulation, original weights 253.3850\n```\n\n\n:::\n:::\n\n\n\n\n## Model building approach\n\nThe model-building approach assumes normality for portfolio losses. The historical loss distribution can deviate from that assumption, especially in the tails. Its main advantage is simplicity: once the covariance matrix and portfolio weights are defined, VaR follows from the normal quantile. The method is also useful as a benchmark against historical simulation because both methods use the same portfolio and horizon.\n\nThe adjusted indices are first transformed into simple returns.\n\n$$\nR_{j,t}=\\frac{S_{j,t}-S_{j,t-1}}{S_{j,t-1}}.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nR <- df.Adj %>%\n  select(Day, DJIA, AFTSE100, ACAC40, ANikkei) %>%\n  mutate(RDJIA = (DJIA-lag(DJIA))/lag(DJIA)) %>%\n  mutate(RFTSE100 = (AFTSE100-lag(AFTSE100))/lag(AFTSE100)) %>%\n  mutate(RCAC40 = (ACAC40-lag(ACAC40))/lag(ACAC40)) %>%\n  mutate(Nikkei = (ANikkei-lag(ANikkei))/lag(ANikkei)) %>%\n  select(RDJIA, RFTSE100, RCAC40, Nikkei) %>%\n  slice(-1)\n\nR.tomorrow <- R %>%\n  slice(501)\n\nR <- R %>%\n  slice(-501)\n```\n:::\n\n\n\n\nThe correlation matrix on September 25, 2008 is calculated by giving equal weight to the last 500 daily returns.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRcor <- cor(R)\nTable23.5 <- Rcor\nTable23.5\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               RDJIA  RFTSE100    RCAC40      Nikkei\nRDJIA     1.00000000 0.4891059 0.4957096 -0.06189921\nRFTSE100  0.48910594 1.0000000 0.9181083  0.20094221\nRCAC40    0.49570963 0.9181083 1.0000000  0.21095096\nNikkei   -0.06189921 0.2009422 0.2109510  1.00000000\n```\n\n\n:::\n:::\n\n\n\n\nThe covariance matrix on September 25, 2008 is calculated by giving equal weight to the last 500 daily returns.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRcov <- cov(R)\nTable23.6 <- Rcov\nTable23.6\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 RDJIA     RFTSE100       RCAC40        Nikkei\nRDJIA     1.229524e-04 7.696591e-05 7.682514e-05 -9.493488e-06\nRFTSE100  7.696591e-05 2.013973e-04 1.821076e-04  3.944302e-05\nRCAC40    7.682514e-05 1.821076e-04 1.953506e-04  4.078130e-05\nNikkei   -9.493488e-06 3.944302e-05 4.078130e-05  1.913129e-04\n```\n\n\n:::\n:::\n\n\n\n\nThis covariance matrix is close to the one in @Hull. Minor differences arise because the calculations here do not use rounded intermediate values.\n\nWith dollar allocations $\\alpha=(4000,3000,1000,2000)'$, the variance of portfolio losses in thousands of dollars follows the quadratic portfolio-risk expression.\n\n$$\n\\sigma_p^2=\\alpha'\\Sigma\\alpha.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRsd <- apply(R, 2, sd)\nalpha <- c(4000, 3000, 1000, 2000)\n(Pvar <- t(alpha) %*% Rcov %*% alpha) # equation in page 506 (chapter 22)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 8779.392\n```\n\n\n:::\n:::\n\n\n\n\nHull reports 8,761.833 for this variance. The value calculated here is slightly different because the code keeps more intermediate precision. Taking the square root gives the portfolio standard deviation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Psd <- Pvar^0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 93.69841\n```\n\n\n:::\n:::\n\n\n\n\nThe one-day 99% VaR under the normal model multiplies the portfolio standard deviation by the 99% normal quantile.\n\n$$\nVaR_{0.99}=z_{0.99}\\sigma_p.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(VaR.ew <- qnorm(0.99, 0, 1) * Psd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 217.9751\n```\n\n\n:::\n:::\n\n\n\n\nHull reports \\$217,757. In the units used here, that is 217.757 in thousands of dollars, compared with 253.385 from the historical simulation approach. The model-building estimate is lower in this case because the normal approximation smooths the empirical tail.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method =\n            \"Model building equal observation weights, original weights\",\n          VaR = VaR.ew) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                  VaR.method      VaR\n1        Historical approximate quantile(), original weights 218.3281\n2                    Historical simulation, original weights 253.3850\n3 Model building equal observation weights, original weights 217.9751\n```\n\n\n:::\n:::\n\n\n\n\nThe equal-observation-weight covariance estimate can be compared with the exponentially weighted moving average method (EWMA).\n\nWith decay parameter $\\lambda$ and demeaned return vector $u_t=r_t-\\bar r$, the EWMA covariance update gives more weight to recent squared return innovations.\n\n$$\n\\Sigma_t=\\lambda\\Sigma_{t-1}+(1-\\lambda)u_{t-1}u_{t-1}'.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model building example -- EWMA\ncovEWMA <-\n  function(factors, lambda = 0.96, return.cor = FALSE) {\n    factor.names  = colnames(factors)\n    t.factor      = nrow(factors)\n    k.factor      = ncol(factors)\n    factors       = as.matrix(factors)\n    t.names       = rownames(factors)\n    factor.means  = colMeans(factors)\n\n    cov.f.ewma = array(,c(t.factor, k.factor, k.factor))\n    cov.f = var(factors)  # unconditional variance as EWMA at time = 0\n    FF = (factors[1, ] - factor.means) %*% t(factors[1,] - factor.means)\n    cov.f.ewma[1,,] = (1 - lambda) * FF  + lambda * cov.f\n    for (i in 2:t.factor) {\n    FF = (factors[i, ] - factor.means) %*% t(factors[i, ] - factor.means)\n    cov.f.ewma[i,,] = (1 - lambda) * FF  + lambda * cov.f.ewma[(i-1),,]\n    }\n    dimnames(cov.f.ewma) = list(t.names, factor.names, factor.names)\n\n    if(return.cor) {\n      cor.f.ewma = cov.f.ewma\n      for (i in 1:dim(cor.f.ewma)[1]) {\n        cor.f.ewma[i, , ] = cov2cor(cov.f.ewma[i, ,])\n      }\n      return(cor.f.ewma)\n    } else {\n      return(cov.f.ewma)\n    }\n  }\n```\n:::\n\n\n\n\nThe covariance matrix on September 25, 2008 is also calculated using the EWMA method with $\\lambda=0.94$. EWMA gives more weight to recent observations, so it responds more strongly when volatility rises near the end of the sample.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nRdf <- as.data.frame(R)\nC <- covEWMA(Rdf, lambda = 0.94)[500,,]\nTable23.7 <- C\nTable23.7\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 RDJIA     RFTSE100       RCAC40        Nikkei\nRDJIA     0.0004801472 0.0004300030 0.0004257243 -0.0000398876\nRFTSE100  0.0004300030 0.0010311334 0.0009630006  0.0002090981\nRCAC40    0.0004257243 0.0009630006 0.0009535706  0.0001681154\nNikkei   -0.0000398876 0.0002090981 0.0001681154  0.0002534478\n```\n\n\n:::\n:::\n\n\n\n\nThe variance of portfolio losses again follows the quadratic form $\\alpha'\\Sigma\\alpha$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Pvar_EWMA <- t(alpha) %*% C %*% alpha)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 40977.22\n```\n\n\n:::\n:::\n\n\n\n\nHull reports 40,995.765 for this value. Taking the square root gives the EWMA portfolio standard deviation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Psd_EWMA <- Pvar_EWMA^0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 202.4283\n```\n\n\n:::\n:::\n\n\n\n\nHull reports 202.474 for this value. The one-day 99% VaR is therefore calculated from the same normal-quantile expression used above.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(VaR.ewma <- qnorm(0.99, 0, 1) * Psd_EWMA)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 470.9187\n```\n\n\n:::\n:::\n\n\n\n\nHull reports \\$471,025, or 471.025 in thousands of dollars. This value is more than twice the VaR estimated with equal observation weights, which reflects the higher volatility near the end of the sample.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method = \"Model building EWMA, original weights\",\n          VaR = VaR.ewma) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                  VaR.method      VaR\n1        Historical approximate quantile(), original weights 218.3281\n2                    Historical simulation, original weights 253.3850\n3                      Model building EWMA, original weights 470.9187\n4 Model building equal observation weights, original weights 217.9751\n```\n\n\n:::\n:::\n\n\n\n\nThe table compares daily volatilities under equal observation weights and EWMA.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTable23.8 <- data.frame(Rsd * 100, diag(C)^0.5 * 100)\ncolnames(Table23.8) <- c(\"Equal obs. weights\", \"EWMA\")\nrownames(Table23.8) <- c(\"DJIA\", \"FTSE 100\", \"CAC 40\", \"Nikkei 225\")\nt(Table23.8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       DJIA FTSE 100   CAC 40 Nikkei 225\nEqual obs. weights 1.108839 1.419145 1.397679   1.383159\nEWMA               2.191226 3.211127 3.087994   1.592004\n```\n\n\n:::\n:::\n\n\n\n\nThe estimated daily standard deviations are much higher when EWMA is used than when data receive equal observation weights. This happens because volatilities were much higher during the period immediately preceding September 25, 2008, than during the rest of the 500 days covered by the data.\n\n\n\n\n\n\n\n\n\n## Optimal allocation\n\nVaR depends on the loss distribution, and the loss distribution depends on the weights. The current benchmark portfolio weights provide the reference allocation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW_benchmark <- alpha / 10000\nW_benchmarkt <- data.frame(W_benchmark)\nrownames(W_benchmarkt) <- c(\"DJIA\", \"FTSE 100\", \"CAC 40\", \"Nikkei 225\")\nt(W_benchmarkt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            DJIA FTSE 100 CAC 40 Nikkei 225\nW_benchmark  0.4      0.3    0.1        0.2\n```\n\n\n:::\n:::\n\n\n\n\nThe following calculation estimates three comparison portfolios: the benchmark allocation, a minimum-variance allocation, and an allocation that targets the expected return of the CAC 40. Returns are expressed in percent for the mean-variance exercise; the later VaR calculations continue to use dollar allocations and the unscaled covariance matrices.\n\nThe minimum-variance allocation solves a constrained variance minimization problem.\n\n$$\n\\min_w w'\\Sigma w\n\\quad \\text{subject to} \\quad \\mathbf{1}'w=1.\n$$\n\nThe CAC 40 target-return allocation adds a return constraint to the same variance minimization problem. This analytical Markowitz calculation is unconstrained, so a target-return solution can include negative weights. In portfolio language, a negative weight is a short position.\n\n$$\n\\min_w w'\\Sigma w\n\\quad \\text{subject to} \\quad \\mathbf{1}'w=1,\\quad w'\\mu=\\mu_{CAC40}.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nR <- R * 100\nR.tomorrow <- R.tomorrow * 100\nstocks<- c(\"DJIA\", \"FTSE100\", \"CAC40\", \"Nikkei\")\nsigma <- var(R)\nsd <- diag(sigma)^0.5\nE <- colMeans(R)\nE.tomorrow <- colMeans(R.tomorrow)\nones <- abs(E / E)\na <- c(t(ones) %*% solve(sigma) %*% ones)\nb <- c(t(ones) %*% solve(sigma) %*% E)\nc <- c(t(E) %*% solve(sigma) %*% E)\nd <- c(a * c - (b^2))\ng <- c(solve(sigma) %*% (c * ones - b * E) / d)\nh <- c(solve(sigma) %*% (a * E - b * ones) / d)\nER <- seq(from = -0.3, to = 0.3, by = 0.0001)\nS <- ER\nW <- matrix(0, nrow = length(ER), ncol = length(stocks))\nfor(i in 1:length(ER)){\n  W[i,] <- g + h * ER[i]\n  ER[i] <- W[i,] %*% E\n  S[i] <- (t(W[i,]) %*% sigma %*% W[i, ])^0.5\n  }\nW_min <- (solve(sigma) %*% ones) / a\nR_min <- c(t(W_min) %*% E)\nR_min.realized <- c(t(W_min) %*% E.tomorrow)\nS_min <- c(t(W_min) %*% sigma %*% W_min)^0.5\n# Allocation targeting the CAC40 expected return with lower estimated variance.\nW.cac40 <- g + h * E[3]\nR_cac40 <- c(t(W.cac40) %*% E)\nR_cac40.realized <- c(t(W.cac40) %*% E.tomorrow)\nS_cac40 <- c(t(W.cac40) %*% sigma %*% W.cac40)^0.5\nR_benchmark.realized = c(t(W_benchmark) %*% E.tomorrow)\n```\n:::\n\n\n\n\nThere are now four portfolio-weight alternatives, two of which are optimized. The risk-management comparison asks whether optimized weights reduce VaR under the same data and horizon.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW <- data.frame(W_benchmark, W_min, W.cac40, c(0.25, 0.25, 0.25, 0.25))\nrownames(W) <- c(\"DJIA\", \"FTSE 100\", \"CAC 40\", \"Nikkei 225\")\ncolnames(W) <- c(\"Benchmark weights\",\n                 \"minimum variance\", \"CAC40 target return\",\n                 \"equal 1/N\")\nt(W)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         DJIA    FTSE 100     CAC 40 Nikkei 225\nBenchmark weights   0.4000000  0.30000000 0.10000000  0.2000000\nminimum variance    0.5592378  0.03793305 0.02279301  0.3800361\nCAC40 target return 0.6075003 -0.40341894 0.45978629  0.3361323\nequal 1/N           0.2500000  0.25000000 0.25000000  0.2500000\n```\n\n\n:::\n:::\n\n\n\n\nThe portfolio weights remain constant in this worked example. A dynamic implementation could rebalance weights as new data arrive. The following resource shows the time evolution of minimum-variance weights when five US industry portfolios are used as investment assets.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/paH1-bDPsA4\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/paH1-bDPsA4\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nA similar exercise with 10 US industry-sorted portfolios extends the same idea.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/DyjQbKm-NdE\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/DyjQbKm-NdE\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nThe comparison now returns to the four-index portfolio.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW_benchmark <- alpha / 10000\nR_benchmark <- c(t(W_benchmark) %*% E)\nS_benchmark <- c(t(W_benchmark) %*% sigma %*% W_benchmark)^0.5\n\nplot(S, ER, type = \"l\", lwd = 3, xlim = c(0.7, 1.6),\n     ylim = c(-0.022, 0.005),\n     ylab = \"Expected return\", xlab = \"Standard deviation\")\npoints(diag(sigma)^0.5, E)\nabline(0, R_benchmark / S_benchmark, lty = 3, col = \"blue\")\nabline(0, R_min / S_min, lty = 3, col = \"red\")\npoints(S_min, R_min, col = \"red\", pch = 19, cex = 2)\nabline(0, 0, lty = 3)\ntext(S_min, R_min, \"Minimum\n     variance\", pos = 2, cex = 0.8)\ntext(sd, E, stocks, adj = -0.5, cex = 0.8)\npoints(S_benchmark, R_benchmark, col = \"blue\", pch = 19, cex = 2)\ntext(S_benchmark, R_benchmark, \"Benchmark\n     allocation\", adj = -0.3, cex = 0.8, pos = 1)\nlegend(\"bottomleft\",\n       legend = c(\"DJ=0.4,   FTSE=0.3,     CAC=0.1,     Nikkei=0.2\",\n                            \"DJ=0.56, FTSE=0.038, CAC=0.022, Nikkei=0.38\"),\n       col = c(\"blue\", \"red\"), pch = 19, bg = \"white\", cex = 1)\n```\n\n::: {.cell-output-display}\n![Original allocation and minimum-variance alternative in mean-variance space.](07-value-at-risk_files/figure-html/fig-haistroiabaawner-1.png){#fig-haistroiabaawner width=672}\n:::\n:::\n\n\n\n\nThe figure suggests that the minimum-variance alternative reduces estimated portfolio risk relative to the original allocation. In the estimated mean-variance space, the minimum-variance portfolio has higher expected return and lower estimated risk. The statement is in-sample and based on estimated means and covariances. The realized outcome can then be evaluated with the actual returns for September 26, 2008.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(R_min.realized <- c(t(W_min) %*% E.tomorrow))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2629549\n```\n\n\n:::\n\n```{.r .cell-code}\n(R_benchmark.realized = c(t(W_benchmark) %*% E.tomorrow))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5583249\n```\n\n\n:::\n:::\n\n\n\n\nThe comparison suggests that the original allocation would have produced a realized return of -0.5583249% on Friday September 26, 2008. The minimum-variance allocation would have produced a portfolio gain of 0.2629549%. The example shows why portfolio weights matter before VaR is computed: the loss distribution changes when the allocation changes.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nW_benchmark <- alpha / 10000\nR_benchmark <- c(t(W_benchmark) %*% E)\nS_benchmark <- c(t(W_benchmark) %*% sigma %*% W_benchmark)^0.5\n\nW_1N <- c(0.25,0.25,0.25,0.25)\nR_1N <- c(t(W_1N) %*% E)\nS_1N <- c(t(W_1N) %*% sigma %*% W_1N)^0.5\n\nplot(S, ER, type = \"l\", lwd = 3, xlim = c(0.7, 1.6),\n     ylim = c(-0.022, 0.005),\n     ylab = \"Expected return\", xlab = \"Standard deviation\")\npoints(diag(sigma)^0.5, E)\nabline(0, R_benchmark / S_benchmark, lty = 3, col = \"blue\")\nabline(0, R_min / S_min, lty = 3, col = \"red\")\nabline(0, R_1N / S_1N, lty = 3, col = \"purple\")\npoints(S_min, R_min, col = \"red\", pch = 19, cex = 2)\npoints(S_1N, R_1N, col = \"purple\", pch = 19, cex = 2)\nabline(0, 0, lty = 3)\ntext(S_min, R_min, \"Minimum\n     variance\", pos = 2, cex = 0.8)\ntext(sd, E, stocks, adj = -0.5, cex = 0.8)\npoints(S_benchmark, R_benchmark, col = \"blue\", pch = 19, cex = 2)\ntext(S_benchmark, R_benchmark, \"Benchmark\n     allocation\", adj = -0.3, cex = 0.8, pos = 1)\ntext(S_1N, R_1N, \"1/N\", adj = -0.3, cex = 0.8, pos = 3)\nlegend(\"bottomleft\",\n       legend =\n         c(\"Bench.: DJ=0.4,   FTSE=0.3,     CAC=0.1,     Nikkei=0.2\",\n\"Minvar: DJ=0.56, FTSE=0.038, CAC=0.022, Nikkei=0.38\",\n\"1/N:      DJ=0.25,  FTSE=0.25,  CAC=0.25,  Nikkei=0.25\"),\n       col = c(\"blue\",\"red\", \"purple\"), pch = 19,\nbg = \"white\", cex = 0.9)\n```\n\n::: {.cell-output-display}\n![Original allocation, minimum-variance alternative, and 1/N benchmark.](07-value-at-risk_files/figure-html/fig-haistroiabaawner2-1.png){#fig-haistroiabaawner2 width=672}\n:::\n:::\n\n\n\n\nThe efficient frontier also changes when the investable universe changes. The following resource shows the US efficient frontier using five industry-sorted portfolios as investment assets.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/Fq4UlUCneyI\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/Fq4UlUCneyI\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nIncreasing the number of investment assets can expand the mean-variance frontier when the added assets bring useful return, risk, or correlation characteristics. The following resource compares 10 versus 12 US industry-sorted portfolios.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/_GnJRviyYJI\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/_GnJRviyYJI\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nThe mean and standard deviation estimates can also be used to simulate 10,000 possible one-day returns for Friday September 26, 2008. The histograms below are model-based checks of where the realized return falls relative to the fitted normal distribution.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/P1Ky6-a8DE0\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/P1Ky6-a8DE0\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\nThe first simulated distribution corresponds to the minimum-variance portfolio.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nM <- rnorm(10000, R_min, S_min)\nhist(M, 100, xlim = c(-4, 4), ylim = c(0, 450), main = \"\")\nabline(v = R_min.realized, col = \"blue\", lwd = 3)\nabline(v = quantile(M, 0.025), lty = 2)\nabline(v = quantile(M, 0.975), lty = 2)\n```\n\n::: {.cell-output-display}\n![Minimum-variance allocation and realized outcome.](07-value-at-risk_files/figure-html/fig-mvraroib-1.png){#fig-mvraroib width=672}\n:::\n:::\n\n\n\n\nThe blue line falls on the gain side of the simulated distribution. For this particular day, the minimum-variance allocation produced a positive realized return under the observed market moves.\n\nThe second simulated distribution corresponds to the original allocation.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nH = rnorm(10000, R_benchmark, S_benchmark)\nhist(H, 100, xlim = c(-4, 4), ylim = c(0, 450), main = \"\")\nabline(v = R_benchmark.realized, col = \"blue\", lwd = 3)\nabline(v = quantile(H, 0.025), lty = 2)\nabline(v = quantile(H, 0.975), lty = 2)\n```\n\n::: {.cell-output-display}\n![Original allocation and realized outcome.](07-value-at-risk_files/figure-html/fig-hsoraro-1.png){#fig-hsoraro width=672}\n:::\n:::\n\n\n\n\nThe blue line for the original allocation falls on the loss side. Comparing this histogram with the previous one shows that changing the weights changes both the center of the fitted distribution and the realized portfolio return.\n\nThe portfolio that targets the CAC 40 expected return is evaluated in the same way.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nCa <- rnorm(10000, R_cac40, S_cac40)\nhist(Ca, 100, xlim = c(-4, 4), ylim = c(0, 450), main = \"\")\nabline(v = R_cac40.realized, col = \"blue\", lwd = 3)\nabline(v = quantile(Ca, 0.025), lty = 2)\nabline(v = quantile(Ca, 0.975), lty = 2)\n```\n\n::: {.cell-output-display}\n![CAC40 target-return allocation and realized outcome.](07-value-at-risk_files/figure-html/fig-craro-1.png){#fig-craro width=672}\n:::\n:::\n\n\n\n\nThe CAC 40 target-return allocation also produces a positive realized return in this one-day evaluation. Because this allocation uses a negative FTSE weight, its apparent improvement has to be read together with short-selling feasibility and implementation constraints.\n\nThe portfolio that targets the CAC 40 expected return can also be located in mean-variance space.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(S, ER, type = \"l\", lwd = 3, xlim = c(0.7, 1.6),\n     ylim = c(-0.022, 0.007), ylab = \"Expected return\",\n     xlab = \"Standard deviation\")\npoints(diag(sigma)^0.5, E)\nabline(0, 0, lty = 3)\npoints(S_cac40, R_cac40, col = \"red\", pch = 19, cex = 2)\npoints(0.68, R_cac40.realized, col = \"red\", pch = 15, cex = 2)\ntext(S_cac40, R_cac40, \"CAC40\n     expected return\", pos = 2, cex = 0.8)\ntext(sd,E,stocks,adj=-0.5,cex=0.8)\nW_benchmark = alpha / 10000\nR_benchmark = c(t(W_benchmark) %*% E)\nS_benchmark = c(t(W_benchmark) %*% sigma %*% W_benchmark)^0.5\npoints(S_benchmark, R_benchmark, col = \"blue\", pch = 19, cex = 2)\npoints(0.68, R_benchmark.realized, col = \"blue\", pch = 15, cex = 2)\nabline(0,R_benchmark / S_benchmark, lty = 3, col = \"blue\")\nabline(0,R_cac40 / S_cac40, lty = 3, col = \"red\")\nabline(0,E[3] / sd[3], lty = 3)\nabline(v = S_cac40, lty = 3)\ntext(S_benchmark, R_benchmark, \"Benchmark\n     allocation\", adj = -0.3, cex = 0.8, pos = 1)\nlegend(\"bottomleft\",\n       legend = c(\"DJ=0.4,     FTSE=0.3,      CAC=0.1,     Nikkei=0.2\",\n                          \"DJ=0.607, FTSE=-0.403, CAC=0.459, Nikkei=0.336\"), col = c(\"blue\", \"red\"),\n       pch = 19, bg = \"white\", cex = 0.9)\n```\n\n::: {.cell-output-display}\n![CAC40 target-return allocation in mean-variance space.](07-value-at-risk_files/figure-html/fig-eoanoarce-1.png){#fig-eoanoarce width=672}\n:::\n:::\n\n\n\nThe realized returns on Friday September 26, 2008 are used to compare the three allocations.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(R_min.realized)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2629549\n```\n\n\n:::\n\n```{.r .cell-code}\n(R_benchmark.realized)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5583249\n```\n\n\n:::\n\n```{.r .cell-code}\n(R_cac40.realized)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5183212\n```\n\n\n:::\n:::\n\n\n\n\nThe original portfolio allocation produces a loss on the realized day. It would lead to a return of -0.558%, equivalent to a loss of 0.558%. The minimum-variance allocation would lead to a positive return of 0.2629%, and the portfolio that targets the CAC 40 expected return leads to a realized return of 0.518%. The last case uses a short FTSE position, so it requires additional feasibility checks before being interpreted as an implementable allocation.\n\n## Model building approach with optimal weights\n\nThe two optimized portfolios are evaluated with the model-building VaR approach. This keeps the covariance estimate fixed and changes only the portfolio weights, which isolates the effect of allocation on VaR. For any weight vector $w$, the dollar allocation is $\\alpha(w)=10{,}000w$ in thousands of dollars and the normal VaR is\n\n$$\nVaR_{0.99}(w)=z_{0.99}\\sqrt{\\alpha(w)'\\Sigma\\alpha(w)}.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Model-building approach with equal observation weights.\nalpha2 <- c(W_min * 10000)\nalpha3 <- c(W.cac40 * 10000)\n# Minimum-variance optimal portfolio.\nPvar2 <- t(alpha2) %*% Rcov %*% alpha2\nPsd2 <- Pvar2^0.5\nVaR.ew.optimal <- qnorm(0.99, 0, 1) * Psd2\n# CAC 40 target-return optimal portfolio.\nPvar3 <- t(alpha3) %*% Rcov %*% alpha3\nPsd3 <- Pvar3^0.5\nVaR.ew.optimal.cac <- qnorm(0.99, 0, 1) * Psd3\n```\n:::\n\n\n\n\nThe results table includes the model-building VaR estimates with optimal weights.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method =\n        c(\"Model building equal observation weights, minimum variance weights\",\n          \"Model building equal observation weights, targeting CAC40\"),\n          VaR = c(VaR.ew.optimal, VaR.ew.optimal.cac)) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                          VaR.method      VaR\n1                Historical approximate quantile(), original weights 218.3281\n2                            Historical simulation, original weights 253.3850\n3                              Model building EWMA, original weights 470.9187\n4 Model building equal observation weights, minimum variance weights 194.3892\n5         Model building equal observation weights, original weights 217.9751\n6          Model building equal observation weights, targeting CAC40 203.7821\n```\n\n\n:::\n:::\n\n\n\nThe second calculation uses the EWMA covariance matrix.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPvar2_EWMA <- t(alpha2) %*% C %*% alpha2\nPsd2_EWMA <- Pvar2_EWMA^0.5\nVaR.ewma.optimal <- qnorm(0.99, 0, 1) * Psd2_EWMA\nVaR.ewma.optimal\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 338.3195\n```\n\n\n:::\n\n```{.r .cell-code}\nPvar3_EWMA <- t(alpha3) %*% C %*% alpha3\nPsd3_EWMA <- Pvar3_EWMA^0.5\nVaR.ewma.optimal.cac <- qnorm(0.99, 0, 1) * Psd3_EWMA\nVaR.ewma.optimal.cac\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         [,1]\n[1,] 348.1888\n```\n\n\n:::\n:::\n\n\n\n\nThe results table includes the EWMA VaR estimates with optimal weights.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method =\n            c(\"Model building EWMA, minimum variance weights\",\n              \"Model building EWMA, targeting CAC40\"),\n          VaR = c(VaR.ewma.optimal, VaR.ewma.optimal.cac)) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                          VaR.method      VaR\n1                Historical approximate quantile(), original weights 218.3281\n2                            Historical simulation, original weights 253.3850\n3                      Model building EWMA, minimum variance weights 338.3195\n4                              Model building EWMA, original weights 470.9187\n5                               Model building EWMA, targeting CAC40 348.1888\n6 Model building equal observation weights, minimum variance weights 194.3892\n7         Model building equal observation weights, original weights 217.9751\n8          Model building equal observation weights, targeting CAC40 203.7821\n```\n\n\n:::\n:::\n\n\n\n\n## Historical approach with optimal weights\n\nThe final comparison returns to historical simulation and applies the same scenario returns to the optimized weights. This keeps the market scenarios fixed and changes only the portfolio exposure. For 500 scenarios, the empirical 99% VaR is again the fifth-worst loss.\n\n$$\nVaR_{0.99}^{hist}(w)=l_{(5)}(w),\n$$\n\nwhere losses are sorted from largest to smallest.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf.Adj.S <- df.Adj.S %>%\n  mutate(p2 = (alpha2[1] * SDJIA / DJIA[501]) +\n             (alpha2[2] * SFTSE100 / AFTSE100[501]) +\n             (alpha2[3] * SCAC40 / ACAC40[501]) +\n             (alpha2[4] * SNikkei / ANikkei[501])) %>%\n  mutate(l2 = 10000 - p2) %>% # Losses l\n  mutate(p3 = (alpha3[1] * SDJIA / DJIA[501]) +\n             (alpha3[2] * SFTSE100 / AFTSE100[501]) +\n             (alpha3[3] * SCAC40 / ACAC40[501]) +\n             (alpha3[4] * SNikkei / ANikkei[501])) %>%\n  mutate(l3 = 10000 - p3) # Losses l\n```\n:::\n\n\n\n\nThe new portfolio losses are calculated under the optimized weights.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nl2 <- df.Adj.S %>%\n  filter(obs > 0 & obs < 501) %>%\n  select(l2) %>%\n  unlist()\n\nl2.tomorrow <- df.Adj.S %>%\n  filter(obs == 501) %>%\n  select(l2) %>%\n  unlist()\n\nl3 <- df.Adj.S %>%\n  filter(obs > 0 & obs < 501) %>%\n  select(l3) %>%\n  unlist()\n\nl3.tomorrow <- df.Adj.S %>%\n  filter(obs == 501) %>%\n  select(l3) %>%\n  unlist()\n```\n:::\n\n\n\n\nThe benchmark allocation provides the reference distribution.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(l, type = \"h\", ylim = c(-600, 600), lwd = 2,\n     xlab = \"500 scenarios (sorted by historical date)\",\nylab = \"Portfolio gains (-) and losses (+)\",\ncol = ifelse(l < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l), lty = 2)\nabline(h = min(l), lty = 2)\n```\n\n::: {.cell-output-display}\n![Losses with the original weights DJ=0.4, FTSE=0.3, CAC=0.1, Nikkei=0.2.](07-value-at-risk_files/figure-html/fig-lwhsadfcn-1.png){#fig-lwhsadfcn width=672}\n:::\n:::\n\n\n\n\nThe benchmark distribution contains several large downside scenarios, and the fifth-worst loss is the historical 99% VaR for the original allocation.\n\nThe one-day 99% value at risk can be estimated as the fifth-worst loss.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(l)[496]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   l487 \n253.385 \n```\n\n\n:::\n:::\n\n\n\n\nThe historical approach is then applied with minimum-variance weights.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(l2, type = \"h\", ylim = c(-600, 600), lwd = 2,\n     xlab = \"500 scenarios (sorted by historical date)\",\n     ylab = \"Portfolio gains (-) and losses (+)\",\n     col = ifelse(l2 < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l2), lty = 2)\nabline(h = min(l2), lty = 2)\n```\n\n::: {.cell-output-display}\n![Losses with minimum-variance weights DJ=0.56, FTSE=0.038, CAC=0.022, Nikkei=0.38.](07-value-at-risk_files/figure-html/fig-lwhsadfcn2-1.png){#fig-lwhsadfcn2 width=672}\n:::\n:::\n\n\n\n\nThe range of losses and gains is reduced under the minimum-variance weights. The one-day 99% Value at Risk can be estimated as the fifth-worst loss.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(l2)[496]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   l2487 \n213.6898 \n```\n\n\n:::\n:::\n\n\n\nThe results table is updated with this case.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method = \"Historical simulation, minimum variance weights\",\n          VaR = sort(l2)[496]) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                          VaR.method      VaR\n1                Historical approximate quantile(), original weights 218.3281\n2                    Historical simulation, minimum variance weights 213.6898\n3                            Historical simulation, original weights 253.3850\n4                      Model building EWMA, minimum variance weights 338.3195\n5                              Model building EWMA, original weights 470.9187\n6                               Model building EWMA, targeting CAC40 348.1888\n7 Model building equal observation weights, minimum variance weights 194.3892\n8         Model building equal observation weights, original weights 217.9751\n9          Model building equal observation weights, targeting CAC40 203.7821\n```\n\n\n:::\n:::\n\n\n\n\nThe final case is the portfolio targeting the CAC 40 expected return.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(l3, type = \"h\", ylim = c(-600, 600), lwd = 2,\n     xlab = \"500 scenarios (sorted by historical date)\",\n     ylab = \"Portfolio gains (-) and losses (+)\",\n     col = ifelse(l3 < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l3), lty = 2)\nabline(h = min(l3), lty = 2)\n```\n\n::: {.cell-output-display}\n![Losses with CAC40 target-return weights DJ=0.607, FTSE=-0.403, CAC=0.459, Nikkei=0.336.](07-value-at-risk_files/figure-html/fig-lwcoadfcn-1.png){#fig-lwcoadfcn width=672}\n:::\n:::\n\n\n\n\nThe CAC 40 target-return allocation also compresses much of the loss range while still allowing larger gains in some scenarios. The one-day 99% Value at Risk can be estimated as the fifth-worst loss. Because this portfolio includes a short FTSE position, its risk reduction is linked to an exposure that may be constrained in practice.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(l3)[496]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   l3494 \n248.8909 \n```\n\n\n:::\n:::\n\n\n\nThe results table is updated again.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nResults.updated <- Results.updated %>%\n  add_row(VaR.method = \"Historical simulation, targeting CAC40\",\n          VaR = sort(l3)[496]) %>%\n  arrange(VaR.method)\nResults.updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                                           VaR.method      VaR\n1                 Historical approximate quantile(), original weights 218.3281\n2                     Historical simulation, minimum variance weights 213.6898\n3                             Historical simulation, original weights 253.3850\n4                              Historical simulation, targeting CAC40 248.8909\n5                       Model building EWMA, minimum variance weights 338.3195\n6                               Model building EWMA, original weights 470.9187\n7                                Model building EWMA, targeting CAC40 348.1888\n8  Model building equal observation weights, minimum variance weights 194.3892\n9          Model building equal observation weights, original weights 217.9751\n10          Model building equal observation weights, targeting CAC40 203.7821\n```\n\n\n:::\n:::\n\n\n\n\nThe three historical approaches are compared side by side.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow=c(1, 3), oma = c(0, 0, 2, 0))\npar(pty = \"s\")\nplot(l, type = \"h\", ylim = c(-600, 600), lwd = 2, xlab = \"\",\n     main = \"Benchmark allocation\",\n     ylab = \"Portfolio gains (-) and losses (+)\",\n     col = ifelse(l < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l), lty = 2)\nabline(h = min(l), lty = 2)\nplot(l2, type = \"h\", ylim = c(-600, 600), lwd = 2,\n     main = \"Minimum variance\",\n     xlab = \"500 scenarios sorted by historical date\", ylab = \"\",\n     col = ifelse(l2 < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l2), lty = 2)\nabline(h = min(l2), lty = 2)\nplot(l3, type = \"h\", ylim = c(-600, 600), lwd = 2, xlab = \"\",\n     main = \"CAC40 target return\", ylab = \"\",\n     col = ifelse(l3 < 0, \"blue\", \"red\"))\nabline(0, 0)\nabline(v = 0)\nabline(h = max(l3), lty = 2)\nabline(h = min(l3), lty = 2)\n```\n\n::: {.cell-output-display}\n![Historical losses under original, minimum-variance, and CAC40-target weights.](07-value-at-risk_files/figure-html/fig-hsaoaoa-1.png){#fig-hsaoaoa width=672}\n:::\n:::\n\n\n\n\nThe side-by-side view makes the effect of allocation visible. The optimized portfolios reduce the height of the worst loss bars in this historical window, while the CAC 40 target-return case changes the distribution partly through the short FTSE exposure.\n\nThe quantiles provide a compact comparison of the three loss distributions.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlq <- quantile(l, c(0.25, 0.5, 0.75))\nlq2 <- quantile(l2, c(0.25, 0.5, 0.75))\nlq3 <- quantile(l3, c(0.25, 0.5, 0.75))\nll <- data.frame(lq, lq2, lq3)\ncolours <- c(\"red\", \"orange\", \"blue\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(as.matrix(t(ll)), beside = TRUE, col = colours,\n        ylim = c(-60, 60), xlab = \"Quantiles\",\n        ylab = \"Portfolio gains (-) and Losses (+)\")\nlegend(\"topleft\", c(\"Benchmark\",\"Minimum variance\",\n                    \"CAC40 target return\"), cex = 1.3, bty = \"n\",\n       fill = colours)\n```\n\n::: {.cell-output-display}\n![Loss quantiles under alternative portfolio weights.](07-value-at-risk_files/figure-html/fig-qcold-1.png){#fig-qcold width=672}\n:::\n:::\n\n\n\n\nThe quantile comparison summarizes the same message without the full time ordering of scenarios: changing weights shifts the empirical loss distribution, and VaR changes because it is a tail quantile of that distribution.\n\nThe chapter's main value is integration. The VaR number is the final summary,\nafter the analyst prepares international index data, converts foreign values\ninto US dollars, defines portfolio weights, generates loss scenarios, estimates\nvolatility and covariance inputs, compares allocation choices, and reads the\nrealized outcome. Within the Financial Modeling with R path, VaR turns data,\nreturns, allocation, and market-risk assumptions into a single loss statement\nthat can be audited and recomputed.\n",
    "supporting": [
      "07-value-at-risk_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/vembedr-0.1.5/css/vembedr.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}